import 'server-only'

import { aiVisibilityReport, efeonceGraphicLine } from '@efeoncepro/axis-tokens'

import layoutProjection from './ai-visibility-layout.generated.json'

/** TASK-1938. AXIS owns values; this adapter converts reference pixels to PDF points.
 * Editorial extension is generated by AXIS, with source and approval hashes.
 * Published package pins remain intact; no sibling checkout is a runtime dependency.
 */
export const ReportPdfBrand = aiVisibilityReport
export const ReportPdfEditorial = layoutProjection.extension
export const px = (value: number): number => value * (72 / aiVisibilityReport.page.dpi)

export const ReportPdfColors = {
  ...aiVisibilityReport.palette,
  ...layoutProjection.extension.palette,
  onDark: aiVisibilityReport.palette.paper,
  onDarkMuted: aiVisibilityReport.palette.softOnDark
} as const

export const ReportPdfFonts = {
  body: 'Poppins Regular',
  light: 'Poppins Light',
  medium: 'Poppins Medium',
  semibold: 'Poppins',
  sloganLead: 'Poppins ExtraBold Italic',
  sloganSpace: 'Poppins ExtraBold',
  sloganWord: 'Poppins Black Italic',
  display: (weight: number = aiVisibilityReport.type.display.weight) => `AI Visibility Bricolage ${weight}`
} as const

type TypeRole = { family: string; weight: number; sizePx: number; lineHeight?: number; tracking?: number }

/** Tracking is expressed in em in AXIS, in pt in react-pdf. */
export const pdfType = (role: TypeRole) => ({
  fontFamily:
    role.family === 'Bricolage Grotesque'
      ? ReportPdfFonts.display(role.weight)
      : role.weight === 300
        ? ReportPdfFonts.light
        : role.weight === 500
          ? ReportPdfFonts.medium
          : role.weight >= 600
            ? ReportPdfFonts.semibold
            : ReportPdfFonts.body,
  fontSize: px(role.sizePx),
  ...(role.lineHeight !== undefined ? { lineHeight: role.lineHeight } : {}),
  ...(role.tracking !== undefined ? { letterSpacing: px(role.sizePx) * role.tracking } : {})
})

export const ReportPdfPage = {
  format: aiVisibilityReport.page.format,
  coverPadding: aiVisibilityReport.cover.paddingPx.map(px),
  interiorPadding: aiVisibilityReport.interior.paddingPx.map(px)
} as const

const slogan = aiVisibilityReport.backCover.brandBlock
const sloganFontPx = (slogan.logoWidthPx * slogan.sloganOfLogo) / efeonceGraphicLine.slogan.widthEmByWord.Engine

export const ReportPdfSlogan = {
  logoWidth: px(slogan.logoWidthPx),
  fontSize: px(sloganFontPx),
  gap: px(sloganFontPx * slogan.sloganGapOfFont),
  lead: efeonceGraphicLine.slogan.lead,
  word: slogan.sloganWord
} as const

export const ReportPdfSeverityColors = efeonceGraphicLine.measureSeverity.colors

/** Preblend on the AXIS ground: native PDF border painting does not support rgba reliably. */
export const pdfAlpha = (hex: string, opacity: number): string => {
  const channels = hex
    .replace('#', '')
    .match(/.{2}/g)!
    .map(channel => parseInt(channel, 16))

  const ground = ReportPdfColors.ground
    .replace('#', '')
    .match(/.{2}/g)!
    .map(channel => parseInt(channel, 16))

  return (
    '#' +
    channels
      .map((channel, i) =>
        Math.round(channel * opacity + ground[i] * (1 - opacity))
          .toString(16)
          .padStart(2, '0')
      )
      .join('')
  )
}
