import fs from 'node:fs';
import sharp from 'sharp';
const dir='ai-generations/2026-09-22_aeo-fuente-preferida';
const plan=JSON.parse(fs.readFileSync(`${dir}/piezas.json`));
for(const suffix of ['916','169']){
 const items=plan.filter(s=>s.id.endsWith(suffix));const w=suffix==='916'?390:780,h=suffix==='916'?693:439;
 const layers=await Promise.all(items.map(async(s,i)=>({input:await sharp(`${dir}/out/${s.id}.png`).resize(w,h).toBuffer(),left:16+(i%2)*(w+16),top:16+Math.floor(i/2)*(h+16)})));
 await sharp({create:{width:2*w+48,height:2*h+48,channels:3,background:'#d7d7d7'}}).composite(layers).jpeg({quality:94}).toFile(`${dir}/out/contacto-${suffix}.jpg`);
}
fs.writeFileSync(`${dir}/ENTREGA.md`,'# SEO + AEO — fuente preferida\n\nCuatro key visuals, dos formatos por concepto. Exportaciones PNG 1080 × 1920 y 1920 × 1080. Propuestas para revisión, sin publicar.\n\n## Corrección de Nexa\n\nEn ¿Te reconoces? se reemplazaron las dos tomas: cámara junto a su hombro, tableta orientada hacia ella, mirada a la pantalla y ambas manos sujetando los bordes. Se eliminó el gesto de señalar. Las interfaces y el contraste torre/bodega son ilustrativos, no capturas de un diagnóstico real.\n\n## Composición y revisión\n\nGeneración y ediciones con imagegen; prompts construidos con construirPrompt. Composición con scripts/foto/componer.mjs y SVG oficial. No se aplicaron scrims. Firma centrada, ancho 20% del lado corto. Contraste medido en out/qa.json. Lechos: respaldo oscuro (01 y04), antepecho oscuro (02), superficie clara (03). Esta última se pidió como piso pero el resultado se lee como superficie elevada: no se certifica como cumplimiento literal de esa ficha. La aprobación visual final sigue abierta.\n\nLa palanca instrumento de04 fue una clasificación incorrecta de la ficha inicial: la imagen es un gesto manual sobre pantalla; no demuestra mirar a través de un instrumento óptico. La pieza03 conserva la tableta secundaria que gustó al operador; no se afirma cumplimiento literal de la palanca proyección sin pantallas.\n\n## Conceptos\n\n1. ¿Sales tú? Exclusión: respuesta y fuentes con un espacio ausente.\n2. ¿Te reconoces? Representación: contraste entre negocio real y descripción ilustrativa equivocada.\n3. Sé la referencia. Aspiración: fuente destacada dentro de la respuesta.\n4. Que te elijan. Decisión: instante anterior al toque.\n\nEstos mecanismos son hipótesis creativas; el efecto sobre clics se valida con campaña, no con una imagen generada.\n');
