import fs from 'node:fs';
import {construirPrompt} from '../../../scripts/foto/build-prompt.mjs';
const dir='ai-generations/2026-09-22_aeo-fuente-preferida';
const concepts=[
{id:'01-fuera',palanca:'ausencia',objetos:['codex'],scene:`A startling extreme low viewpoint across a black glass digital workbench in a monumental but real contemporary studio. A large razor-thin tilted display faces camera; on it an unmistakable AI answer layout: one question row, several answer rows and exactly three source cards, with two small filled blue source cards and a conspicuous EMPTY outlined slot. UI text exists but is physically too small to read, no invented large words. A tiny physical 25cm Codex character stands immediately beside the display, reaching toward the two populated sources, continuing to answer after the humans left. The near empty graphite executive chair is dramatically pulled back and partly out of frame; its curved back is the foreground. Blue anodised display stand is a strong Efeonce colour independent of Codex. Screen and character are unusually close and large, with strong diagonal perspective. Hard shaft of neutral daylight strikes only the display edges and character, long crisp shadows across concrete. No cute toy shop mood: tense premium editorial advertising, palpable absence, very bold silhouettes.`},
{id:'02-reconoces',palanca:'reflejo',identidad:['nexa'],objetos:['polo-efeonce'],scene:`A cinematic double-reality scene in a dark architectural digital studio. Canonical Nexa in the exact navy Efeonce corporate pique polo from garment references, smartwatch on left wrist, silver earrings, natural healthy skin, neutral concerned mouth NOT smiling. She is in three-quarter profile studying a huge angled optical glass panel. A tablet in her hands clearly shows a modern architectural tower photograph within a website page. Reflected in the large glass panel is an AI answer card describing that same entity with a visibly incompatible derelict little warehouse photograph. Both photographs and their digital card structures must be immediately clear and visually different, no small-detail puzzle. This is an illustrative mismatch, NOT two faces and NOT a distorted face. The two screens form a sharp V in depth, Nexa's face is behind and smaller than the answer. One hand gestures toward the mismatch. Her chest mark is naturally turned away and in deep shadow; no invented embroidery. Hard neutral side light outlines cheek and tablet, one small functional orange tablet clasp, active blue interface accents. Real photographed glass reflections, no holograms, no floating UI.`},
{id:'03-referencia',palanca:'proyeccion',identidad:['nexa'],objetos:['polo-efeonce'],scene:`A breathtaking but physically credible digital projection studio: a monumental AI answer is projected onto textured pale concrete in the right/central action zone, visible material grain through its white answer lines and blue source card. The source card is the visual hero, vastly larger than the small tablet that contains the matching website below it. Canonical Nexa, wearing exact navy Efeonce corporate pique polo from refs, in profile and looking up at the answer, holds the source tablet. She is small relative to the projection, clearly examining its source. Do not look at camera. A visible low projector on a blue anodised equipment pedestal makes a raking shaft of light through subtle clean haze; its beam terminates below the headline reservation. One selected blue source card in the projection matches the blue source card on the tablet through exact visual shape and thumbnail, not strings of mystical light. Physical shadows, tangible projector and concrete. Healthy natural Nexa face, no smile, silver earrings, smartwatch left. Chest embroidery is at an oblique unreadable angle. Strong high-key projection against deep warm-neutral shadows, dramatic perspective, no cyan colour grading.`},
{id:'04-elegida',palanca:'instrumento',instrumento:'the large optical glass surface of a real inclined touch display, seen at almost grazing angle',objetos:['codex'],scene:`Extreme close perspective of a real inclined touch display showing an AI answer and three source cards, the nearest selected blue source card enormously foreshortened toward camera. A real human index fingertip hovers two millimetres above that card and its perfect reflection nearly touches it: the decisive instant BEFORE a tap. The hand belongs to an anonymous user outside frame, anatomically correct. Small physical Codex stands far behind the display, 25cm scale and secondary, watching the choice, not waving at camera. Camera at glass level, powerful diagonal, one source card sharply focused, other cards progressively smaller and defocused. A physical active-blue aluminium frame supports the display. Restrained generic response lines and source thumbnail shapes, no third-party wordmarks, no readable fabricated UI text. Hard neutral window light creates crisp rim on fingertip and optical reflections with deep detail, photographic not CGI. Black equipment housing in extreme foreground dissolves into deep blur.`}
];
let jobs=[];
for(const c of concepts)for(const formato of ['9:16','16:9']){
 const suffix=formato==='9:16'?'916':'169'; const id=c.id+'-'+suffix;
 const ficha={id,formato,impacto:true,palanca:c.palanca,...(c.instrumento?{instrumento:c.instrumento}:{}),...(c.identidad?{identidad:c.identidad}:{}),objetos:c.objetos,reservas:{texto:{muro:'the fine-grained graphite plaster of the real studio wall, naturally in deep even shadow',tinta:'blanca'}},lecho:{objeto:'the rounded dark graphite upholstered back of the empty viewer chair close to lens, outside all light',tono:'near black charcoal fabric in natural shadow with extremely soft optical defocus, not a graphic band'},escena:c.scene+' '+(suffix==='916'?'VERTICAL action composition: all storytelling, heads, hands, projection and screens between 37% and 77% of height, large and legible, with no bright objects in upper 34%.':'WIDE action composition: all story objects, projection, heads, hands and light beams inside the right 55%, from 12% to 80% height. Entire left 42% is real graphite plaster in shadow for typography. The action fills its allocated space boldly.')+' This is a CLEAN PHOTOGRAPHIC PLATE: no headline, no CTA, no signature, no watermark. Preserve natural camera realism and exact reference identity. NO decorative books, coffee cups, trophy, podium, neon tubes, floating cards or holograms. Digital interfaces are physically on screens or projected on real concrete.'};
 const built=construirPrompt(ficha);
 fs.writeFileSync(`${dir}/brief/${id}.json`,JSON.stringify(ficha,null,2));fs.writeFileSync(`${dir}/brief/${id}.prompt.txt`,built.prompt);
 jobs.push({id,prompt:built.prompt,refs:built.imagenes});
}
fs.writeFileSync(`${dir}/brief/jobs.json`,JSON.stringify(jobs,null,2));
console.log(JSON.stringify(jobs.map(({id,refs})=>({id,refs})),null,2));
