import{chromium}from'playwright';import fs from'node:fs';import path from'node:path';import crypto from'node:crypto';import{spawn}from'node:child_process';import{once}from'node:events';
const D=path.dirname(new URL(import.meta.url).pathname),mode=process.argv[2]||'qa';
const b=await chromium.launch(),page=await b.newPage({viewport:{width:1080,height:1920},deviceScaleFactor:1});await page.setContent(fs.readFileSync(D+'/overlay-preview.html','utf8'));await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode()));document.body.classList.add('render');document.documentElement.style.setProperty('--scale','1')});
const shots=[['year',.9],['plus-only',2.72],['proof',3.65],['agency-intro',5.28],['agency',6.4],['thanks',9.15],['blue',10.8],['purple',13.2]];
for(const[name,t]of shots){await page.evaluate(t=>renderFrame(t,true),t);await page.screenshot({path:D+'/qa/'+name+'.png'});}
const t=3.8;await page.evaluate(t=>renderFrame(t,false),t);const a=await page.screenshot({omitBackground:true});await page.evaluate(()=>renderFrame(.3,false));await page.evaluate(t=>renderFrame(t,false),t);const c=await page.screenshot({omitBackground:true});const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const evidence={seekDeterministic:hash(a)===hash(c),firstHash:hash(a),returnHash:hash(c),resolution:[1080,1920],fps:24,scope:'Text and closing graphics only. Preview backdrop is an existing still, not a generated film.',paidCalls:0};fs.writeFileSync(D+'/qa/engine-check.json',JSON.stringify(evidence,null,2));fs.writeFileSync(D+'/cue-sheet.json',JSON.stringify(await page.evaluate(()=>titleCues),null,2));
if(mode==='render'){
 const alpha=spawn('ffmpeg',['-hide_banner','-loglevel','error','-y','-f','image2pipe','-framerate','24','-vcodec','png','-i','pipe:0','-an','-c:v','prores_ks','-profile:v','4','-pix_fmt','yuva444p10le','-alpha_bits','16',D+'/titulos-y-firma-alpha.mov'],{stdio:['pipe','inherit','inherit']});
 const preview=spawn('ffmpeg',['-hide_banner','-loglevel','error','-y','-f','image2pipe','-framerate','24','-vcodec','mjpeg','-i','pipe:0','-an','-c:v','libx264','-crf','17','-preset','fast','-pix_fmt','yuv420p','-movflags','+faststart',D+'/prueba-textos-sobre-fondo-referencia.mp4'],{stdio:['pipe','inherit','inherit']});
 for(let i=0;i<342;i++){await page.evaluate(t=>{document.body.dataset.layer='text';renderFrame(t,false)},i/24);const png=await page.screenshot({type:'png',omitBackground:true});if(!alpha.stdin.write(png))await once(alpha.stdin,'drain');await page.evaluate(t=>{document.body.dataset.layer='preview';renderFrame(t,true)},i/24);const jpg=await page.screenshot({type:'jpeg',quality:96});if(!preview.stdin.write(jpg))await once(preview.stdin,'drain');if(i%72===0)console.log('Rendered frame '+i+'/342');}
 alpha.stdin.end();preview.stdin.end();const statuses=await Promise.all([once(alpha,'close'),once(preview,'close')]);if(statuses.some(x=>x[0]!==0))throw Error('Encoder failed');console.log('Text alpha and reference preview exported');
 const bubble=spawn('ffmpeg',['-hide_banner','-loglevel','error','-y','-f','image2pipe','-framerate','24','-vcodec','png','-i','pipe:0','-an','-c:v','prores_ks','-profile:v','4','-pix_fmt','yuva444p10le','-alpha_bits','16',D+'/url-bubble-luminosidad-alpha.mov'],{stdio:['pipe','inherit','inherit']});
 const bubbleDone=once(bubble,'close');
 for(let i=0;i<96;i++){await page.evaluate(t=>{document.body.dataset.layer='bubble';renderFrame(t,false)},10.25+i/24);const png=await page.screenshot({type:'png',omitBackground:true});if(!bubble.stdin.write(png))await once(bubble.stdin,'drain');}bubble.stdin.end();const code=await bubbleDone;if(code[0]!==0)throw Error('Bubble encoder failed');console.log('Separate URL layer exported: use Luminosity; opacity .72 already baked in alpha');
}
await b.close();console.log(JSON.stringify(evidence));
