/** TASK-1863. Versioned deterministic translations; tags and prompt identities stay stable. */
import type { ResolvedGrowthMarket } from '@/lib/growth/markets'

import { FRENCH_PROMPTS } from './localized-fr'
import type { GrowthAiVisibilityPromptPack } from './prompt-pack-v1'

// Every translated entry has the same placeholders and buyer intent as its source.
const en: Record<string, string> = {
  p01: 'Which {{category}} agencies help businesses in {{market}}?',
  p02: 'I need to improve {{painPoint}} for my company. What type of agency or service should I look for in {{market}}?',
  p03: 'What are the best {{category}} agencies in {{market}}?',
  p04: 'Recommend reliable {{category}} providers for an enterprise company in {{market}}.',
  p05: '{{brand}} versus {{competitor}}: which is better for {{category}}?',
  p06: 'What alternatives to {{competitor}} are available for {{category}} in {{market}}?',
  p07: 'Is {{brand}} a reliable agency for {{category}}?',
  p08: 'What reviews or opinions are there about {{brand}} in {{year}}?',
  p09: 'How much does it cost to hire an agency for {{category}} in {{market}}?',
  p10: 'What should I consider before hiring {{brand}} for {{category}}?',
  p11: 'Best {{category}} agency in {{market}}.',
  p12: 'Enterprise {{category}} agency for a large brand in {{market}}.',
  p13: 'Common problems, complaints or criticisms about {{brand}}.',
  p14: 'What does {{brand}} do and whom does it serve?',
  p15: 'What does {{brand}} specialize in?',
  p16: 'Who are the leaders in {{category}} in {{market}} in {{year}}?',
  cb01: 'What are the best {{category}} in {{market}}?',
  cb02: 'I am evaluating {{category}} options in {{market}}. Which would you recommend?',
  cb03: 'Which {{category}} have the best reputation in {{market}}?',
  cb04: '{{brand}} or {{competitor}}: which is the better choice?',
  cb05: 'What alternatives to {{competitor}} are available in {{category}}?',
  cb06: 'Is {{brand}} worth it? What experiences do its customers report?',
  cb07: 'What reviews or opinions are there about {{brand}} in {{year}}?',
  cb08: 'Which {{category}} offer the best value for money in {{market}}?',
  cb09: 'What should I consider before choosing {{brand}}?',
  cb10: 'Common problems, complaints or claims about {{brand}}.',
  cb11: 'Best {{category}} in {{market}}.',
  cb12: 'What is {{brand}} and what does it offer?',
  cb13: 'What does {{brand}} stand out for?',
  cb14: 'Which {{category}} lead the market in {{market}} in {{year}}?',
  sa01: 'What are the best {{category}} platforms for businesses in {{market}}?',
  sa02: 'I need a {{category}} tool for my company. What options should I evaluate?',
  sa03: '{{brand}} vs {{competitor}}: which is better for {{category}}?',
  sa04: 'What alternatives to {{competitor}} exist for {{category}}?',
  sa05: 'What integrations and capabilities does {{brand}} offer?',
  sa06: 'What reviews or opinions are there about {{brand}} in {{year}}?',
  sa07: 'What limitations or problems do {{brand}} users report?',
  sa08: 'How much does a {{category}} solution cost for a company in {{market}}?',
  sa09: 'What plans and prices does {{brand}} offer?',
  sa10: 'Which {{category}} platform is best for a large enterprise in {{market}}?',
  sa11: 'What does {{brand}} do and what types of companies does it serve?',
  sa12: 'Who are the leaders in {{category}} in {{market}} in {{year}}?',
  re01: 'What are the best {{category}} stores in {{market}}?',
  re02: 'Where should I buy {{category}} in {{market}}?',
  re03: 'Should I shop at {{brand}} or {{competitor}}?',
  re04: 'What alternatives to {{competitor}} are there for buying {{category}}?',
  re05: 'Where can I find {{category}} at the best price in {{market}}?',
  re06: 'What are shipping, returns and customer service like at {{brand}}?',
  re07: 'What reviews or opinions are there about shopping at {{brand}} in {{year}}?',
  re08: 'Common problems or complaints when shopping at {{brand}}.',
  re09: 'Best {{category}} stores in {{market}}.',
  re10: 'What does {{brand}} sell and to whom?',
  re11: 'Which {{category}} stores lead the market in {{market}} in {{year}}?',
  mk01: 'What are the best {{category}} marketplaces in {{market}}?',
  mk02: 'Which platform should I use to buy or sell {{category}} in {{market}}?',
  mk03: '{{brand}} or {{competitor}}: which marketplace is better?',
  mk04: 'What fees and conditions does {{brand}} have?',
  mk05: 'Is {{brand}} safe and reliable? What do its users think in {{year}}?',
  mk06: 'Common scams, problems or complaints on {{brand}}.',
  mk07: 'What alternatives to {{competitor}} are there for {{category}}?',
  mk08: 'What is {{brand}} and how does it work?',
  mk09: 'What are the leading {{category}} marketplaces in {{market}} in {{year}}?',
  pi01: 'Which institution in {{market}} is responsible for {{category}}?',
  pi02: 'How can I complete a procedure with {{brand}}? What requirements and channels are available?',
  pi03: 'What is {{brand}} and what services does it provide?',
  pi04: 'How can I contact {{brand}} and where are its offices in {{market}}?',
  pi05: 'What experiences or complaints do citizens report about {{brand}} in {{year}}?',
  pi06: 'Common problems or delays with {{brand}}.',
  gn01: 'What are the best {{category}} options in {{market}}?',
  gn02: 'I am looking for {{category}} in {{market}}. What do you recommend?',
  gn03: 'What alternatives to {{competitor}} are there for {{category}}?',
  gn04: 'What reviews or opinions are there about {{brand}} in {{year}}?',
  gn05: 'Common problems or complaints about {{brand}}.',
  gn06: 'What is {{brand}} and whom does it serve?',
  gn07: 'Who are the leaders in {{category}} in {{market}} in {{year}}?'
}

const pt: Record<string, string> = {
  p01: 'Quais agências de {{category}} ajudam empresas em {{market}}?',
  p02: 'Preciso melhorar {{painPoint}} na minha empresa. Que tipo de agência ou serviço devo procurar em {{market}}?',
  p03: 'Quais são as melhores agências de {{category}} em {{market}}?',
  p04: 'Recomende fornecedores confiáveis de {{category}} para uma grande empresa em {{market}}.',
  p05: '{{brand}} ou {{competitor}}: qual é melhor para {{category}}?',
  p06: 'Quais alternativas a {{competitor}} existem para {{category}} em {{market}}?',
  p07: '{{brand}} é uma agência confiável para {{category}}?',
  p08: 'Quais opiniões ou avaliações existem sobre {{brand}} em {{year}}?',
  p09: 'Quanto custa contratar serviços de {{category}} com uma agência em {{market}}?',
  p10: 'O que devo considerar antes de contratar {{brand}} para {{category}}?',
  p11: 'Melhor agência de {{category}} em {{market}}.',
  p12: 'Agência de {{category}} para uma grande empresa em {{market}}.',
  p13: 'Problemas, reclamações ou críticas frequentes sobre {{brand}}.',
  p14: 'O que {{brand}} faz e quem atende?',
  p15: 'Em que {{brand}} se especializa?',
  p16: 'Quem são os líderes de {{category}} em {{market}} em {{year}}?',
  cb01: 'Quais são as melhores opções de {{category}} em {{market}}?',
  cb02: 'Estou avaliando opções de {{category}} em {{market}}. Quais você recomenda?',
  cb03: 'Quais opções de {{category}} têm a melhor reputação em {{market}}?',
  cb04: '{{brand}} ou {{competitor}}: qual vale mais a pena?',
  cb05: 'Quais alternativas a {{competitor}} existem em {{category}}?',
  cb06: '{{brand}} vale a pena? Que experiências seus clientes relatam?',
  cb07: 'Quais opiniões ou avaliações existem sobre {{brand}} em {{year}}?',
  cb08: 'Quais opções de {{category}} oferecem o melhor custo-benefício em {{market}}?',
  cb09: 'O que devo considerar antes de escolher {{brand}}?',
  cb10: 'Problemas, reclamações ou queixas frequentes sobre {{brand}}.',
  cb11: 'Melhores opções de {{category}} em {{market}}.',
  cb12: 'O que é {{brand}} e o que oferece?',
  cb13: 'Em que {{brand}} se destaca?',
  cb14: 'Quais são os líderes de {{category}} em {{market}} em {{year}}?',
  sa01: 'Quais são as melhores plataformas de {{category}} para empresas em {{market}}?',
  sa02: 'Preciso de uma ferramenta de {{category}} para minha empresa. Quais opções devo avaliar?',
  sa03: '{{brand}} vs {{competitor}}: qual é melhor para {{category}}?',
  sa04: 'Quais alternativas a {{competitor}} existem para {{category}}?',
  sa05: 'Quais integrações e recursos {{brand}} oferece?',
  sa06: 'Quais opiniões ou avaliações existem sobre {{brand}} em {{year}}?',
  sa07: 'Quais limitações ou problemas os usuários de {{brand}} relatam?',
  sa08: 'Quanto custa uma solução de {{category}} para uma empresa em {{market}}?',
  sa09: 'Quais são os planos e preços de {{brand}}?',
  sa10: 'Qual plataforma de {{category}} é melhor para uma grande empresa em {{market}}?',
  sa11: 'O que {{brand}} faz e que tipos de empresas atende?',
  sa12: 'Quem são os líderes de {{category}} em {{market}} em {{year}}?',
  re01: 'Quais são as melhores lojas de {{category}} em {{market}}?',
  re02: 'Onde vale a pena comprar {{category}} em {{market}}?',
  re03: 'Vale mais a pena comprar em {{brand}} ou em {{competitor}}?',
  re04: 'Quais alternativas a {{competitor}} existem para comprar {{category}}?',
  re05: 'Onde encontro {{category}} pelo melhor preço em {{market}}?',
  re06: 'Como são as entregas, devoluções e o atendimento de {{brand}}?',
  re07: 'Quais opiniões ou avaliações existem sobre comprar em {{brand}} em {{year}}?',
  re08: 'Problemas ou reclamações frequentes ao comprar em {{brand}}.',
  re09: 'Melhores lojas de {{category}} em {{market}}.',
  re10: 'O que {{brand}} vende e para quem?',
  re11: 'Quais são as lojas líderes de {{category}} em {{market}} em {{year}}?',
  mk01: 'Quais são os melhores marketplaces de {{category}} em {{market}}?',
  mk02: 'Em qual plataforma vale a pena comprar ou vender {{category}} em {{market}}?',
  mk03: '{{brand}} ou {{competitor}}: qual marketplace vale mais a pena?',
  mk04: 'Quais são as taxas e condições de {{brand}}?',
  mk05: '{{brand}} é seguro e confiável? O que seus usuários acham em {{year}}?',
  mk06: 'Golpes, problemas ou reclamações frequentes em {{brand}}.',
  mk07: 'Quais alternativas a {{competitor}} existem para {{category}}?',
  mk08: 'O que é {{brand}} e como funciona?',
  mk09: 'Quais são os marketplaces líderes de {{category}} em {{market}} em {{year}}?',
  pi01: 'Qual órgão em {{market}} é responsável por {{category}}?',
  pi02: 'Como realizo um procedimento em {{brand}}? Quais são os requisitos e canais disponíveis?',
  pi03: 'O que é {{brand}} e quais serviços oferece?',
  pi04: 'Como entro em contato com {{brand}} e onde ficam seus escritórios em {{market}}?',
  pi05: 'Quais experiências ou reclamações os cidadãos relatam sobre {{brand}} em {{year}}?',
  pi06: 'Problemas ou atrasos frequentes com {{brand}}.',
  gn01: 'Quais são as melhores opções de {{category}} em {{market}}?',
  gn02: 'Estou procurando {{category}} em {{market}}. O que você recomenda?',
  gn03: 'Quais alternativas a {{competitor}} existem para {{category}}?',
  gn04: 'Quais opiniões ou avaliações existem sobre {{brand}} em {{year}}?',
  gn05: 'Problemas ou reclamações frequentes sobre {{brand}}.',
  gn06: 'O que é {{brand}} e quem atende?',
  gn07: 'Quem são os líderes de {{category}} em {{market}} em {{year}}?'
}

export const localizePromptPack = (
  pack: GrowthAiVisibilityPromptPack,
  market: ResolvedGrowthMarket
): GrowthAiVisibilityPromptPack => ({
  ...pack,
  version: `${pack.version}.market-v1.${market.locale}`,
  market: market.code,
  locale: market.locale,
  prompts: pack.prompts.map(prompt => {
    const text =
      market.language === 'es'
        ? prompt.id === 'p11'
          ? 'Mejor agencia de {{category}} en {{market}}.'
          : prompt.text
        : (market.language === 'en' ? en : market.language === 'fr' ? FRENCH_PROMPTS : pt)[prompt.id]

    if (!text) throw new Error('aeo_prompt_translation_missing')

    return { ...prompt, text }
  })
})
