/** French baseline for Haiti and French-speaking audiences; immutable market-v1. */
export const FRENCH_PROMPTS: Record<string, string> = {
  p01: 'Quelles agences de {{category}} accompagnent les entreprises en {{market}} ?',
  p02: 'Je souhaite améliorer {{painPoint}} pour mon entreprise. Quel type d’agence ou de service chercher en {{market}} ?',
  p03: 'Quelles sont les meilleures agences de {{category}} en {{market}} ?',
  p04: 'Recommandez des prestataires fiables de {{category}} pour une grande entreprise en {{market}}.',
  p05: '{{brand}} ou {{competitor}} : lequel choisir pour {{category}} ?',
  p06: 'Quelles alternatives à {{competitor}} existent pour {{category}} en {{market}} ?',
  p07: '{{brand}} est-elle une agence fiable pour {{category}} ?',
  p08: 'Quels avis ou évaluations existe-t-il sur {{brand}} en {{year}} ?',
  p09: 'Combien coûte le recours à une agence de {{category}} en {{market}} ?',
  p10: 'Que faut-il considérer avant de choisir {{brand}} pour {{category}} ?',
  p11: 'Meilleure agence de {{category}} en {{market}}.',
  p12: 'Agence de {{category}} pour une grande entreprise en {{market}}.',
  p13: 'Problèmes, plaintes ou critiques fréquents concernant {{brand}}.',
  p14: 'Que fait {{brand}} et à qui s’adresse cette marque ?',
  p15: 'Dans quoi {{brand}} se spécialise-t-elle ?',
  p16: 'Qui sont les leaders de {{category}} en {{market}} en {{year}} ?',
  cb01: 'Quelles sont les meilleures options de {{category}} en {{market}} ?',
  cb02: 'J’évalue les options de {{category}} en {{market}}. Lesquelles recommandez-vous ?',
  cb03: 'Quelles options de {{category}} ont la meilleure réputation en {{market}} ?',
  cb04: '{{brand}} ou {{competitor}} : lequel choisir ?',
  cb05: 'Quelles alternatives à {{competitor}} existent dans {{category}} ?',
  cb06: '{{brand}} en vaut-elle la peine ? Quelles expériences ses clients rapportent-ils ?',
  cb07: 'Quels avis ou évaluations existe-t-il sur {{brand}} en {{year}} ?',
  cb08: 'Quelles options de {{category}} offrent le meilleur rapport qualité-prix en {{market}} ?',
  cb09: 'Que faut-il considérer avant de choisir {{brand}} ?',
  cb10: 'Problèmes, plaintes ou réclamations fréquents concernant {{brand}}.',
  cb11: 'Meilleures options de {{category}} en {{market}}.',
  cb12: 'Qu’est-ce que {{brand}} et que propose cette marque ?',
  cb13: 'En quoi {{brand}} se distingue-t-elle ?',
  cb14: 'Quelles sont les principales options de {{category}} en {{market}} en {{year}} ?',
  sa01: 'Quelles sont les meilleures plateformes de {{category}} pour les entreprises en {{market}} ?',
  sa02: 'J’ai besoin d’un outil de {{category}} pour mon entreprise. Quelles options évaluer ?',
  sa03: '{{brand}} ou {{competitor}} : lequel choisir pour {{category}} ?',
  sa04: 'Quelles alternatives à {{competitor}} existent pour {{category}} ?',
  sa05: 'Quelles intégrations et fonctionnalités {{brand}} propose-t-elle ?',
  sa06: 'Quels avis ou évaluations existe-t-il sur {{brand}} en {{year}} ?',
  sa07: 'Quelles limites ou difficultés les utilisateurs de {{brand}} signalent-ils ?',
  sa08: 'Combien coûte une solution de {{category}} pour une entreprise en {{market}} ?',
  sa09: 'Quels sont les forfaits et les tarifs de {{brand}} ?',
  sa10: 'Quelle plateforme de {{category}} convient le mieux à une grande entreprise en {{market}} ?',
  sa11: 'Que fait {{brand}} et quels types d’entreprises accompagne-t-elle ?',
  sa12: 'Qui sont les leaders de {{category}} en {{market}} en {{year}} ?',
  re01: 'Quels sont les meilleurs magasins de {{category}} en {{market}} ?',
  re02: 'Où acheter {{category}} en {{market}} ?',
  re03: 'Vaut-il mieux acheter chez {{brand}} ou {{competitor}} ?',
  re04: 'Quelles alternatives à {{competitor}} existent pour acheter {{category}} ?',
  re05: 'Où trouver {{category}} au meilleur prix en {{market}} ?',
  re06: 'Comment se passent les livraisons, les retours et le service client de {{brand}} ?',
  re07: 'Quels avis ou évaluations existe-t-il sur les achats chez {{brand}} en {{year}} ?',
  re08: 'Problèmes ou réclamations fréquents lors des achats chez {{brand}}.',
  re09: 'Meilleurs magasins de {{category}} en {{market}}.',
  re10: 'Que vend {{brand}} et à qui ?',
  re11: 'Quels sont les magasins leaders de {{category}} en {{market}} en {{year}} ?',
  mk01: 'Quelles sont les meilleures places de marché de {{category}} en {{market}} ?',
  mk02: 'Quelle plateforme choisir pour acheter ou vendre {{category}} en {{market}} ?',
  mk03: '{{brand}} ou {{competitor}} : quelle place de marché choisir ?',
  mk04: 'Quels sont les frais et les conditions de {{brand}} ?',
  mk05: '{{brand}} est-elle sûre et fiable ? Que pensent ses utilisateurs en {{year}} ?',
  mk06: 'Arnaques, problèmes ou plaintes fréquents sur {{brand}}.',
  mk07: 'Quelles alternatives à {{competitor}} existent pour {{category}} ?',
  mk08: 'Qu’est-ce que {{brand}} et comment fonctionne cette plateforme ?',
  mk09: 'Quelles sont les places de marché leaders de {{category}} en {{market}} en {{year}} ?',
  pi01: 'Quel organisme en {{market}} est responsable de {{category}} ?',
  pi02: 'Comment effectuer une démarche auprès de {{brand}} ? Quelles sont les conditions et les voies de contact ?',
  pi03: 'Qu’est-ce que {{brand}} et quels services cet organisme fournit-il ?',
  pi04: 'Comment contacter {{brand}} et où sont ses bureaux en {{market}} ?',
  pi05: 'Quelles expériences ou plaintes les citoyens rapportent-ils concernant {{brand}} en {{year}} ?',
  pi06: 'Problèmes ou retards fréquents avec {{brand}}.',
  gn01: 'Quelles sont les meilleures options de {{category}} en {{market}} ?',
  gn02: 'Je cherche {{category}} en {{market}}. Que recommandez-vous ?',
  gn03: 'Quelles alternatives à {{competitor}} existent pour {{category}} ?',
  gn04: 'Quels avis ou évaluations existe-t-il sur {{brand}} en {{year}} ?',
  gn05: 'Problèmes ou plaintes fréquents concernant {{brand}}.',
  gn06: 'Qu’est-ce que {{brand}} et à qui s’adresse cette marque ?',
  gn07: 'Qui sont les leaders de {{category}} en {{market}} en {{year}} ?'
}
