import{config}from'dotenv';import{readFile,writeFile,readdir,access}from'node:fs/promises';import{writeFileSync}from'node:fs';import{createHash}from'node:crypto';import{uploadFalFile,getFalAccountBalances,getFalEndpointPricing,runFalModel,getFalRequestStatus,awaitFalRequest}from'@/lib/ai/fal';
config({path:'.env.local',quiet:true});const root='ai-generations/2026-09-23_cmp003-sky-video/seedance/';const dir=root+'v9/';const model='bytedance/seedance-2.5/reference-to-video';const account='FAL_API_KEY_B';const save=async(n:string,v:any)=>writeFile(dir+n,JSON.stringify(v,null,2));
async function main(){const mode=process.argv[2];
if(mode==='prepare'){
const balances=await getFalAccountBalances();const apiPrice=await getFalEndpointPricing(model);const estimatedUsd=1080*1920*60*24/1024/1000*.0234*.6;
await save('preflight.json',{date:new Date().toISOString(),balances,apiPrice,estimatedUsd,basis:'1080*1920*(30 input + 30 output)*24/1024 tokens * $0.0234/1000 * 0.6 video reference discount',pricingSource:'https://fal.ai/models/bytedance/seedance-2.5/reference-to-video'});console.log({balances,estimatedUsd});if((balances.find(x=>x.account===account)?.balance??0)<estimatedUsd)throw Error('Insufficient verified balance');
const files=(await readdir(dir+'refs')).filter(x=>x.endsWith('.png')).sort().map(x=>dir+'refs/'+x).concat(['V02','V10','VR','V16'].map(x=>root+'refs/A320neo_CFM_SKY_'+x+'.png'),[dir+'sky-v9-guide-silent.mp4']);const refs:any[]=[];
for(const path of files){const bytes=await readFile(path);const isVideo=path.endsWith('.mp4');const r=await uploadFalFile({bytes:new Uint8Array(bytes),fileName:path.split('/').pop()!,contentType:isVideo?'video/mp4':'image/png'});refs.push({path,sha256:createHash('sha256').update(bytes).digest('hex'),url:r.url,kind:isVideo?'video':'image'});await save('references.json',refs);console.log('Uploaded '+refs.length+'/'+files.length);}
const input={prompt:await readFile(dir+'generation.prompt.txt','utf8'),task:'reference',image_urls:refs.filter(x=>x.kind==='image').map(x=>x.url),video_urls:refs.filter(x=>x.kind==='video').map(x=>x.url),duration:'30',resolution:'1080p',aspect_ratio:'9:16',generate_audio:false,bitrate_mode:'high',codec:'H264'};await save('request.json',{model,account,input});console.log('Payload ready: 18 images, full 30s guide, 1080p, audio disabled');
}else if(mode==='submit'){
try{await access(dir+'submission-started.json');throw Error('Submission guard exists; inspect status, never duplicate')}catch(e:any){if(e.code!=='ENOENT')throw e}
const req=JSON.parse(await readFile(dir+'request.json','utf8'));await save('submission-started.json',{at:new Date().toISOString()});const result=await runFalModel({model,input:req.input,account,detach:true,onEnqueued:handle=>writeFileSync(dir+'queue-handle.json',JSON.stringify({...handle,at:new Date().toISOString()},null,2))});await save('submission.json',result);console.log({ok:result.ok,httpStatus:result.httpStatus,requestId:result.requestId});
}else if(mode==='balance'){const balances=await getFalAccountBalances();await save('balance-final.json',{checkedAt:new Date().toISOString(),balances});console.log(balances);
}else if(mode==='status'){const h=JSON.parse(await readFile(dir+'queue-handle.json','utf8'));const result=await getFalRequestStatus({model,requestId:h.requestId,account});await save('status.json',{...result,checkedAt:new Date().toISOString()});console.log(result);
}else if(mode==='result'){const h=JSON.parse(await readFile(dir+'queue-handle.json','utf8'));const result:any=await awaitFalRequest({model,requestId:h.requestId,account,pollTimeoutMs:50000});await save('result.json',result);console.log({ok:result.ok,httpStatus:result.httpStatus});if(result.ok&&result.output?.video?.url){const r=await fetch(result.output.video.url);if(!r.ok)throw Error('Download failed');await writeFile(dir+'sky-v9-fal-native.mp4',new Uint8Array(await r.arrayBuffer()));await save('balance-after.json',await getFalAccountBalances());console.log('Native render saved for visual/audio QA');}}
}main().catch(e=>{console.error('Operation failed: '+String(e.message).slice(0,160));process.exitCode=1});
