/** Localized category labels; keys belong to the canonical taxonomy. */
export const FRENCH_CATEGORY_LABELS: Record<string, string> = {
  Technology: 'Technologie',
  'Professional services': 'Services professionnels',
  'Marketing and communications': 'Marketing et communication',
  Healthcare: 'Santé',
  Finance: 'Finance',
  Education: 'Éducation',
  Retail: 'Commerce de détail',
  Manufacturing: 'Industrie manufacturière',
  Energy: 'Énergie',
  Government: 'Administration publique',
  'Real estate': 'Immobilier',
  Construction: 'Construction',
  'Logistics and transportation': 'Logistique et transport',
  'Hospitality and travel': 'Hôtellerie et tourisme',
  'Media and entertainment': 'Médias et divertissement',
  Legal: 'Services juridiques',
  'Agriculture and food': 'Agriculture et alimentation',
  'Nonprofit and impact': 'Organisations à but non lucratif et impact',
  'Airlines and aviation': 'Compagnies aériennes et aviation',
  Automotive: 'Automobile',
  Telecommunications: 'Télécommunications',
  'Consumer goods': 'Biens de consommation',
  'Food and beverage': 'Alimentation et boissons',
  'Passenger airlines': 'Compagnies aériennes de passagers',
  'Supermarkets and grocery': 'Supermarchés et épiceries',
  'Apparel and fashion': 'Habillement et mode',
  'Beauty and personal care': 'Beauté et soins personnels',
  'Restaurants and foodservice': 'Restaurants et restauration',
  Beverages: 'Boissons',
  'Retail and consumer banking': 'Services bancaires aux particuliers',
  'B2B SaaS': 'SaaS B2B',
  Martech: 'Martech',
  'Marketing services': 'Services de marketing',
  'Creative agency': 'Agence créative',
  'Revenue operations': 'Opérations de revenus',
  Fintech: 'Fintech',
  Healthtech: 'Technologies de santé',
  'AI and automation': 'IA et automatisation',
  'Data and analytics': 'Données et analyse',
  Cybersecurity: 'Cybersécurité',
  'Cloud and IT services': 'Services cloud et informatiques',
  'Developer tools': 'Outils de développement',
  'Ecommerce and marketplaces': 'Commerce électronique et places de marché',
  Edtech: 'Technologies éducatives',
  'HR tech': 'Technologies RH',
  Proptech: 'Proptech',
  Legaltech: 'Legaltech',
  Cleantech: 'Technologies propres',
  'Banking and insurance': 'Banque et assurance',
  Payments: 'Paiements',
  'Supply chain': 'Chaîne logistique',
  CRM: 'CRM',
  'Digital agency': 'Agence numérique',
  'Growth Operating System': 'Système opérationnel de croissance',
  'HubSpot consulting': 'Conseil HubSpot',
  'Web development': 'Développement web',
  'Inbound Marketing': 'Marketing entrant',
  'Marketing automation': 'Automatisation du marketing',
  'Customer service automation': 'Automatisation du service client',
  'AEO / AI Visibility': 'AEO / Visibilité dans les IA',
  'AI agents': 'Agents IA',
  'Chatbots and virtual assistants': 'Chatbots et assistants virtuels',
  'Business intelligence': 'Informatique décisionnelle',
  'Data platform': 'Plateforme de données',
  ERP: 'ERP',
  'Cybersecurity services': 'Services de cybersécurité',
  'Cloud migration': 'Migration cloud',
  'DevOps platform': 'Plateforme DevOps',
  'Ecommerce platform': 'Plateforme de commerce électronique',
  Marketplace: 'Place de marché',
  'Payment gateway': 'Passerelle de paiement',
  'Accounting software': 'Logiciel comptable',
  'Insurance brokerage': 'Courtage en assurance',
  Telemedicine: 'Télémédecine',
  'Patient experience': 'Expérience patient',
  'LMS / learning platform': 'LMS / Plateforme pédagogique',
  'HRIS / people management': 'SIRH / Gestion du personnel',
  'Recruiting platform': 'Plateforme de recrutement',
  'Contract management': 'Gestion des contrats',
  'Property management': 'Gestion immobilière',
  'Construction management': 'Gestion de construction',
  'Supply chain software': 'Logiciel de chaîne logistique',
  'Booking and reservations': 'Réservations',
  'Content management': 'Gestion de contenu',
  'Public relations': 'Relations publiques',
  'Sustainability reporting': 'Rapports de durabilité',
  'Lead generation': 'Génération de prospects',
  'AEO readiness': 'Préparation AEO',
  'CRM implementation': 'Mise en place de CRM',
  'Demand generation': 'Génération de demande',
  'Customer acquisition': 'Acquisition de clients',
  'Customer retention': 'Fidélisation des clients',
  'Customer support': 'Assistance client',
  'Sales enablement': 'Accompagnement commercial',
  'Onboarding and activation': 'Intégration et activation',
  'Analytics and reporting': 'Analyse et rapports',
  'Compliance and risk management': 'Conformité et gestion des risques',
  'Talent acquisition': 'Acquisition de talents',
  'Procurement and sourcing': 'Achats et approvisionnement',
  'Field operations': 'Opérations de terrain',
  'Appointment scheduling': 'Prise de rendez-vous',
  'Content operations': 'Opérations de contenu',
  'Brand awareness': 'Notoriété de marque',
  'Ecommerce conversion': 'Conversion du commerce électronique',
  'CMO / marketing leader': 'Direction marketing',
  'RevOps leader': 'Direction RevOps',
  Founder: 'Fondateur',
  'Operations leader': 'Direction des opérations',
  'CIO / IT leader': 'Direction des systèmes d’information',
  'CTO / engineering leader': 'Direction technique',
  'CFO / finance leader': 'Direction financière',
  'CHRO / people leader': 'Direction des ressources humaines',
  'Sales leader': 'Direction commerciale',
  'Customer Success leader': 'Direction de la réussite client',
  'Security leader': 'Direction de la sécurité',
  'Legal counsel': 'Conseil juridique',
  'Clinic manager': 'Gestion de clinique',
  'Ecommerce manager': 'Gestion du commerce électronique',
  'Property manager': 'Gestion immobilière',
  Chile: 'Chili',
  LatAm: 'Amérique latine',
  Global: 'Mondial',
  Enterprise: 'Grande entreprise',
  'Mid-market': 'Entreprise de taille intermédiaire',
  'Small business': 'Petite entreprise',
  Startup: 'Startup',
  'Public sector': 'Secteur public',
  'United States': 'États-Unis',
  Mexico: 'Mexique',
  Colombia: 'Colombie',
  Peru: 'Pérou',
  Brazil: 'Brésil',
  Spain: 'Espagne'
}
