import type { GrowthLanguage } from '@/lib/growth/markets'

import { FRENCH_CATEGORY_LABELS } from './labels-fr'
import { getCategoryTaxonomyNode } from './index'

/** Portuguese labels supplement the immutable taxonomy's es/en labels. */
const PT: Record<string, string> = {
  Technology: 'Tecnologia',
  'Professional services': 'Serviços profissionais',
  'Marketing and communications': 'Marketing e comunicação',
  Healthcare: 'Saúde',
  Finance: 'Finanças',
  Education: 'Educação',
  Retail: 'Varejo',
  Manufacturing: 'Indústria',
  Energy: 'Energia',
  Government: 'Governo',
  'Real estate': 'Setor imobiliário',
  Construction: 'Construção',
  'Logistics and transportation': 'Logística e transporte',
  'Hospitality and travel': 'Hotelaria e turismo',
  'Media and entertainment': 'Mídia e entretenimento',
  Legal: 'Serviços jurídicos',
  'Agriculture and food': 'Agricultura e alimentos',
  'Nonprofit and impact': 'Organizações sem fins lucrativos e impacto',
  'Airlines and aviation': 'Companhias aéreas e aviação',
  Automotive: 'Setor automotivo',
  Telecommunications: 'Telecomunicações',
  'Consumer goods': 'Bens de consumo',
  'Food and beverage': 'Alimentos e bebidas',
  'Paints and coatings': 'Tintas e revestimentos',
  'Passenger airlines': 'Companhias aéreas de passageiros',
  'Supermarkets and grocery': 'Supermercados e mercearias',
  'Apparel and fashion': 'Vestuário e moda',
  'Beauty and personal care': 'Beleza e cuidados pessoais',
  'Restaurants and foodservice': 'Restaurantes e alimentação',
  Beverages: 'Bebidas',
  'Retail and consumer banking': 'Serviços bancários para pessoas físicas',
  'B2B SaaS': 'SaaS B2B',
  Martech: 'Martech',
  'Marketing services': 'Serviços de marketing',
  'Creative agency': 'Agência criativa',
  'Revenue operations': 'Operações de receita',
  Fintech: 'Fintech',
  Healthtech: 'Healthtech',
  'AI and automation': 'IA e automação',
  'Data and analytics': 'Dados e análise',
  Cybersecurity: 'Cibersegurança',
  'Cloud and IT services': 'Serviços de nuvem e TI',
  'Developer tools': 'Ferramentas para desenvolvedores',
  'Ecommerce and marketplaces': 'Comércio eletrônico e marketplaces',
  Edtech: 'Edtech',
  'HR tech': 'Tecnologia de RH',
  Proptech: 'Proptech',
  Legaltech: 'Legaltech',
  Cleantech: 'Cleantech',
  'Banking and insurance': 'Bancos e seguros',
  Payments: 'Pagamentos',
  'Supply chain': 'Cadeia de suprimentos',
  CRM: 'CRM',
  'Digital agency': 'Agência digital',
  'Growth Operating System': 'Sistema operacional de crescimento',
  'HubSpot consulting': 'Consultoria HubSpot',
  'Web development': 'Desenvolvimento web',
  'Inbound Marketing': 'Inbound Marketing',
  'Marketing automation': 'Automação de marketing',
  'Customer service automation': 'Automação do atendimento ao cliente',
  'AEO / AI Visibility': 'AEO / Visibilidade em IA',
  'AI agents': 'Agentes de IA',
  'Chatbots and virtual assistants': 'Chatbots e assistentes virtuais',
  'Business intelligence': 'Inteligência de negócios',
  'Data platform': 'Plataforma de dados',
  ERP: 'ERP',
  'Cybersecurity services': 'Serviços de cibersegurança',
  'Cloud migration': 'Migração para a nuvem',
  'DevOps platform': 'Plataforma DevOps',
  'Ecommerce platform': 'Plataforma de comércio eletrônico',
  Marketplace: 'Marketplace',
  'Payment gateway': 'Gateway de pagamento',
  'Accounting software': 'Software contábil',
  'Insurance brokerage': 'Corretagem de seguros',
  Telemedicine: 'Telemedicina',
  'Patient experience': 'Experiência do paciente',
  'LMS / learning platform': 'LMS / Plataforma de aprendizagem',
  'HRIS / people management': 'HRIS / Gestão de pessoas',
  'Recruiting platform': 'Plataforma de recrutamento',
  'Contract management': 'Gestão de contratos',
  'Property management': 'Gestão imobiliária',
  'Construction management': 'Gestão de obras',
  'Supply chain software': 'Software de cadeia de suprimentos',
  'Booking and reservations': 'Reservas',
  'Content management': 'Gestão de conteúdo',
  'Public relations': 'Relações públicas',
  'Sustainability reporting': 'Relatórios de sustentabilidade',
  'Lead generation': 'Geração de leads',
  'AEO readiness': 'Preparação para AEO',
  'CRM implementation': 'Implementação de CRM',
  'Demand generation': 'Geração de demanda',
  'Customer acquisition': 'Aquisição de clientes',
  'Customer retention': 'Retenção de clientes',
  'Customer support': 'Atendimento e suporte ao cliente',
  'Sales enablement': 'Capacitação de vendas',
  'Onboarding and activation': 'Integração e ativação',
  'Analytics and reporting': 'Análise e relatórios',
  'Compliance and risk management': 'Conformidade e gestão de riscos',
  'Talent acquisition': 'Aquisição de talentos',
  'Procurement and sourcing': 'Compras e abastecimento',
  'Field operations': 'Operações de campo',
  'Appointment scheduling': 'Agendamento',
  'Content operations': 'Operações de conteúdo',
  'Brand awareness': 'Reconhecimento de marca',
  'Ecommerce conversion': 'Conversão no comércio eletrônico',
  'CMO / marketing leader': 'CMO / Liderança de marketing',
  'RevOps leader': 'Liderança de RevOps',
  Founder: 'Fundador',
  'Operations leader': 'Liderança de operações',
  'CIO / IT leader': 'CIO / Liderança de TI',
  'CTO / engineering leader': 'CTO / Liderança de engenharia',
  'CFO / finance leader': 'CFO / Liderança financeira',
  'CHRO / people leader': 'CHRO / Liderança de pessoas',
  'Sales leader': 'Liderança de vendas',
  'Customer Success leader': 'Liderança de sucesso do cliente',
  'Security leader': 'Liderança de segurança',
  'Legal counsel': 'Assessoria jurídica',
  'Clinic manager': 'Gestão de clínica',
  'Ecommerce manager': 'Gestão de comércio eletrônico',
  'Property manager': 'Gestão imobiliária',
  Chile: 'Chile',
  LatAm: 'América Latina',
  Global: 'Global',
  Enterprise: 'Grande empresa',
  'Mid-market': 'Média empresa',
  'Small business': 'Pequena empresa',
  Startup: 'Startup',
  'Public sector': 'Setor público',
  'United States': 'Estados Unidos',
  Mexico: 'México',
  Colombia: 'Colômbia',
  Peru: 'Peru',
  Brazil: 'Brasil',
  Spain: 'Espanha'
}

export const localizedCategoryLabel = (nodeId: string, language: GrowthLanguage): string | null => {
  const node = getCategoryTaxonomyNode(nodeId)

  if (!node) return null

  if (language === 'fr') {
    if (!FRENCH_CATEGORY_LABELS[node.label.en]) throw new Error('aeo_category_translation_missing')

    return FRENCH_CATEGORY_LABELS[node.label.en]
  }

  if (language === 'pt-BR' && !PT[node.label.en]) throw new Error('aeo_category_translation_missing')

  return language === 'pt-BR' ? PT[node.label.en] : node.label[language]
}
