// ================= B3 · Espacio con la lente (reemplaza la versión de puntos) =================
// Vidrio esmerilado: la sala se ve borrosa y aclarada; un solo círculo transparente a la altura de los ojos.
const frosted=({src,x,y,w,h,cx,cy,D,pos='50% 45%',alt})=>abs(x,y,w,h,{overflow:'hidden'},
 `<img src="${src}" alt="${alt}" style="position: absolute; left: 0; top: 0; width: ${w}px; height: ${h}px; object-fit: cover; object-position: ${pos}; filter: blur(22px) brightness(1.35) saturate(0.35)">`+abs(0,0,w,h,{background:'rgba(236,240,243,0.72)'})+
 abs(0,0,w,h,{clipPath:`circle(${D/2}px at ${cx-x}px ${cy-y}px)`},`<img src="${src}" alt="" style="position: absolute; left: 0; top: 0; width: ${w}px; height: ${h}px; object-fit: cover; object-position: ${pos}">`)+
 abs(cx-x-D/2,cy-y-D/2,D,D,{borderRadius:'50%',boxShadow:'inset 0 0 0 3px rgba(255,255,255,0.55)'}));
S.o_recep=()=>{const W=1920,H=1080;return {W,H,bg:C.navy,html:lens({src:IMG.studio,W,H:970,cx:1150,cy:400,D:760,zoom:1.12,alt:'Mural de recepción: estudio en navy con el equipo a color dentro del círculo'})+abs(120,700,null,null,{},dom('Hacer',190,C.white))+abs(0,970,W,110,{background:'#1A2530'})};};
S.o_sala=()=>{const W=1920,H=1080,x=140,y=90,w=1640,h=880;return {W,H,bg:'#E4E6E3',html:frosted({src:IMG.conv,x,y,w,h,cx:1180,cy:470,D:620,alt:'Sala de reuniones tras vidrio esmerilado; se ve nítida sólo a través del círculo'})+
 abs(x,y,w,h,{border:'14px solid #9AA4AC',boxSizing:'border-box'})+abs(x+120,y+110,null,null,{},div(W8(170,C.navy,300),'Sala 02'))+
 abs(x+128,y+330,520,null,{display:'flex',alignItems:'center',gap:18},div({width:30,height:30,borderRadius:'50%',background:C.tealDark})+p('En sesión hasta las 16:00',34,C.navy,500))+abs(0,970,W,110,{background:'#C9CDC9'})};};
S.o_pasillo=()=>{const W=1920,H=1080;return {W,H,bg:C.navy,html:lens({src:IMG.edit,W,H:970,cx:980,cy:470,D:560,zoom:1.25,pos:'50% 42%',alt:'Muro de pasillo: estación de edición en navy con el frasco a color dentro del círculo'})+abs(120,120,700,null,{},q('¿Cuál sale al aire?',40,C.soft))+abs(120,190,null,null,{},dom('Esta',170,C.white))+abs(1380,860,420,null,{},p('v07 · aprobada por dirección de arte',22,C.soft,500))+abs(0,970,W,110,{background:'#1A2530'})};};
boards['R2-07-espacio.dc.html']=board('B3 · Espacio',
 head('B3 · Espacio','La oficina se mira a través de la lente.','La lente pasa de la gráfica a la arquitectura. Los muros son fotos del trabajo real en navy apagado con un solo círculo a color; el vidrio de las salas es esmerilado y sólo deja ver hacia adentro a través de un círculo. Nada de patrones de puntos: una lente por muro.')+
 place(64,300,'Recepción · mural con lente',S.o_recep,.37)+place(820,300,'Sala de reuniones · vidrio esmerilado con un círculo transparente',S.o_sala,.37)+place(64,760,'Pasillo · muro de trabajo',S.o_pasillo,.37)+
 col(820,760,716,380,'Reglas de espacio',list(['Una lente por muro o por vidrio, a la altura de los ojos (centro a 1,5 m). Diámetro entre 1,2 y 2,4 m según el muro.','Murales: foto real del trabajo, en navy apagado; dentro de la lente, a color. Se renuevan con cada ciclo de proyectos.','Vidrio de salas: vinilo esmerilado completo con el círculo transparente; cumple además la función de visibilidad del vidrio.','Estado de la sala en texto, con la esfera teal oscuro: «En sesión hasta las 16:00».','Una palabra o pregunta del banco de voz por espacio, nunca más.'],13.5)),1600,1180);
