// ================= La órbita · objetos, movimiento, especificaciones, fotografía, decisiones y manual =================
const OB={mugBlanca:'/_blob/7e77938b0047f683c8583b4512812f48',mugNavy:'/_blob/15a172d35a0ac70a0995c7466dda936e',mugNavy34:'/_blob/b11e28c09653583f320d4f7da67e1096',mugGlobe:'/_blob/3c494f03246cc554e274fc493bc8baa3',vid169:'/_blob/7043b207bc1ab1073e642e7ddc1e7605',vid11:'/_blob/5148e31a14a14537112a4863b05d0a0c',fin169:'/_blob/5b5e18458a084e70697abd625c02860a',fin11:'/_blob/bd7bf39c29ecf029c1108ca5f45c2e43'};
const photo=(x,y,w,h,src,alt,bg='#EDEFEE')=>abs(x,y,w,h,{background:bg,outline:`1px solid ${C.line}`},`<img src="${src}" alt="${alt}" style="position: absolute; left: 0; top: 0; width: ${w}px; height: ${h}px; object-fit: contain">`);
const video=(x,y,w,h,src,poster,label)=>abs(x,y,w,h,{background:OR.navy,outline:`1px solid ${C.line}`,overflow:'hidden'},`<video src="${src}" poster="${poster}" autoplay loop muted playsinline aria-label="${label}" style="position: absolute; left: 0; top: 0; width: ${w}px; height: ${h}px; object-fit: cover"></video>`);
boards['O-06-orbita-objetos-motion.dc.html']=board('O-06 · Órbita: objetos y movimiento',
 head('O-06 · Objetos y movimiento','La taza blanca se queda con su punto; la navy lleva la órbita.','Probamos la órbita sobre el mismo modelo de taza (render 3D real). La versión blanca con «Hacer.» ya era la más elegante y la órbita no le suma: queda igual. En navy y en las ediciones de producto, la órbita con el logo sí convierte la taza en objeto de marca. Abajo, el cierre de marca producido en video.')+
 lab(64,300,'Actual · blanca con punto final')+photo(64,300,340,340,FAM[0].mug[0],'Taza blanca con «Hacer.» y punto teal')+lab(424,300,'Blanca con órbita')+photo(424,300,340,340,OB.mugBlanca,'Taza blanca con «Hacer.» dentro de una órbita fina')+
 lab(784,300,'Navy · órbita con el logo')+photo(784,300,340,340,OB.mugNavy,'Taza navy con órbita teal alrededor del logo Efeonce e interior teal')+lab(1144,300,'Navy · tres cuartos')+photo(1144,300,340,340,OB.mugNavy34,'La misma taza navy en tres cuartos: la órbita se curva con el cilindro')+
 lab(64,700,'Globe · la órbita en su acento')+photo(64,700,340,340,OB.mugGlobe,'Taza Globe en tinta con órbita naranja alrededor del logo e interior naranja')+
 col(424,700,1112,340,'Decisión propuesta',list(['Blanca: se queda con «Hacer.» y su punto (sin órbita). Es la pieza de todos los días.','Navy y productos: órbita con logo. Es la edición de marca y de regalo.','En cerámica no hay halo: sólo anillo 0,5 mm, arco 1,2 mm y esfera Ø 4,4 mm. La órbita mide 74 mm y va centrada en la cara frontal.','El interior toma el acento de la marca.'],13.5))+
 lab(64,1100,'Cierre de marca 16:9 · 4,5 s')+video(64,1100,800,450,OB.vid169,OB.fin169,'Animación: aparece el anillo, crece el arco, la esfera llega, sube el halo y aparecen el logo y el eslogan')+
 lab(900,1100,'Cierre 1:1 · redes')+video(900,1100,450,450,OB.vid11,OB.fin11,'La misma animación en formato cuadrado')+
 col(1380,1100,156,450,'Guion',list(['0–0,5 s anillo','0,4–1,4 s arco','1,4–1,7 s la esfera asienta','1,2–2,0 s halo','1,9–2,5 s logo','2,5–3,0 s eslogan'],12)),1600,1620);
// Especificaciones
const gridTile=({W,H,m,orb,text,unsafe=[],label})=>()=>{let h='';unsafe.forEach(([y0,y1])=>{h+=abs(0,y0,W,y1-y0,{background:'repeating-linear-gradient(45deg, rgba(248,57,2,0.16) 0 10px, transparent 10px 20px)'});});
 h+=abs(m,m,W-2*m,H-2*m,{border:'3px dashed rgba(114,222,216,0.55)',boxSizing:'border-box'});h+=orbit({W,H,cx:orb[0],cy:orb[1],r:orb[2],a0:200,a1:250,k:SOC(W)});
 h+=abs(text[0],text[1],text[2],text[3],{background:'rgba(244,246,248,0.10)',border:'2px solid rgba(244,246,248,0.35)',boxSizing:'border-box'},abs(16,12,null,null,{},p('Texto',Math.round(W/40),OR.ink,500)));
 return {W,H,bg:OR.navy,html:h};};
const T=(rows)=>`<table style="border-collapse: collapse; width: 100%; font-family: 'Poppins', sans-serif; font-size: 12.5px; color: ${C.ink}">${rows.map((r,i)=>`<tr>${r.map(c=>`<${i?'td':'th'} style="text-align: left; padding: 7px 10px 7px 0; border-bottom: 1px solid ${C.line}; vertical-align: top; font-weight: ${i?400:600}">${c}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table>`;
boards['O-07-orbita-especificaciones.dc.html']=board('O-07 · Órbita: especificaciones',
 head('O-07 · Grillas y especificaciones','Dónde va la órbita y cómo se produce.','Grillas por formato con margen, zona de texto, posición de la órbita y zonas que tapa la interfaz de cada red. Abajo, medidas de producción por soporte.')+
 place(64,300,'4:5 · 1080 × 1350',gridTile({W:1080,H:1350,m:96,orb:[640,500,324],text:[96,900,888,354]}),.26)+
 place(370,300,'9:16 · rayado = interfaz',gridTile({W:1080,H:1920,m:96,orb:[540,760,324],text:[96,1300,888,280],unsafe:[[0,250],[1580,1920]]}),.183)+
 place(600,300,'16:9 · 1920 × 1080',gridTile({W:1920,H:1080,m:140,orb:[1340,470,432],text:[140,600,700,340]}),.31)+
 place(1220,300,'A4 · informe (Insights)',gridTile({W:794,H:1123,m:68,orb:[520,376,236],text:[68,720,658,335]}),.28)+
 col(64,700,1472,120,'Proporciones',list(['Margen: 9 % del lado corto en redes (96 px sobre 1080); 140 px en 16:9. Órbita: radio 30 % del ancho en vertical, 40 % del alto en horizontal; centro fuera del eje, hacia la derecha y arriba. El texto vive en el tercio inferior izquierdo y nunca cruza la órbita.'],13))+
 col(64,860,1472,560,'Producción por soporte',T([['Soporte','Anillo','Arco','Esfera','Halo','Notas'],
  ['Pantalla (base 794 px de ancho)','1 px · 16–22 %','1,6–2 px','r 3,5–4 px','13 → 3 → 0 %','Escala con el ancho del lienzo.'],
  ['Redes (≤ 1200 px de ancho)','× 1,75 (2,4 px sobre 1080)','× 1,75','× 1,75 (r 8 px)','igual','Verificado a 390 px de ancho: se lee sin perder finura.'],
  ['Papel (informe, cuaderno)','mín. 0,3 mm','mín. 0,5 mm','mín. Ø 1,5 mm','se omite o fondo liso','Degradados bajo 5 % hacen bandas en offset.'],
  ['Cerámica (taza)','0,5 mm','1,2 mm','Ø 4,4 mm','sin halo','Órbita Ø 74 mm, centrada en la cara frontal.'],
  ['Vinilo (muro, vidrio) · órbita Ø 1,2 m','3 mm','5 mm','Ø 18 mm','sin halo','Escala lineal con el diámetro; centro a 1,5 m del piso.'],
  ['Pizarra','impreso 2 mm, 30 %','impreso 4 mm','imán Ø 45 mm','sin halo','El imán es la esfera y se mueve.'],
  ['Video','igual que pantalla','crece en 1 s, ease-out','asienta con rebote de 0,3 s','sube en 0,8 s','Cierre de 4,5 s; con movimiento reducido, cuadro final fijo.']])+
  abs(0,300,1472,null,{},p('Color: los valores son sRGB. Para papel, cerámica y vinilo, la conversión a CMYK o Pantone se define con prueba física del proveedor; no se fija un código sin prueba.',12.5,C.muted))),1600,1260);
// Fotografía para la lente
boards['O-08-orbita-fotografia.dc.html']=board('O-08 · Órbita: fotografía para la lente',
 head('O-08 · Fotografía para la lente','Fotos pensadas para ser vistas a través de un círculo.','Hoy repetimos tres fotos y en todas se ve el emblema bordado, lo que invalida la prueba sin logo. Este es el brief del banco propio: se genera con el pipeline canónico (pnpm foto:prompt → foto:validar), registro documental, nadie mira al lente.')+
 col(64,300,700,560,'Reglas de la toma',list(['El sujeto importante cabe en un círculo del 55 % del lado corto, con 15 % de aire al borde del círculo.','Fuera del círculo la foto tolera quedar en navy apagado: nada esencial vive ahí.','Sin emblema legible: de espaldas, en sombra, fuera de cuadro o sin bordado. El logo lo pone la pieza, no la ropa.','Un acento cálido dentro del círculo (luz de pantalla, material, piel), nunca en el fondo.','Oficio a la vista: manos, pantalla, pieza, pizarra; la obra en proceso.','Registro documental: nadie mira al lente.'],13.5))+
 col(840,300,696,560,'Lista de tomas (8)',T([['#','Toma','Palanca','Círculo sobre'],['1','Manos ajustando una curva de color en una pieza','manos','las manos y la pantalla'],['2','Dos personas decidiendo entre dos versiones','variantes','la pantalla con las dos versiones'],['3','Estratega marcando la pizarra con la órbita','instrumento','la mano y el imán'],['4','Cámara detrás del monitor de edición','reflejo','el reflejo de la pieza'],['5','Revisión de un informe impreso en la mesa','cenital','la página con el dato'],['6','Llamada con cliente, sólo la escucha','escucha','el gesto de quien escucha'],['7','Pieza aprobada saliendo en pantalla grande','proyeccion','la pieza'],['8','Mesa vacía al final del ciclo, con la pieza impresa','ausencia','la pieza impresa']]))+
 col(64,900,1472,300,'Producción',list(['Una ficha JSON por toma, armada con pnpm foto:prompt (nunca a mano); registro A documental.','Validar cada plate con pnpm foto:validar y mirar al 100 %: identidad, sin emblema legible, sin texto de terceros.','Costo estimado: 8 tomas × 2 pasadas en calidad alta, del orden de USD 5–10; se confirma con el catálogo de modelos antes de generar.','Estado: brief listo; no se generó ninguna imagen. Espera tu aprobación de presupuesto.'],13.5)),1600,1120);
// Decisiones y prueba
const stim=(orbital)=>()=>{const W=1080,H=1350,cx=640,cy=500,r=324,k=SOC(W);return {W,H,bg:orbital?OR.navy:'#1C2430',html:(orbital?orbit({W,H,cx,cy,r,a0:200,a1:250,k}):'')+
 abs(96,900,900,null,{},orbital?q('¿Qué cambió este mes?',38,OR.ink,{ringColor:OR.teal}):p('¿Qué cambió este mes?',38,OR.ink,300))+abs(96,970,900,null,{},orbital?dom('Lo que medimos',110,C.white,{sphereColor:OR.teal}):div(W8(110,C.white,760),'Lo que medimos'))};};
boards['O-09-orbita-decisiones.dc.html']=board('O-09 · Órbita: decisiones y prueba',
 head('O-09 · Decisiones tomadas y prueba sin logo','Lo que quedó decidido y cómo se va a medir.','Decisiones aplicadas en este canvas (reversibles) y la prueba de atribución actualizada con piezas de la órbita.')+
 col(64,300,720,600,'Decisiones aplicadas',list(['Forma: la órbita es la forma canónica; el punto final se mantiene en titulares, firma de mail y taza blanca; el foco, en fotos.','Color: en oscuro manda la paleta de la órbita (#001A33, #36C8BF, #72DED8, tokens del deck AXIS); en papel, navy #023C70 y teal #0E8C82.','Hilo de familia: la órbita misma es el hilo (misma forma en las cuatro marcas) + la variante del eslogan (opción C). Queda descartada la B (anillo teal en productos).','Redes: grosor ×1,75 en lienzos de hasta 1200 px.','Archivo: punto gigante, esfera tipográfica y aplicaciones planas (sección B).'],13.5))+
 place(840,300,'Estímulo de prueba · con la órbita',stim(true),.3)+place(1196,300,'Distractor · mismo copy, sin órbita ni esfera',stim(false),.3)+
 col(840,760,696,440,'Protocolo (sin cambios)',list(['Diseño entre sujetos, 150 personas por versión (ICP de Efeonce, Chile).','8 piezas por versión: post, story, deck, muro, taza navy, cuaderno, LinkedIn y firma de mail.','Preguntas: «¿de qué empresa crees que es?» (abierta), elección entre Efeonce y 5 competidores, y recuerdo de la pieza.','Éxito: +10 puntos de atribución asistida sobre el distractor, con 95 % de confianza.','Pendiente: proveedor de panel y presupuesto (decisión tuya).'],13.5))+
 col(64,960,720,260,'Sigue siendo tuyo',list(['Aprobar el banco de pares de copy (C2).','Presupuesto del banco de fotos (O-08) y del panel de la prueba.','Instalar la firma de mail (alojar imágenes, fotos reales, correos de área).'],13.5)),1600,1260);
// Manual resumen
const msec=(x,y,w,n,t,body)=>abs(x,y,w,null,{display:'flex',flexDirection:'column',gap:8},cap(`${n} · ${t}`,C.teal,12)+body);
boards['00b-manual.dc.html']=board('00b · Manual de la línea',
 head('00b · Manual de la línea gráfica (resumen)','Una esfera, su órbita y dos voces.','La línea en una lámina. Cada punto enlaza con su lámina de detalle.')+
 msec(64,300,450,'1','Idea',list(['La esfera del isotipo es el activo. Recorre su órbita: el avance es visible, el oficio está a la vista y la conversación cierra con una respuesta.'],13))+
 msec(574,300,450,'2','La esfera, tres estados',list(['Órbita: portadas, cierres, carga y avance (O-01).','Punto final: titulares, firma de mail y taza blanca (A2).','Foco: el halo sobre lo importante en fotos (A3·2+).'],13))+
 msec(1084,300,452,'3','Color',list(['Oscuro: #001A33, acento #36C8BF, halo #72DED8.','Papel: navy #023C70, teal #0E8C82.','Productos: tinta #091951 con su acento (Globe #FF6500, Wave #0375DB, Reach #F83902).'],13))+
 msec(64,560,450,'4','Tipografía',list(['Bricolage Grotesque para la respuesta; Poppins para la pregunta y el texto. Eslogan con los pesos del SSOT de marca.'],13))+
 msec(574,560,450,'5','Voz',list(['Pregunta real del cliente con anillo; respuesta de una a tres palabras que cierra con la esfera; evidencia debajo (A5).'],13))+
 msec(1084,560,452,'6','Oficio a la vista',list(['Selección y cursores de AXIS; guías y marcas de corte; máximo dos herramientas por pieza (A4).'],13))+
 msec(64,800,450,'7','Familia',list(['Misma órbita y misma voz; cambia el acento. En el portafolio, los productos son satélites de Efeonce (O-03).'],13))+
 msec(574,800,450,'8','Fotografía',list(['La lente: foto en navy apagado y el círculo a color, rodeado por la órbita. Sin emblema legible (O-08).'],13))+
 msec(1084,800,452,'9','Aplicaciones',list(['Deck con órbita de navegación (O-04), oficina (O-05), objetos y video de cierre (O-06), firma de mail (F-06).'],13))+
 msec(64,1040,1472,'10','No hacer',list(['Discos planos rellenos, brillos, reflejos o esferas de vidrio.','Dos órbitas o dos acentos en una pieza.','Arco de avance sin dato real.','Emblemas o logos de terceros como si fueran alianzas: los satélites de canales muestran dónde medimos, no con quién nos asociamos.','Texto cruzando la órbita.'],13)),1600,1320);
