// Eslogan: «Empower your ___». SSOT src/config/efeonce-brand.ts: Empower ExtraBold Italic · your ExtraBold · palabra final Black Italic.
const LOCK={light:'/_blob/54b5f7ee4cf5337b1e41e22b4208f06f',dark:'/_blob/da25b54e72e02c9afd40e5351c217bc8',r:371/1200,rd:365/1200};
const WORD={efeonce:'Growth',globe:'Brand',wave:'Engine',reach:'Voice'};
const slogan=(word,size,{dark=false,accent,align='left'}={})=>{const base=dark?'#E2E2E2':'#848484',fin=accent??(dark?C.white:C.navy);
 return div({fontFamily:PO,fontSize:size,lineHeight:1.15,whiteSpace:'nowrap',color:base,textAlign:align},`<span style="font-weight: 800; font-style: italic">Empower</span> <span style="font-weight: 800">your</span> <span style="font-weight: 900; font-style: italic; color: ${fin}">${word}</span>`);};
S.endEfeonce=()=>{const W=1920,H=1080,w=900;return {W,H,bg:C.navy,html:`<img src="${LOCK.dark}" alt="Logo Efeonce con eslogan Empower your Growth" style="position: absolute; left: ${(W-w)/2}px; top: ${(H-w*LOCK.rd)/2}px; width: ${w}px; height: ${+(w*LOCK.rd).toFixed(1)}px">`};};
S.endProduct=b=>()=>{const W=1920,H=1080,w=640,lh=w*LK[b.k].r,top=(H-lh-120)/2;return {W,H,bg:b.dark,html:lkImg(b,true,(W-w)/2,top,w)+abs(0,top+lh+44,W,null,{},slogan(WORD[b.k],60,{dark:true,accent:b.onDark,align:'center'}))};};
S.emailSig=()=>{const W=1200,H=380;return {W,H,bg:C.white,html:abs(56,70,560,null,{},p('[Nombre Apellido]',34,C.navy,600)+p('[Cargo] · Efeonce',24,C.ink,400,{marginTop:4})+p('[correo] · [teléfono]',22,C.muted,400,{marginTop:18})+p('efeoncepro.com',22,C.muted,400))+abs(640,60,2,260,{background:C.line})+`<img src="${LOCK.light}" alt="Logo Efeonce con eslogan" style="position: absolute; left: 700px; top: ${(H-440*LOCK.r)/2}px; width: 440px; height: ${+(440*LOCK.r).toFixed(1)}px">`};};
boards['R3-05-eslogan.dc.html']=board('Ronda 3 · eslogan',
 head('Ronda 3 · eslogan','El acento cierra, también en el eslogan.','«Empower your Growth» tiene dos formas oficiales: el bloque con el logo, centrado debajo, y el eslogan solo, con la palabra final destacada. La palabra final rota por capability, y en la línea toma el mismo papel que la esfera: el acento va al cierre.')+
 lab(64,270,'Oficial · bloque logo + eslogan')+abs(64,270,520,190,{background:C.paper,border:`1px solid ${C.line}`},`<img src="${LOCK.light}" alt="Logo Efeonce con eslogan" style="position: absolute; left: 40px; top: ${(190-440*LOCK.r)/2}px; width: 440px; height: ${+(440*LOCK.r).toFixed(1)}px">`)+
 abs(604,270,520,190,{background:C.navy},`<img src="${LOCK.dark}" alt="Logo Efeonce con eslogan en negativo" style="position: absolute; left: 40px; top: ${(190-440*LOCK.rd)/2}px; width: 440px; height: ${+(440*LOCK.rd).toFixed(1)}px">`)+
 lab(1144,270,'Oficial · eslogan solo')+abs(1144,270,392,90,{background:C.paper,border:`1px solid ${C.line}`,display:'flex',alignItems:'center',paddingLeft:22,boxSizing:'border-box'},slogan('Growth',30))+abs(1144,370,392,90,{background:C.navy,display:'flex',alignItems:'center',paddingLeft:22,boxSizing:'border-box'},slogan('Growth',30,{dark:true}))+
 lab(64,530,'Familia · la palabra final rota y toma el acento de la marca (propuesta para productos)')+abs(64,530,1472,150,{display:'grid',gridTemplateColumns:'repeat(4, minmax(0, 1fr))',gap:16},FAM.map(b=>div({display:'flex',flexDirection:'column',gap:8},div({height:66,background:C.paper,border:`1px solid ${C.line}`,display:'flex',alignItems:'center',paddingLeft:18},slogan(WORD[b.k],24,{accent:b.k==='efeonce'?undefined:b.onLight}))+div({height:66,background:b.dark,display:'flex',alignItems:'center',paddingLeft:18},slogan(WORD[b.k],24,{dark:true,accent:b.k==='efeonce'?undefined:b.onDark})))).join(''))+
 place(64,750,'Cierre de video · Efeonce',S.endEfeonce,.2)+place(468,750,'Cierre de video · Globe',S.endProduct(FAM[1]),.2)+place(872,750,'Firma de correo',S.emailSig,.3)+
 col(1250,750,286,380,'Reglas',list(['El bloque se usa desde el archivo oficial; no se rearma.','Va en cierres: final de video, última lámina, contratapa, firma de correo, recepción, merch.','No va en cada post: ahí la respuesta con esfera ya cierra.','Nunca pegar la esfera al eslogan, traducirlo ni cambiar pesos o cursivas.','Growth, Brand, Engine y Voice según la capability que lidera (09_marca-agencia).'],12.5)),1600,1160);
