import fs from 'node:fs';import{construirPrompt}from'../../scripts/foto/build-prompt.mjs';
const root='ai-generations/2026-09-22_aeo-final-safe-v07';fs.mkdirSync(root+'/brief',{recursive:true});fs.mkdirSync(root+'/plates',{recursive:true});
for(const base of ['01-fuera','02-reconoces','03-referencia','04-elegida']){
const f=JSON.parse(fs.readFileSync(`ai-generations/2026-09-22_aeo-cta-v04/brief/${base}-45.json`));f.id=base+'-916';f.formato='9:16';
f.lecho.objeto=({'01-fuera':'the soft curved graphite upholstered back of the viewer chair close to the lens, crossing only the bottom 20 percent of the photograph','02-reconoces':'the near dark charcoal corridor windowsill, below the subject, crossing only the bottom 20 percent','03-referencia':'the near pale matte review table surface, crossing only the bottom 20 percent','04-elegida':'the near graphite equipment housing below the inclined touchscreen, crossing only the bottom 20 percent'})[base];
f.lecho.tono=base==='03-referencia'?'pale almost white, naturally lit, very soft optical defocus, smooth gradual transition':'deep charcoal in real physical shadow, very soft optical defocus, smooth gradual transition';
f.escena=`EDIT THE ATTACHED NATIVE 9:16 PHOTOGRAPH. Correct its excessive foreground. Currently the blurred foreground begins near the middle and hides almost half the picture. The new image must show the actual scene much larger and extending farther downward. Reduce the near foreground obstruction to ONLY THE LOWEST FIFTH (bottom 20–22%). Its upper edge is now near y=79–80%, NOT near the middle. Reveal and re-stage the real desk, character body, and equipment behind it to fill the previously hidden middle/lower scene. Keep the upper y=0–32% real dark wall empty for later typography; the top of the character's head or monitor does not enter that space. Main narrative scene occupies y=34–79%, much taller and larger than before. The physical foreground crosses the bottom edge only, leaving a calm central region at y=82–85% for a later official signature. This is NOT a black rectangle, a gradient, a scrim, an added canvas band or an enlarged blur. Restore realistic physical scene content, natural perspective and the SAME character identity, clothing, light, materials and screen content. Keep the exact same native 9:16 ratio. No headline, no text labels, no CTA, no watermark, no editorial logo. `+({'01-fuera':'Codex, same blue cloud silhouette and face, stands on the real desk at left. The large monitor at right shows the same two blue source cards and empty third slot. Enlarge the desk/monitor/Codex ensemble downward; the foreground chair only grazes the bottom fifth.','02-reconoces':'Preserve Nexa in side/rear profile, same facial features and hair, navy corporate polo. Enlarge her torso downward. Both hands naturally hold her tablet facing inward/up toward her, NOT aimed at the viewer. No pointing. The tablet shows the modern tower, the monitor at right the old warehouse. All fingers remain natural, screen orientations physically consistent. The lower foreground windowsill begins below her hands and torso, near the lowest fifth.','03-referencia':'Preserve Nexa side/rear profile looking at the physical projection on the real wall. She holds her tablet toward herself, without pointing. Keep the exact source card projection and blue accent, but enlarge the scene vertically downward: her body and projector can extend to y=78%. The near pale review table begins ONLY at y=79–80%, with calm pale surface at82–85%. The projection must NOT invade upper-left wall where the headline will sit (x=8–52%,y=16–32%).','04-elegida':'Preserve the anatomically correct hand and natural index finger hovering before touching the selected source card, its consistent reflection, the inclined touchscreen, and Codex behind. Make screen and hand occupy the available middle/lower area down to y=79%. Foreground equipment housing only enters at the lowest fifth; no giant dark block hiding the lower half.'})[base];
fs.writeFileSync(`${root}/brief/${f.id}.json`,JSON.stringify(f,null,2)+'\n');const p=construirPrompt(f);fs.writeFileSync(`${root}/brief/${f.id}.prompt.txt`,p.prompt);
}
