import fs from'node:fs';import path from'node:path';import sharp from'sharp';
const dir=path.dirname(path.resolve(process.argv[2]||'ai-generations/2026-09-22_aeo-cta-v03/piezas.json')),plan=JSON.parse(fs.readFileSync(dir+'/piezas.json'));
const L=rgb=>{const a=rgb.map(c=>{c/=255;return c<=.04045?c/12.92:((c+.055)/1.055)**2.4});return a[0]*.2126+a[1]*.7152+a[2]*.0722};const hex=h=>L(h.match(/[a-f\d]{2}/gi).map(x=>parseInt(x,16)));const ratio=(a,b)=>(Math.max(a,b)+.05)/(Math.min(a,b)+.05);const round=n=>+n.toFixed(3);const rows=[];
for(const s of plan){const raw=await sharp(path.resolve(dir,s.plate)).removeAlpha().raw().toBuffer({resolveWithObject:true}),{width:w,height:h,channels:ch}=raw.info;const bg=(x,y)=>L([...raw.data.subarray((y*w+x)*ch,(y*w+x)*ch+3)]);
const e=JSON.parse(fs.readFileSync(`${dir}/out/${s.id}-cta-evidence.json`)),lay=JSON.parse(fs.readFileSync(`${dir}/out/${s.id}-layout.json`));const minBox=(b,ink)=>{let min=Infinity;for(let y=Math.floor(b.top);y<Math.ceil(b.bottom);y++)for(let x=Math.floor(b.left);x<Math.ceil(b.right);x++)min=Math.min(min,ratio(ink,bg(x,y)));return min};
const text=e.variant==='solid'?ratio(hex(e.colors.ink),hex(e.colors.surface)):minBox(e.textBounds,hex(e.colors.ink));const descriptor=minBox(e.descriptorBounds,1);let border=null;
if(e.variant!=='text'){border=Infinity;const b=e.surface;for(let y=Math.floor(b.top)-2;y<=Math.ceil(b.bottom)+2;y++)for(let x=Math.floor(b.left)-2;x<=Math.ceil(b.right)+2;x++){if(y>Math.floor(b.top)+3&&y<Math.ceil(b.bottom)-3&&x>Math.floor(b.left)+3&&x<Math.ceil(b.right)-3)continue;border=Math.min(border,ratio(hex(e.colors.surface),bg(x,y)));}}
const control=await sharp(`${dir}/out/${s.id}-controls.svg`).ensureAlpha().raw().toBuffer();let ctrl=Infinity,count=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;if(control[i+3]>=250&&L([...control.subarray(i,i+3)])>.5){ctrl=Math.min(ctrl,ratio(L([...control.subarray(i,i+3)]),bg(x,y)));count++;}}
const overlay=await sharp(`${dir}/out/${s.id}-overlay.svg`).ensureAlpha().raw().toBuffer();let right=0,bottom=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(overlay[(y*w+x)*4+3]>12){right=Math.max(right,x);bottom=Math.max(bottom,y)}
const otherText=lay.elements.filter(e=>!['cta','descriptor'].includes(e.id)).map(e=>({id:e.id,min:minBox(e.box,e.id.includes('acento')?hex('#ff6500'):1),threshold:e.id.startsWith('dominante')?3:4.5}));
const reserve=s.editorialReserve;const compositionPass=right<=reserve.maxRight&&bottom<=reserve.maxBottom;
const row={otherText,compositionPass,id:s.id,style:e.variant,colors:e.colors,ctaTextMin:round(text),descriptorMin:round(descriptor),boundaryMin:border==null?null:round(border),cursorAndControlsMin:round(ctrl),controlCorePixels:count,overlayBounds:{right,bottom},contrastPass:otherText.every(t=>t.min>=t.threshold)&&text>=4.5&&descriptor>=4.5&&(border==null||border>=3)&&ctrl>=3};rows.push(row);}
fs.writeFileSync(`${dir}/out/accesibilidad-cta.json`,JSON.stringify({method:'WCAG relative luminance; conservative minimum across full text bounding boxes on native photograph (not p98); solid text versus surface; boundary band versus photograph; opaque light cursor/selection core pixels versus photograph. Antialiased edges excluded for controls, not text boxes.',thresholds:{text:4.5,boundary:3,controls:3},results:rows},null,2));console.log(JSON.stringify(rows));if(rows.some(r=>!r.contrastPass||!r.compositionPass))process.exitCode=1;
