/**
 * TASK-811 — domain microcopy extracted from src/config/greenhouse-nomenclature.ts.
 *
 * This module keeps domain-specific visible copy out of the product
 * nomenclature/navigation contract while preserving type-safe GH_* ergonomics.
 * Do not rewrite strings in this file as part of trim-only work.
 */

export const GH_INTERNAL_MESSAGES = {
  internal_dashboard_clients: 'Clientes',
  internal_dashboard_active_users: 'Usuarios activos',
  internal_dashboard_pending_users: 'Pendientes de activacion',
  internal_dashboard_internal_admins: 'Admins internos',
  internal_dashboard_spaces_without_activity: 'Spaces sin actividad',
  internal_dashboard_global_otd: 'OTD global',
  internal_dashboard_no_new_clients: 'Sin altas nuevas este mes.',
  internal_dashboard_active_subtitle: (active: number, total: number) => `${active} de ${total} con al menos 1 login`,
  internal_dashboard_active_status_low: 'Activacion baja',
  internal_dashboard_active_status_healthy: 'Base activa',
  internal_dashboard_active_footer: 'Semaforo de activacion efectiva del portal.',
  internal_dashboard_global_subtitle: 'Promedio ponderado de OTD visible',
  internal_dashboard_title: 'Control Tower',
  internal_dashboard_requires_attention: (count: number) => `${count} requieren atencion`,
  internal_dashboard_onboarding: (count: number) => `${count} en onboarding`,
  internal_dashboard_inactive: (count: number) => `${count} inactivos`,
  internal_dashboard_create_space: 'Crear space',
  internal_dashboard_export: 'Exportar',
  internal_dashboard_summary: (activeClients: number, invitedUsers: number, lastActivity: string) =>
    `${activeClients} clientes activos. ${invitedUsers} usuarios pendientes de activacion. Ultima actividad: ${lastActivity}.`,
  internal_dashboard_pending_subtitle: 'Usuarios invitados sin login visible',
  internal_dashboard_pending_status_risk: 'Onboarding en riesgo',
  internal_dashboard_pending_status_ok: 'Bajo control',
  internal_dashboard_pending_footer: 'Si supera 80% hay friccion de activacion.',
  internal_dashboard_admins_subtitle: 'Equipo Efeonce con acceso visible',
  internal_dashboard_admins_footer: 'Sin semaforo: sirve como control de cobertura interna.',
  internal_dashboard_spaces_without_activity_subtitle: '0 scopes o sin actividad en los ultimos 30 dias',
  internal_dashboard_spaces_without_activity_status_alert: 'Revisar hoy',
  internal_dashboard_spaces_without_activity_status_clear: 'Sin alertas',
  internal_dashboard_spaces_without_activity_footer: 'Indicador directo de clientes que necesitan intervencion.',
  internal_dashboard_otd_status_empty: 'Sin data',
  internal_dashboard_otd_status_healthy: 'Saludable',
  internal_dashboard_otd_status_watch: 'Bajo observacion',
  internal_dashboard_otd_status_alert: 'Requiere atencion',
  internal_dashboard_otd_footer: (projects: number) =>
    projects > 0 ? `${projects} proyectos con OTD visible.` : 'Sin proyectos con OTD visible todavia.',
  internal_dashboard_create_space_tooltip: 'El flujo de creacion de spaces aun no existe como mutacion dedicada en el repo.',
  internal_dashboard_kpis_error_title: 'No pudimos cargar los indicadores del control tower',
  internal_dashboard_kpis_error_description: 'Reintenta la lectura de la capa ejecutiva en unos segundos.',
  internal_dashboard_table_error_title: 'No pudimos cargar la lista de clientes',
  internal_dashboard_table_error_description: 'Intenta de nuevo. Si persiste, revisa la consulta interna del control tower.',
  internal_dashboard_table_title: 'Clientes',
  internal_dashboard_table_subtitle:
    'Control operativo de spaces con prioridad visual para onboarding trabado, baja activacion y falta de scope.',
  internal_dashboard_table_search_placeholder: 'Buscar por cliente o email',
  internal_dashboard_table_filter_all: 'Todos',
  internal_dashboard_table_filter_active: 'Activos',
  internal_dashboard_table_filter_onboarding: 'Onboarding',
  internal_dashboard_table_filter_attention: 'Requiere atencion',
  internal_dashboard_table_filter_inactive: 'Inactivos',
  internal_dashboard_table_client_header: 'Cliente',
  internal_dashboard_table_status_header: 'Estado',
  internal_dashboard_table_users_header: 'Usuarios',
  internal_dashboard_table_projects_header: 'Proyectos',
  internal_dashboard_table_capabilities_header: 'Modulos',
  internal_dashboard_table_last_activity_header: 'Ultima actividad',
  internal_dashboard_table_actions_header: 'Acciones',
  internal_dashboard_table_no_contact: 'Sin contacto principal',
  internal_dashboard_table_active_users_summary: (active: number, total: number) => `${active} activos / ${total} total`,
  internal_dashboard_table_pending_users_summary: (pending: number) => `${pending} pendientes de activacion`,
  internal_dashboard_table_projects_base: (count: number) => `${count} base`,
  internal_dashboard_table_no_capabilities: 'Sin modulos activos',
  internal_dashboard_table_last_login_recorded: 'Ultimo login registrado',
  internal_dashboard_table_no_login: 'Sin login visible',
  internal_dashboard_table_view: 'Ver',
  internal_dashboard_table_view_detail: 'Ver detalle',
  internal_dashboard_table_view_as_client: 'Ver como cliente',
  internal_dashboard_table_edit: 'Editar',
  internal_dashboard_table_deactivate: 'Desactivar',
  internal_dashboard_table_empty_title: 'Sin clientes configurados.',
  internal_dashboard_table_empty_description: 'Crea tu primer space para comenzar.',
  internal_dashboard_table_empty_filtered_title: 'Sin resultados para este filtro.',
  internal_dashboard_table_empty_filtered_description: 'Prueba con otro filtro o busca por nombre.',

  admin_tenants_chip: 'Gobernanza de spaces',
  admin_tenants_hero_title: 'Administra spaces como empresas, con su postura de acceso, modulos y usuarios asociados.',
  admin_tenants_hero_subtitle:
    'Cada space representa una empresa cliente del portal. Esta vista consolida estado comercial y operativo sin colapsar metadata del cliente con identidad de usuario.',
  admin_tenants_total_spaces: 'Spaces',
  admin_tenants_active_spaces: 'Activos',
  admin_tenants_with_credentials: 'Con credenciales',
  admin_tenants_pending_reset: 'Pendientes reset',
  admin_tenants_with_projects: 'Con proyectos en scope',
  admin_tenants_table_subtitle:
    'Cada fila representa un cliente visible como space. El detalle agrupa usuarios, proyectos visibles, modulos contratados y feature flags activos.',
  admin_tenants_no_record: 'Sin registro',
  admin_tenants_no_contact: 'Sin contacto principal',
  admin_tenants_home_label: 'Home',
  admin_tenants_no_modules: 'Sin modulos activos',
  admin_tenants_features_label: 'Feature flags',
  admin_tenants_updated_label: 'Actualizacion',
  admin_tenants_last_login_label: 'Ultimo login',

  admin_users_total: 'Usuarios',
  admin_users_total_subtitle: 'Usuarios cliente sobre el total visible',
  admin_users_active: 'Activos',
  admin_users_active_subtitle: 'Base operativa con acceso habilitado',
  admin_users_invited: 'Invitados',
  admin_users_invited_subtitle: 'Onboarding pendiente o acceso en curso',
  admin_users_internal: 'Internos',
  admin_users_internal_subtitle: 'Staff Efeonce habilitado en la plataforma',
  admin_users_table_subtitle: 'Usuarios, roles y scopes visibles del portal.',
  admin_users_filters_title: 'Filtros',
  admin_users_filter_role: 'Filtrar rol',
  admin_users_filter_role_all: 'Todos los roles',
  admin_users_filter_tenant: 'Filtrar tipo de space',
  admin_users_filter_tenant_all: 'Todos los spaces',
  admin_users_filter_status: 'Filtrar status',
  admin_users_filter_status_all: 'Todos los status',
  admin_users_search_placeholder: 'Buscar usuario',
  admin_users_export: 'Exportar',
  admin_users_roles_button: 'Roles y permisos',
  admin_users_no_data: 'Sin datos disponibles',
  admin_users_user_header: 'Usuario',
  admin_users_role_header: 'Rol',
  admin_users_space_header: 'Space',
  admin_users_access_header: 'Acceso',
  admin_users_home_header: 'Home',
  admin_users_last_login_header: 'Ultimo login',
  admin_users_actions_header: 'Acciones',
  admin_users_no_role: 'Sin rol',
  admin_users_primary_role: 'Rol primario',
  admin_users_extra_roles: (count: number) => `+${count} roles extra`,
  admin_users_access_detail: (projects: number, routeGroups: number) => `${projects} proyectos · ${routeGroups} route groups`,
  admin_users_tenant_client: 'Cliente',
  admin_users_tenant_internal: 'Efeonce interno',
  admin_users_view: 'Ver',
  admin_users_open_detail: 'Abrir detalle',
  admin_users_open_roles: 'Ir a roles',

  admin_roles_subtitle:
    'Patron Vuexy Roles reinterpretado sobre roles reales de Greenhouse y sus scopes operativos.',
  admin_roles_assigned_summary: (users: number, clients: number) => `${users} usuarios asignados en ${clients} spaces.`,
  admin_roles_matrix_title: 'Matriz de roles actual',
  admin_roles_role_header: 'Rol',
  admin_roles_tenant_type_header: 'Tipo de space',
  admin_roles_route_groups_header: 'Grupos de ruta',
  admin_roles_users_header: 'Usuarios',
  admin_roles_spaces_header: 'Spaces',

  admin_tenant_users_active: 'Activos',
  admin_tenant_users_active_subtitle: 'Con acceso operativo',
  admin_tenant_users_invited: 'Invitados',
  admin_tenant_users_invited_subtitle: 'Pendientes de activacion',
  admin_tenant_users_total: 'Total',
  admin_tenant_users_total_subtitle: 'Usuarios del space',
  admin_tenant_users_title: 'Usuarios del space',
  admin_tenant_users_subtitle: 'Patron Vuexy User Management adaptado a client_users, roles y scopes reales del tenant.',
  admin_tenant_users_search_placeholder: 'Buscar usuario',
  admin_tenant_users_status_label: 'Estado',
  admin_tenant_users_status_all: 'Todos',
  admin_tenant_users_invite: 'Invitar usuario',
  admin_tenant_users_resend: 'Reenviar pendientes',
  admin_tenant_users_no_data: 'No hay usuarios para este filtro.',
  admin_tenant_users_user_header: 'Usuario',
  admin_tenant_users_role_header: 'Rol',
  admin_tenant_users_access_header: 'Acceso',
  admin_tenant_users_scopes_header: 'Scopes',
  admin_tenant_users_last_login_header: 'Ultimo login',
  admin_tenant_users_actions_header: 'Acciones',
  admin_tenant_users_no_role: 'Sin rol',
  admin_tenant_users_extra_roles: (count: number) => `+${count} roles extra`,
  admin_tenant_users_manual_source: 'Manual o interno',
  admin_tenant_users_no_route_groups: 'Sin route groups',
  admin_tenant_users_view: 'Ver',
  admin_tenant_users_resend_invite: 'Reenviar invitacion',
  admin_tenant_users_change_role: 'Cambiar rol',
  admin_tenant_users_deactivate: 'Desactivar',

  // ── Admin User Detail: Header ──
  admin_user_detail_job_title_empty: 'Sin cargo asignado',
  admin_user_detail_avatar_helper: 'PNG, JPG, WEBP o SVG hasta 5 MB. Visible en admin y en la sesion autenticada del usuario.',
  admin_user_detail_resend_onboarding: 'Reenviar onboarding',
  admin_user_detail_review_access: 'Revisar acceso',
  admin_user_detail_member_since: (date: string) => `Activo desde ${date}`,
  admin_user_detail_project_count: (count: number) => `${count} ${count === 1 ? 'proyecto' : 'proyectos'}`,
  admin_user_detail_campaign_count: (count: number) => `${count} ${count === 1 ? 'campana' : 'campanas'}`,

  // ── Admin User Detail: Tabs ──
  admin_user_detail_tab_profile: 'Perfil',
  admin_user_detail_tab_security: 'Seguridad',
  admin_user_detail_tab_organization: 'Organizacion',
  admin_user_detail_tab_roles: 'Roles',
  admin_user_detail_tab_access: 'Accesos',

  // ── Admin User Detail: Tab Accesos ──
  admin_user_access_roles_title: 'Roles asignados',
  admin_user_access_roles_description: 'Roles activos del usuario y los módulos que habilitan.',
  admin_user_access_no_roles: 'Sin roles asignados.',
  admin_user_access_sets_title: 'Sets de permisos',
  admin_user_access_sets_description: 'Conjuntos de vistas adicionales asignados al usuario.',
  admin_user_access_no_sets: 'Sin sets de permisos asignados.',
  admin_user_access_overrides_title: 'Ajustes manuales',
  admin_user_access_overrides_description: 'Vistas otorgadas o revocadas individualmente al usuario.',
  admin_user_access_col_view_code: 'Codigo de vista',
  admin_user_access_col_label: 'Nombre',
  admin_user_access_col_source: 'Origen',
  admin_user_access_effective_title: 'Vistas efectivas',
  admin_user_access_effective_description: 'Todas las vistas a las que tiene acceso este usuario, agrupadas por seccion.',
  admin_user_access_no_views: 'Este usuario no tiene vistas efectivas.',

  // ── Admin User Detail: Tab Perfil — Sobre el usuario (AboutOverview) ──
  admin_user_detail_about_title: 'Sobre el usuario',
  admin_user_detail_section_personal: 'Informacion personal',
  admin_user_detail_section_contact: 'Contacto',
  admin_user_detail_section_identifiers: 'Identificadores',
  admin_user_detail_label_name: 'Nombre completo:',
  admin_user_detail_label_email: 'Correo electronico:',
  admin_user_detail_label_job_title: 'Cargo:',
  admin_user_detail_label_username: 'Usuario:',
  admin_user_detail_label_status: 'Estado:',
  admin_user_detail_label_timezone: 'Zona horaria:',
  admin_user_detail_label_locale: 'Idioma:',
  admin_user_detail_label_public_id: 'ID de colaborador:',
  admin_user_detail_label_identity_id: 'EO-ID:',
  admin_user_detail_no_job_title: 'Sin cargo asignado',
  admin_user_detail_no_timezone: 'No configurada',
  admin_user_detail_no_locale: 'No configurado',

  // ── Admin User Detail: Tab Perfil — Actividad y alcance ──
  admin_user_detail_activity_title: 'Actividad reciente',
  admin_user_detail_scope_title: 'Alcance operativo',
  admin_user_detail_campaign_context_title: 'Campanas asignadas',
  admin_user_detail_campaign_context_description: (count: number) =>
    count === 0
      ? 'Este usuario no tiene campanas asignadas.'
      : `Este usuario tiene acceso a ${count} ${count === 1 ? 'campana' : 'campanas'}.`,
  admin_user_detail_no_campaign_scopes: 'Sin campanas asignadas.',

  // ── Admin User Detail: Tab Seguridad ──
  admin_user_detail_auth_title: 'Perfil de autenticacion',
  admin_user_detail_auth_description: 'Configuracion de acceso y metodo de autenticacion del usuario.',
  admin_user_detail_label_auth_mode: 'Metodo de autenticacion:',
  admin_user_detail_label_password_algorithm: 'Algoritmo:',
  admin_user_detail_label_last_login: 'Ultimo acceso:',
  admin_user_detail_label_invited_at: 'Fecha de invitacion:',
  admin_user_detail_no_password_algorithm: 'No disponible',
  admin_user_detail_never_logged_in: 'Nunca ha iniciado sesion',
  admin_user_detail_not_invited: 'Sin invitacion registrada',

  admin_user_detail_roles_overview_title: 'Roles y permisos',
  admin_user_detail_roles_overview_description:
    'Vista rapida de los roles asignados y los modulos habilitados. Para modificar roles, ve a la pestana Roles.',
  admin_user_detail_no_roles: 'Sin roles asignados.',
  admin_user_detail_route_groups: 'Modulos habilitados',
  admin_user_detail_no_route_groups: 'Sin modulos habilitados.',

  admin_user_detail_audit_title: 'Auditoria',
  admin_user_detail_audit_description: 'Fechas de creacion y ultima actualizacion del registro.',
  admin_user_detail_label_created: 'Fecha de creacion:',
  admin_user_detail_label_updated: 'Ultima actualizacion:',

  // ── Admin User Detail: Tab Organizacion ──
  admin_user_detail_tenant_title: 'Relacion con el tenant',
  admin_user_detail_tenant_description: 'Datos de la organizacion y el espacio al que pertenece este usuario.',
  admin_user_detail_label_client: 'Organizacion:',
  admin_user_detail_label_contact: 'Contacto principal:',
  admin_user_detail_label_hubspot: 'HubSpot:',
  admin_user_detail_label_space_id: 'Space ID:',
  admin_user_detail_label_internal_key: 'Clave interna:',
  admin_user_detail_label_tenant_type: 'Tipo de tenant:',
  admin_user_detail_no_contact: 'Sin contacto registrado',
  admin_user_detail_no_hubspot: 'Sin integracion HubSpot',

  admin_user_detail_features_title: 'Funcionalidades activas',
  admin_user_detail_features_description:
    'Modulos y funcionalidades habilitadas para el tenant de este usuario. Los flags controlan la experiencia dentro del portal.',
  admin_user_detail_feature_flags: 'Feature flags',
  admin_user_detail_no_feature_flags: 'Sin funcionalidades especiales activadas.',
  admin_user_detail_label_home: 'Pagina de inicio del portal:',

  admin_user_detail_commercial_title: 'Preparacion comercial',
  admin_user_detail_commercial_description:
    'Contexto comercial del cliente. Este espacio se habilitara con la integracion de facturacion y planes contratados.',
  admin_user_detail_commercial_chip: 'Contexto comercial',
  admin_user_detail_commercial_pending: 'Pendiente',
  admin_user_detail_commercial_ready: 'Conectado',
  admin_user_detail_commercial_readiness: 'Preparacion comercial',
  admin_user_detail_commercial_readiness_value: (hasContact: boolean) => hasContact ? '65%' : '35%',

  admin_user_detail_resend_onboarding_success: 'Invitacion de onboarding reenviada.',
  admin_user_detail_resend_onboarding_error: 'No se pudo reenviar la invitacion.',
  admin_user_detail_resend_onboarding_not_eligible: 'Este usuario no es elegible para reenvio de onboarding.',

  // Cross-links Person 360
  admin_user_detail_link_people: 'Ver perfil operativo',
  people_detail_link_admin: 'Ver acceso y permisos',

  admin_tenant_preview_title: 'Ver como cliente',
  admin_tenant_preview_subtitle: (clientName: string) =>
    `Estas viendo el dashboard del space cliente ${clientName} desde tu sesion de administrador.`,
  admin_tenant_preview_back: 'Volver al space',
  admin_tenant_preview_spaces: 'Ir a spaces',

  admin_tenant_detail_header_summary:
    'Estado completo de la cuenta: modulos, usuarios, CRM y visibilidad operativa del space en una sola vista.',
  admin_tenant_detail_header_meta: (publicId: string, hubspotCompanyId: string | null, timezone: string | null, fetchedAt: string) =>
    `Space ID ${publicId}  |  CRM ${hubspotCompanyId || '--'}  |  Timezone ${timezone || '--'}  |  Ultima lectura HubSpot ${fetchedAt}`,
  admin_tenant_detail_logo_helper: 'PNG, JPG, WEBP o SVG hasta 5 MB. Visible en admin, internal y superficies autenticadas del space.',
  admin_tenant_detail_view_as_client: 'Ver como cliente',
  admin_tenant_detail_save_manual: 'Guardar seleccion manual',
  admin_tenant_detail_refresh_hubspot: 'Refrescar lectura HubSpot',
  admin_tenant_detail_open_preview: 'Abrir preview cliente',
  admin_tenant_detail_deactivate_space: 'Desactivar space',
  admin_tenant_detail_kpi_users: 'Usuarios',
  admin_tenant_detail_kpi_users_subtitle: (invited: number) => `${invited} invitados pendientes`,
  admin_tenant_detail_kpi_business_lines: 'Business lines',
  admin_tenant_detail_kpi_business_lines_subtitle: 'Activas para este space',
  admin_tenant_detail_kpi_projects: 'Proyectos',
  admin_tenant_detail_kpi_projects_subtitle: (count: number) => `${count} detectados en Notion`,
  admin_tenant_detail_kpi_modules: 'Service modules',
  admin_tenant_detail_kpi_modules_subtitle: 'Habilitados en governance',

  admin_tenant_capabilities_business_lines_title: 'Business lines',
  admin_tenant_capabilities_business_lines_subtitle:
    'Familias comerciales activas del space con color operativo y origen de asignacion.',
  admin_tenant_capabilities_service_modules_title: 'Service modules',
  admin_tenant_capabilities_service_modules_subtitle:
    'Tabla compacta de modulos activos o disponibles para este tenant, con sorting y filtro local.',
  admin_tenant_capabilities_feature_flags_title: 'Feature flags',
  admin_tenant_capabilities_feature_flags_empty: 'Sin feature flags activos.',
  admin_tenant_capabilities_company_record: 'Registro de empresa',
  admin_tenant_capabilities_company_record_empty: 'Sin company mapping',
  admin_tenant_capabilities_edit_title: 'Editar governance manual',
  admin_tenant_capabilities_edit_subtitle:
    'Mantiene la logica actual de precedencia manual vs sync externo, pero ahora dentro del tab correcto.',
  admin_tenant_capability_state_active: 'Activo',
  admin_tenant_capability_state_available: 'Disponible',
  admin_tenant_capability_description_empty: 'Sin descripcion operativa',
  admin_tenant_service_modules_search: 'Buscar modulo',
  admin_tenant_service_modules_active_count: (count: number) => `${count} activos`,
  admin_tenant_service_modules_empty: 'Sin service modules registrados para este filtro',
  admin_tenant_service_modules_header_module: 'Modulo',
  admin_tenant_service_modules_header_code: 'Codigo',
  admin_tenant_service_modules_header_family: 'Familia',
  admin_tenant_service_modules_header_state: 'Estado',
  admin_tenant_service_modules_header_updated: 'Actualizado',
  admin_tenant_service_modules_no_date: 'Sin fecha',

  admin_tenant_governance_eyebrow: 'Capability governance',
  admin_tenant_governance_title: 'Capabilities activas del space',
  admin_tenant_governance_subtitle:
    'Define que lineas de negocio y modulos quedan habilitados para este cliente. Admin fija el estado operativo y las integraciones externas solo pueden actualizarlo si envian payload explicito desde el registro de empresa.',
  admin_tenant_governance_business_lines_active: 'Business lines activas',
  admin_tenant_governance_service_modules_active: 'Service modules activos',
  admin_tenant_governance_company_record: 'Registro de empresa',
  admin_tenant_governance_ready: 'Listo',
  admin_tenant_governance_pending: 'Pendiente',
  admin_tenant_governance_rule_button: 'Regla de precedencia manual',
  admin_tenant_governance_rule_body:
    'La edicion manual tiene precedencia. La sincronizacion externa se admite via API con `businessLines` y `serviceModules` explicitos; no se deriva desde deals.',
  admin_tenant_governance_business_lines_title: 'Business lines',
  admin_tenant_governance_business_lines_subtitle:
    'Activa solo las familias comerciales que deben estar disponibles en este tenant.',
  admin_tenant_governance_service_modules_title: 'Service modules',
  admin_tenant_governance_service_modules_subtitle:
    'Habilita los modulos concretos que el space puede usar y reportar.',
  admin_tenant_governance_company_mapping_empty: 'Sin company mapping',
  admin_tenant_governance_company_mapping_with_id:
    'Las integraciones externas deben sincronizar capabilities desde el objeto empresa.',
  admin_tenant_governance_company_mapping_without_id:
    'Sin una empresa asociada, este tenant solo puede gobernarse manualmente desde admin.',
  admin_tenant_governance_tenant_label: (clientId: string) => `Tenant: ${clientId}`,
  admin_tenant_governance_save: 'Guardar seleccion manual',
  admin_tenant_governance_save_error: 'No pudimos guardar las capabilities del tenant.',
  admin_tenant_governance_save_success: 'Capabilities guardadas desde admin.',
  admin_tenant_governance_source_controlled: 'Controlled',
  admin_tenant_governance_source_admin_off: 'Admin off',
  admin_tenant_governance_source_hubspot: 'HubSpot',
  admin_tenant_governance_source_hubspot_off: 'HubSpot off',
  admin_tenant_governance_source_active: 'Active',
  admin_tenant_governance_source_available: 'Available',

  admin_tenant_crm_no_contacts: 'No habia contactos CRM por provisionar.',
  admin_tenant_crm_provision_error_partial: (processed: number, total: number) =>
    `No pudimos completar el provisioning de contactos CRM. Se procesaron ${processed} de ${total} contactos antes del corte.`,
  admin_tenant_crm_provision_error:
    'No pudimos completar el provisioning de contactos CRM. Reintenta en unos segundos.',
  admin_tenant_crm_config_title: 'Configuracion comercial',
  admin_tenant_crm_config_subtitle: 'Contexto compacto del registro comercial y la relacion actual con HubSpot.',
  admin_tenant_crm_business_lines: 'Business lines',
  admin_tenant_crm_business_lines_empty: 'Sin business lines.',
  admin_tenant_crm_service_modules: 'Service modules',
  admin_tenant_crm_service_modules_empty: 'Sin service modules.',
  admin_tenant_crm_lifecycle: 'Lifecycle',
  admin_tenant_crm_lifecycle_empty: 'Sin lifecycle',
  admin_tenant_crm_live_ok: 'Lectura live de HubSpot operativa para company, owner y contactos asociados.',
  admin_tenant_crm_retry_live: 'Reintentar lectura live',
  admin_tenant_crm_contacts_title: 'Contactos CRM',
  admin_tenant_crm_contacts_subtitle: 'Lectura live de HubSpot reconciliada contra los accesos reales del space.',
  admin_tenant_crm_chip_hubspot: (count: number) => `${count} en HubSpot`,
  admin_tenant_crm_chip_reconciled: (count: number) => `${count} reconciliados`,
  admin_tenant_crm_chip_pending: (count: number) => `${count} pendientes`,
  admin_tenant_crm_chip_ambiguous: (count: number) => `${count} ambiguos`,
  admin_tenant_crm_chip_no_email: (count: number) => `${count} sin email`,
  admin_tenant_crm_provision_action: (count: number) => `Provisionar ${count}`,
  admin_tenant_crm_provision_progress: (processed: number, total: number) => `Provisionando ${processed}/${total}`,
  admin_tenant_crm_provision_info:
    'Provisionar crea o reconcilia accesos `invited` en `greenhouse.client_users` con rol base `client_executive`.',
  admin_tenant_crm_provision_batches: (size: number) => `Los lotes se ejecutan de a ${size} contactos por request.`,
  admin_tenant_crm_reconciliation_warning:
    'Hay brechas de reconciliacion que conviene resolver antes de nuevas invitaciones.',
  admin_tenant_crm_batch_progress: (current: number, total: number, processed: number, contacts: number) =>
    `Ejecutando lote ${current} de ${total}. Procesados ${processed} de ${contacts} contactos.`,
  admin_tenant_crm_empty_load_title: 'No pudimos cargar los contactos CRM',
  admin_tenant_crm_empty_load_description:
    'La lectura live de HubSpot devolvio una incidencia. Reintenta la consulta antes de provisionar contactos.',
  admin_tenant_crm_empty_no_contacts_title: 'No hay contactos asociados en HubSpot',
  admin_tenant_crm_empty_no_contacts_description:
    'Este space no tiene contactos company-level visibles en la lectura actual. Reintenta o revisa la asociacion CRM.',
  admin_tenant_crm_sync_now: 'Sincronizar ahora',
  admin_tenant_crm_tab_contact: 'Contacto',
  admin_tenant_crm_tab_body: 'Cuerpo',
  admin_tenant_crm_tab_cycle: 'Ciclo',
  admin_tenant_crm_tab_provider: 'Proveedor',
  admin_tenant_crm_header_contact: 'Contacto',
  admin_tenant_crm_header_channels: 'Canales',
  admin_tenant_crm_header_role: 'Cargo',
  admin_tenant_crm_header_cycle: 'Ciclo',
  admin_tenant_crm_header_provider: 'Proveedor',
  admin_tenant_crm_header_user: 'Usuario Greenhouse',
  admin_tenant_crm_header_status: 'Estado',
  admin_tenant_crm_status_ambiguous: 'Ambiguo',
  admin_tenant_crm_status_provisioned: 'Provisionado',
  admin_tenant_crm_status_pending: 'Pendiente',
  admin_tenant_crm_status_no_email: 'Sin email',
  admin_tenant_crm_phone_empty: 'Sin telefono',
  admin_tenant_crm_company_empty: 'Sin company',
  admin_tenant_crm_job_empty: 'Sin cargo',
  admin_tenant_crm_lead_stage_empty: 'Sin lifecycle',
  admin_tenant_crm_lead_status_empty: 'Sin lead status',
  admin_tenant_crm_exact_match: 'Match exacto HubSpot',
  admin_tenant_crm_reconciled_email: 'Reconciliacion por email',
  admin_tenant_crm_expected_id: (publicId: string) => `ID esperado: ${publicId}`,
  admin_tenant_crm_reconciled_label_exact: 'Match exacto HubSpot',
  admin_tenant_crm_reconciled_label_email: 'Reconciliado por email',
  admin_tenant_crm_no_access: 'Aun no existe acceso Greenhouse para este contacto.',
  admin_tenant_crm_hubspot_read_title: 'Lectura HubSpot',
  admin_tenant_crm_hubspot_read_subtitle:
    'Detalle tecnico y operativo del sync bajo demanda. Colapsado por defecto para no contaminar la lectura principal.',
  admin_tenant_crm_company_profile: 'Company profile',
  admin_tenant_crm_company_profile_empty: 'Sin lectura live',
  admin_tenant_crm_owner: 'Owner',
  admin_tenant_crm_owner_empty: 'Sin owner asignado',
  admin_tenant_crm_sync: 'Sync',
  admin_tenant_crm_sync_connected: 'Servicio conectado',
  admin_tenant_crm_sync_disconnected: 'Servicio no configurado',
  admin_tenant_crm_last_read: (value: string) => `Ultima lectura: ${value}`,
  admin_tenant_crm_base_url: (value: string) => `Base URL: ${value}`,

  admin_tenant_projects_title: 'Visibilidad de proyectos',
  admin_tenant_projects_subtitle: 'Proyectos visibles en scope para este space y su cobertura actual.',
  admin_tenant_projects_add: 'Agregar proyecto al scope',
  admin_tenant_projects_empty_title: 'No hay proyectos visibles en scope',
  admin_tenant_projects_empty_description:
    'Este space aun no tiene proyectos conectados a la visibilidad del tenant o no existen scopes activos.',
  admin_tenant_projects_users: (count: number) => `${count} usuarios`,
  admin_tenant_projects_open_source: 'Abrir origen en Notion',
  admin_tenant_projects_header_project: 'Proyecto',
  admin_tenant_projects_header_id: 'ID',
  admin_tenant_projects_header_users: 'Usuarios asignados',
  admin_tenant_projects_header_state: 'Estado',
  admin_tenant_projects_state_scoped: 'Scoped',

  admin_tenant_settings_identity_title: 'Identidad del space',
  admin_tenant_settings_label_space_id: 'Space ID',
  admin_tenant_settings_label_internal_key: 'Internal key',
  admin_tenant_settings_label_hubspot: 'HubSpot company',
  admin_tenant_settings_label_home: 'Portal home',
  admin_tenant_settings_label_timezone: 'Timezone',
  admin_tenant_settings_access_title: 'Estado de acceso',
  admin_tenant_settings_active_users: 'Usuarios activos',
  admin_tenant_settings_active_users_subtitle: (count: number) => `${count} invitados`,
  admin_tenant_settings_scoped_projects: 'Proyectos scoped',
  admin_tenant_settings_scoped_projects_subtitle: (count: number) => `${count} detectados`,
  admin_tenant_settings_company_record_title: 'Registro de empresa',
  admin_tenant_settings_company_connected: 'Integrado con HubSpot',
  admin_tenant_settings_company_disconnected: 'Sin integracion activa',
  admin_tenant_settings_live_sync: 'Ultima sync live',
  admin_tenant_settings_tenant_updated: 'Ultima actualizacion del tenant',
  admin_tenant_settings_created: 'Creado',
  admin_tenant_settings_notes_title: 'Notas operativas',
  admin_tenant_settings_notes_empty: 'Sin nota operativa registrada para este space.',
  admin_tenant_settings_notes_helper: 'La mutacion de notas internas aun no esta expuesta en esta superficie.',

  admin_tenant_tabs_capabilities: 'Capabilities',
  admin_tenant_tabs_users: 'Usuarios',
  admin_tenant_tabs_crm: 'CRM',
  admin_tenant_tabs_projects: 'Proyectos',
  admin_tenant_tabs_notion: 'Notion',
  admin_tenant_tabs_settings: 'Configuracion',
  admin_tenant_error_title: 'No pudimos renderizar esta seccion',
  admin_tenant_error_description:
    'Reintenta la carga. Si el problema persiste, revisa la integracion o el payload de este space.',
  admin_tenant_error_retry: 'Reintentar',
  admin_media_upload_cta: 'Subir imagen',
  admin_media_upload_replace: 'Cambiar imagen',
  admin_media_upload_progress: 'Guardando imagen...',
  admin_media_upload_success: 'Imagen guardada.',
  admin_media_upload_error: 'No pudimos guardar la imagen. Reintenta en unos segundos.',
  admin_media_upload_invalid_type: 'Selecciona un PNG, JPG, WEBP o SVG.',
  admin_media_upload_invalid_size: 'La imagen supera 5 MB.'
} as const
