export const AEO_MARKET_ERRORS = {
  aeo_market_unknown: 'El país indicado no está en el catálogo de mercados.',
  aeo_locale_unsupported: 'El idioma indicado no está disponible para esta medición.',
  aeo_market_not_configured: 'Configura y activa el mercado antes de solicitar una medición.',
  aeo_market_not_included: 'El mercado no está incluido en el servicio contratado.',
  aeo_primary_market_required: 'Selecciona otro mercado principal antes de cambiar este mercado.',
  aeo_multi_market_disabled: 'La medición en varios mercados aún no está habilitada.',
  aeo_market_not_active: 'Activa el mercado antes de seleccionarlo como principal.',
  aeo_market_archived: 'El mercado está archivado.',
  aeo_market_mismatch: 'El país y el idioma no corresponden al mercado seleccionado.',
  aeo_profile_not_found: 'No se encontró un perfil de marca activo.',
  aeo_competitor_set_required: 'Configura los competidores de este mercado.',
  aeo_competitors_invalid: 'Revisa los nombres de los competidores; puedes registrar hasta diez.',
  aeo_aliases_invalid: 'Revisa los nombres alternativos y su modo de coincidencia.',
  aeo_reason_required: 'Indica el motivo del cambio.',
  aeo_batch_invalid: 'Revisa los mercados y la clave de la solicitud.',
  aeo_idempotency_conflict: 'Esta clave ya corresponde a una solicitud diferente.',
  aeo_batch_not_found: 'No se encontró el lote solicitado.',
  disabled: 'Las mediciones no están habilitadas.',
  not_entitled: 'La organización no tiene acceso vigente a este servicio.',
  profile_required: 'Configura el perfil de marca antes de solicitar una medición.',
  category_unresolved: 'Confirma la categoría de la marca antes de medirla.',
  business_model_unconfirmed: 'Confirma el modelo de negocio de la marca.',
  quota_exhausted: 'La solicitud supera las mediciones disponibles para este período.',
  cost_blocked: 'La solicitud supera el presupuesto disponible.',
  budget_exhausted: 'La solicitud supera el presupuesto de la organización.',
  forbidden: 'No tienes acceso a esta acción.'
} as const
