/** Copy exclusivo del prototipo visual TASK-1835; no es una pantalla de autenticación. */
export const AUTH_SERVER_PREVIEW_COPY = {
  lang: 'es-CL',
  brand: 'Efeonce ID',
  previewNotice: 'Prototipo visual · datos ficticios · sin acceso real',
  contextLabel: 'Continúa hacia',
  loginTitle: 'Entra a Efeonce',
  loginIntro: 'Elige cómo acceder para continuar a la aplicación.',
  teamTitle: 'Equipo Efeonce',
  teamDescription: 'Usa tu cuenta corporativa de Microsoft.',
  microsoftAction: 'Continuar con Microsoft',
  invitationTitle: 'Acceso por invitación',
  invitationDescription: 'Si recibiste una invitación, entra con tu passkey o pide un enlace.',
  passkeyAction: 'Usar mi passkey',
  emailAlternative: 'O recibe un enlace por correo',
  emailLabel: 'Correo de tu invitación',
  emailPlaceholder: 'nombre@ejemplo.com',
  emailHint: 'No necesitas una contraseña.',
  emailAction: 'Enviarme un enlace',
  loginFooter: 'Después de entrar podrás revisar los permisos de la aplicación.',
  consentTitle: 'Revisa el acceso solicitado',
  consentIntro: (application: string) => `${application} solicita estos permisos para trabajar con tu organización.`,
  organizationLabel: 'Organización de este acceso',
  permissionsTitle: 'Permisos solicitados',
  readLabel: 'Lectura',
  writeLabel: 'Escritura',
  consentBoundary: 'Los permisos se limitan al acceso que ya tienes en esta organización.',
  denyAction: 'Cancelar',
  allowAction: 'Permitir',
  consentFooter: 'Si cancelas, volverás a la aplicación sin autorizar este acceso.',
  scopeDetails: 'Ver aplicación y permisos técnicos',
  applicationIdLabel: 'Identificador de aplicación',
  fixtureClientId: 'preview-client-not-registered',
  fixtureApplication: 'Asistente de proyectos · demo',
  fixtureOrganization: 'Organización de ejemplo',
  fixtureReadTitle: 'Consultar información de la organización',
  fixtureReadDescription: 'Leer la información disponible para tu cuenta en Efeonce.',
  fixtureWriteTitle: 'Actualizar la configuración SEO',
  fixtureWriteDescription: 'Modificar los ajustes SEO de esta organización. Este permiso permite realizar cambios.'
} as const
