export const GH_CONTRACTOR_SUBMISSIONS = {
  workRegion: 'Datos y documentos del envío',
  responseRegion: 'Respuesta y evidencia corregida',
  prepareTitle: 'Preparar envío',
  responseTitle: 'Responder observación',
  invoiceSelected: 'Boleta seleccionada',
  invoicePending: 'Boleta pendiente',
  invoiceOptional: 'Boleta opcional',
  evidenceSelected: 'Evidencia seleccionada',
  evidencePending: 'Evidencia pendiente',
  evidenceOptional: 'Evidencia opcional',
  hoursWorked: 'Horas trabajadas',
  daysWorked: 'Días trabajados',
  quantityPrecision: 'La cantidad admite hasta cuatro decimales.',
  saveFailed: 'No pudimos guardar tu envío. Intenta de nuevo.',
  newSubmission: 'Preparar otro período',
  prepareFirst: 'Prepara un envío antes de adjuntar los documentos del período.',
  periodStart: 'Inicio del servicio',
  periodEnd: 'Fin del servicio',
  periodHelp: 'Selecciona las fechas del trabajo que estás cobrando.',
  startRequired: 'Selecciona la fecha de inicio del servicio.',
  invalidDate: 'Selecciona una fecha válida para el período de servicio.',
  reversedPeriod: 'El fin del servicio debe ser igual o posterior al inicio.',
  periodSummary: 'Período'
} as const
