export const GH_GROWTH_FORMS = {
  navRoot: 'Growth',
  navForms: 'Forms',
  pageTitle: 'Growth Forms',
  pageSubtitle:
    'Control plane interno para formularios públicos, host surfaces, submissions, destinos y evidencia de entrega.',
  breadcrumbs: {
    admin: 'Admin Center',
    growth: 'Growth',
    forms: 'Forms',
  },
  actions: {
    createDraft: 'Crear draft',
    review: 'Enviar a review',
    publish: 'Publicar',
    deprecate: 'Deprecar',
    archive: 'Archivar',
    dispatch: 'Ejecutar dispatch',
    inspect: 'Inspeccionar',
    openComposer: 'Nuevo formulario',
    openEvidence: 'Ver evidencia',
    backToInspector: 'Volver al inspector',
    saveDraft: 'Guardar draft',
    cancel: 'Cancelar',
    refresh: 'Actualizar',
    resolveNow: 'Resolver ahora',
    keepWatching: 'Seguir monitoreando',
    planSmoke: 'Planificar smoke',
  },
  feedback: {
    ready: 'Cockpit listo. Los datos vienen del motor Growth Forms y sus readers gobernados.',
    refreshing: 'Actualizando cockpit.',
    actionQueued: 'Acción en curso. Mantén esta vista abierta hasta ver confirmación.',
  },
  aria: {
    sidecar: 'Inspector de Growth Forms',
    tableRegion: 'Lista operativa de Growth Forms',
    filterSearch: 'Buscar formularios por nombre o slug',
    selectForm: 'Seleccionar formulario',
    operationalPulse: 'Pulso operativo de Growth Forms',
  },
  fields: {
    search: 'Buscar',
    name: 'Nombre',
    slug: 'Slug',
    purpose: 'Propósito',
    formKind: 'Tipo',
    riskProfile: 'Riesgo',
  },
  table: {
    form: 'Form',
    status: 'Status',
    destinations: 'Destinos',
    surfaces: 'Surfaces',
    submissions: 'Submissions',
    lastSignal: 'Última señal',
    action: 'Acción',
  },
  units: {
    forms: 'forms',
    surfaces: 'surfaces',
    submissions: 'submissions',
    attempts: 'intentos',
    retry: 'reintentos',
    version: 'v',
    hours24: '24h',
  },
  filters: {
    all: 'All',
    ok: 'OK',
    risk: 'Risk',
  },
  formKinds: {
    lead_magnet: 'Lead magnet',
    subscribe: 'Subscribe',
    contact: 'Contact',
    diagnostic_intake: 'Diagnostic intake',
  },
  riskProfiles: {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
  },
  starter: {
    defaultName: 'Lead magnet público',
    defaultSlug: 'lead-magnet-publico',
    defaultPurpose: 'Capturar interés comercial low-risk desde una surface pública gobernada.',
    emailLabel: 'Email de trabajo',
    companyLabel: 'Organización',
    interestLabel: 'Interés principal',
    interestAiVisibility: 'AI Visibility',
    interestAutomation: 'Automatización',
    interestGrowthOps: 'Growth Ops',
    consentLabel: 'Acepto ser contactado por Efeonce y entiendo el uso de mis datos para este formulario.',
    successMessage: 'Recibimos tu información. El equipo Efeonce revisará el contexto antes del siguiente paso.',
  },
  helper: {
    starterTemplate:
      'Se crea con una plantilla gobernada low-risk: email, organización, interés y consentimiento explícito.',
    noFormSelected: 'Selecciona un formulario para ver versiones, destinos, surfaces y evidencia.',
    noSubmissions: 'Aún no hay submissions para este formulario.',
    noDestinations: 'Agrega un destino antes de publicar.',
    noResults: 'No hay formularios que coincidan con este filtro.',
    rowSelection: 'Enter abre el inspector. La evidence ledger conserva consent, delivery attempts y retry state.',
    archiveWarning: 'Archivar retira el formulario del circuito operativo. Úsalo solo si ya existe reemplazo publicado.',
    noDestinationsTitle: 'Destino pendiente',
    noDestinationsBody: 'Este formulario puede capturar evidencia, pero no debería publicarse como flujo comercial hasta definir un destino o confirmar que será ledger-only.',
    noSubmissionsTitle: 'Sin submissions todavía',
    noSubmissionsBody: 'Cuando el form reciba tráfico, aquí aparecerán acceptance state, consent snapshot y delivery attempts para auditar la ruta completa.',
    noSurfacesTitle: 'Sin host surface dedicada',
    noSurfacesBody: 'Autoriza una surface antes del smoke público. La surface controla origen, canal del renderer y slugs permitidos.',
  },
  sections: {
    commandCenter: 'Command center',
    readiness: 'Readiness',
    destinations: 'Destinos',
    surfaces: 'Host surfaces',
    recentSubmissions: 'Submissions recientes',
    evidenceLedger: 'Evidencia de entrega',
    authoring: 'Authoring',
    smoke: 'Smoke y dispatch',
    consent: 'Consent snapshot',
    operationalPulse: 'Pulso operativo',
    nextBestAction: 'Next best action',
    deliveryPath: 'Delivery path',
    decisionContext: 'Contexto de decisión',
  },
  decision: {
    deadLetterTitle: 'Revisar dead letters antes de publicar',
    deadLetterBody: 'Hay entregas agotadas o estados dead-letter. Abre evidencia y resuelve mapping, token o destino antes de seguir.',
    retryTitle: 'Drenar retry queue',
    retryBody: 'Hay submissions o attempts pendientes. Ejecuta dispatch y confirma si vuelven a delivered o pasan a revisión humana.',
    destinationTitle: 'Definir destino o confirmar ledger-only',
    destinationBody: 'El form está publicado, pero no tiene destino activo. Antes de tráfico real, decide si HubSpot u otro adapter recibe el lead.',
    surfaceTitle: 'Autorizar surface de smoke',
    surfaceBody: 'El form necesita una host surface activa para probar render, submit y medición desde WordPress/Astro/Next.',
    reviewTitle: 'Enviar a review',
    reviewBody: 'El draft ya puede entrar al control de publicación cuando campos, consentimiento y destino estén listos.',
    smokeTitle: 'Hacer smoke público',
    smokeBody: 'Publicado y sin submissions recientes. Ejecuta smoke de view/start/submit/accepted sin PII en dataLayer.',
    monitorTitle: 'Mantener monitoreo',
    monitorBody: 'La ruta está saludable. Revisa evidencia ante nuevos submissions o antes de un cambio de host surface.',
  },
  deliveryPath: {
    accepted: 'Accepted',
    routed: 'Routed',
    delivered: 'Delivered',
    evidence: 'Evidence',
    pending: 'Pendiente',
    complete: 'Completo',
    attention: 'Atención',
    blocked: 'Bloqueado',
  },
  sidecar: {
    inspectorEyebrow: 'Inspector operacional',
    inspectorSubtitle: 'Readiness, surfaces, destinos y evidencia del formulario seleccionado.',
    composerEyebrow: 'Authoring gobernado',
    composerTitle: 'Nuevo formulario',
    composerSubtitle: 'Crea un draft low-risk con contrato, consentimiento y analítica sin valores raw.',
    evidenceEyebrow: 'Ledger de evidencia',
    evidenceTitle: 'Evidencia',
    evidenceSubtitle: 'Consent snapshot, destination attempts, retry state y señales de entrega.',
  },
  insights: {
    publishedCoverage: 'Cobertura publicada',
    deliveryHealth: 'Salud de entrega',
    migrationReadiness: 'Readiness de migración',
    governedSurfaces: 'Surfaces gobernadas',
    noDeadLetters: 'Sin dead letters activos',
    deadLettersNeedReview: 'Dead letters requieren revisión',
    retryQueueClear: 'Retry queue limpia',
    retryQueuePending: 'Retry queue pendiente',
  },
  metrics: {
    forms: 'Forms',
    published: 'Publicados',
    activeSurfaces: 'Surfaces activas',
    submissions24h: 'Submissions 24h',
    retryQueue: 'Retry queue',
    deadLetters: 'Dead letters',
  },
  statuses: {
    draft: 'Draft',
    setup: 'Setup',
    ready: 'Ready',
    healthy: 'Healthy',
    attention: 'Attention',
    dead_letter: 'Dead letter',
    active: 'Activo',
    archived: 'Archivado',
    published: 'Publicado',
    review: 'Review',
    deprecated: 'Deprecado',
    received: 'Recibido',
    validated: 'Validado',
    accepted: 'Aceptado',
    rejected: 'Rechazado',
    routed: 'Enrutado',
    delivered: 'Entregado',
    destination_failed: 'Destino falló',
    retrying: 'Reintentando',
    pending: 'Pendiente',
    succeeded: 'Exitoso',
    failed: 'Fallido',
  },
  toast: {
    draftCreated: 'Draft creado. El cockpit se actualizará con el nuevo formulario.',
    lifecycleUpdated: 'Lifecycle actualizado.',
    dispatchQueued: 'Dispatch ejecutado.',
    smokePlanned: 'Smoke preparado. Revisa evidencia y host surface antes de tráfico real.',
    monitoringKept: 'Monitoreo activo. Vuelve a evidencia ante nuevos submissions.',
    actionFailed: 'No se pudo completar la acción. Revisa permisos o readiness.',
  },
  // TASK-1256 Slice 4 — datos del lead con PII enmascarada + reveal gobernado.
  leadPii: {
    sectionTitle: 'Datos del lead',
    sectionHint: 'La información sensible está enmascarada. Revelar un dato queda registrado.',
    loading: 'Cargando datos del lead…',
    empty: 'Este lead no tiene datos para mostrar.',
    error: 'No pudimos cargar los datos del lead. Intenta de nuevo.',
    retry: 'Reintentar',
    maskedBadge: 'Enmascarado',
    revealCta: 'Revelar',
    revealedBadge: 'Revelado',
    noCapabilityHint: 'No tienes permiso para revelar datos sensibles.',
    dialogTitle: 'Revelar dato sensible',
    dialogNotice: 'Esta acción queda registrada con tu usuario, la fecha y el motivo.',
    reasonLabel: 'Motivo del acceso',
    reasonPlaceholder: 'Ej. verificación de identidad para contrato',
    reasonHint: 'Mínimo 10 caracteres.',
    cancel: 'Cancelar',
    confirmReveal: 'Revelar dato',
    revealing: 'Revelando…',
    revealError: 'No se pudo revelar el dato. Revisa el motivo e intenta de nuevo.',
    revealedNotice: 'Dato revelado y registrado en la bitácora.',
  },
} as const
