/** Browser-safe public copy for the native Efeonce meeting scheduler. */
export const GH_GROWTH_MEETINGS_COPY = {
  regionLabel: 'Agenda una conversación con Efeonce',
  eyebrow: '30 min · Microsoft Teams',
  title: 'Conversemos sobre tu próximo desafío',
  compactTitle: 'Elige tu horario',
  intro: 'Reserva 30 minutos con nuestro equipo. Verás la disponibilidad en tu zona horaria.',
  loading: 'Buscando horarios disponibles…',
  timezoneLabel: 'Tu zona horaria',
  timezonePrefix: 'Tu zona horaria',
  timezoneNote: 'Todas las horas se muestran en la zona horaria de tu dispositivo.',
  scheduleStep: 'Fecha y hora',
  detailsStep: 'Tus datos',
  confirmationStep: 'Confirmación',
  chooseDay: 'Elige un día',
  calendarTitle: 'Elige una fecha',
  calendarRegion: 'Calendario de disponibilidad',
  availableDay: 'Disponible',
  previousMonth: 'Mes anterior',
  nextMonth: 'Mes siguiente',
  viewCalendar: 'Volver al calendario',
  calendarEyebrow: 'Disponibilidad',
  chooseTime: 'Elige una hora',
  timeRegion: 'Horarios disponibles',
  timesFor: 'Horarios del',
  chooseTimeHelp: 'La disponibilidad se confirmará al reservar.',
  selectedTime: 'Horario elegido',
  selectSlotPrompt: 'Elige una hora para continuar',
  continueWithTime: 'Continuar con',
  noSlots: 'No hay horarios disponibles en este mes.',
  nextWindow: 'Ver próximos días',
  continue: 'Continuar',
  reserve: 'Reservar horario',
  back: 'Cambiar horario',
  fallback: 'Abrir agenda alternativa',
  fallbackOnly: 'No pudimos cargar esta agenda. Puedes reservar desde nuestra agenda alternativa.',
  requiredSummary: 'Revisa los campos marcados.',
  requiredField: 'Completa este campo.',
  invalidEmail: 'Escribe un correo con formato nombre@empresa.com.',
  fieldReady: 'Listo.',
  emailHint: 'Usa tu correo de empresa; ahí recibirás la invitación.',
  verifyingEmail: 'Verificando tu correo de empresa…',
  corporateEmail: 'Ingresa un correo de empresa para continuar; no aceptamos cuentas personales.',
  disposableEmail: 'Ingresa un correo de empresa permanente; no aceptamos direcciones temporales.',
  emailVerified: 'Correo de empresa verificado.',
  consentRequired: 'Acepta el uso de tus datos para coordinar la reunión.',
  consentAccepted: 'Autorización registrada.',
  captchaRequired: 'Completa la verificación de seguridad para reservar.',
  processing: 'Reservando tu horario…',
  confirmedEyebrow: 'Reunión confirmada',
  confirmedRailStatus: 'Horario reservado',
  confirmedRailTitle: 'Todo listo',
  confirmedRailBody: 'Tu reunión quedó reservada. La invitación incluirá el enlace y las opciones para hacer cambios.',
  confirmedTitle: 'Tu reunión está confirmada',
  confirmedBody: 'Enviaremos la invitación con el enlace de Microsoft Teams a tu correo de trabajo. Puede tardar unos minutos.',
  confirmedReceiptLabel: 'Fecha y hora',
  confirmedNextTitle: 'Qué sigue',
  confirmedNextEmail: 'Revisa tu correo de trabajo. La invitación puede tardar unos minutos.',
  confirmedNextTeams: 'El enlace de Microsoft Teams estará dentro de la invitación.',
  confirmedNextChanges: 'Puedes reprogramar o cancelar desde la misma invitación.',
  confirmedHelp: 'Si no la encuentras, revisa la carpeta de spam antes de volver a reservar.',
  conflict: 'Ese horario ya no está disponible. Elige otro para continuar.',
  refreshAvailability: 'Actualizar horarios',
  genericError: 'No pudimos cargar la agenda.',
  ambiguousTitle: 'Estamos comprobando tu reserva',
  ambiguousBody: 'La reunión podría haberse creado. Revisa tu correo antes de volver a reservar para evitar una cita duplicada.',
  firstName: 'Nombre',
  lastName: 'Apellido',
  email: 'Correo de trabajo',
  company: 'Empresa',
  processingConsent: 'Acepto que Efeonce use mis datos para coordinar esta reunión.',
  meetingSummary: 'Tu horario',
  selected: 'Aún no eliges un horario.',
  availabilitySynced: 'Horarios actualizados',
  confirmationAssurance: 'Reserva registrada',
  meetingPlatform: 'Microsoft Teams',
  today: 'Hoy',
  optionSingular: 'opción',
  optionPlural: 'opciones',
  slotSingular: 'horario disponible',
  slotPlural: 'horarios disponibles',
  moreOptions: 'Más horarios disponibles',
  agendaUpdated: 'Horarios actualizados',
  morning: 'Mañana',
  afternoon: 'Tarde',
  evening: 'Noche',
} as const
