export const GH_GROWTH_FORMS = {
  navRoot: 'Growth',
  navForms: 'Forms',
  pageTitle: 'Growth Forms',
  pageSubtitle:
    'Control plane interno para formularios públicos, host surfaces, submissions, destinos y evidencia de entrega.',
  breadcrumbs: {
    admin: 'Admin Center',
    growth: 'Growth',
    forms: 'Forms',
  },
  actions: {
    createDraft: 'Crear draft',
    review: 'Enviar a review',
    publish: 'Publicar',
    deprecate: 'Deprecar',
    archive: 'Archivar',
    dispatch: 'Ejecutar dispatch',
    inspect: 'Inspeccionar',
    openComposer: 'Nuevo formulario',
    openEvidence: 'Ver evidencia',
    backToInspector: 'Volver al inspector',
    saveDraft: 'Guardar draft',
    cancel: 'Cancelar',
    refresh: 'Actualizar',
  },
  feedback: {
    ready: 'Cockpit listo. Los datos vienen del motor Growth Forms y sus readers gobernados.',
    refreshing: 'Actualizando cockpit.',
    actionQueued: 'Acción en curso. Mantén esta vista abierta hasta ver confirmación.',
  },
  aria: {
    sidecar: 'Inspector de Growth Forms',
    tableRegion: 'Lista operativa de Growth Forms',
    filterSearch: 'Buscar formularios por nombre o slug',
    selectForm: 'Seleccionar formulario',
    operationalPulse: 'Pulso operativo de Growth Forms',
  },
  fields: {
    search: 'Buscar',
    name: 'Nombre',
    slug: 'Slug',
    purpose: 'Propósito',
    formKind: 'Tipo',
    riskProfile: 'Riesgo',
  },
  table: {
    form: 'Form',
    status: 'Status',
    destinations: 'Destinos',
    surfaces: 'Surfaces',
    submissions: 'Submissions',
    lastSignal: 'Última señal',
    action: 'Acción',
  },
  units: {
    forms: 'forms',
    surfaces: 'surfaces',
    submissions: 'submissions',
    attempts: 'intentos',
    retry: 'reintentos',
    version: 'v',
    hours24: '24h',
  },
  filters: {
    all: 'All',
    ok: 'OK',
    risk: 'Risk',
  },
  formKinds: {
    lead_magnet: 'Lead magnet',
    subscribe: 'Subscribe',
    contact: 'Contact',
    diagnostic_intake: 'Diagnostic intake',
  },
  riskProfiles: {
    low: 'Low',
    medium: 'Medium',
    high: 'High',
  },
  starter: {
    defaultName: 'Lead magnet público',
    defaultSlug: 'lead-magnet-publico',
    defaultPurpose: 'Capturar interés comercial low-risk desde una surface pública gobernada.',
    emailLabel: 'Email de trabajo',
    companyLabel: 'Organización',
    interestLabel: 'Interés principal',
    interestAiVisibility: 'AI Visibility',
    interestAutomation: 'Automatización',
    interestGrowthOps: 'Growth Ops',
    consentLabel: 'Acepto ser contactado por Efeonce y entiendo el uso de mis datos para este formulario.',
    successMessage: 'Recibimos tu información. El equipo Efeonce revisará el contexto antes del siguiente paso.',
  },
  helper: {
    starterTemplate:
      'Se crea con una plantilla gobernada low-risk: email, organización, interés y consentimiento explícito.',
    noFormSelected: 'Selecciona un formulario para ver versiones, destinos, surfaces y evidencia.',
    noSubmissions: 'Aún no hay submissions para este formulario.',
    noDestinations: 'Agrega un destino antes de publicar.',
    noResults: 'No hay formularios que coincidan con este filtro.',
    rowSelection: 'Enter abre el inspector. La evidence ledger conserva consent, delivery attempts y retry state.',
    archiveWarning: 'Archivar retira el formulario del circuito operativo. Úsalo solo si ya existe reemplazo publicado.',
  },
  sections: {
    commandCenter: 'Command center',
    readiness: 'Readiness',
    destinations: 'Destinos',
    surfaces: 'Host surfaces',
    recentSubmissions: 'Submissions recientes',
    evidenceLedger: 'Evidencia de entrega',
    authoring: 'Authoring',
    smoke: 'Smoke y dispatch',
    consent: 'Consent snapshot',
    operationalPulse: 'Pulso operativo',
  },
  sidecar: {
    inspectorEyebrow: 'Inspector operacional',
    inspectorSubtitle: 'Readiness, surfaces, destinos y evidencia del formulario seleccionado.',
    composerEyebrow: 'Authoring gobernado',
    composerTitle: 'Nuevo formulario',
    composerSubtitle: 'Crea un draft low-risk con contrato, consentimiento y analítica sin valores raw.',
    evidenceEyebrow: 'Ledger de evidencia',
    evidenceTitle: 'Evidencia',
    evidenceSubtitle: 'Consent snapshot, destination attempts, retry state y señales de entrega.',
  },
  insights: {
    publishedCoverage: 'Cobertura publicada',
    deliveryHealth: 'Salud de entrega',
    migrationReadiness: 'Readiness de migración',
    governedSurfaces: 'Surfaces gobernadas',
    noDeadLetters: 'Sin dead letters activos',
    deadLettersNeedReview: 'Dead letters requieren revisión',
    retryQueueClear: 'Retry queue limpia',
    retryQueuePending: 'Retry queue pendiente',
  },
  metrics: {
    forms: 'Forms',
    published: 'Publicados',
    activeSurfaces: 'Surfaces activas',
    submissions24h: 'Submissions 24h',
    retryQueue: 'Retry queue',
    deadLetters: 'Dead letters',
  },
  statuses: {
    draft: 'Draft',
    setup: 'Setup',
    ready: 'Ready',
    healthy: 'Healthy',
    attention: 'Attention',
    dead_letter: 'Dead letter',
    active: 'Activo',
    archived: 'Archivado',
    published: 'Publicado',
    review: 'Review',
    deprecated: 'Deprecado',
    received: 'Recibido',
    validated: 'Validado',
    accepted: 'Aceptado',
    rejected: 'Rechazado',
    routed: 'Enrutado',
    delivered: 'Entregado',
    destination_failed: 'Destino falló',
    retrying: 'Reintentando',
    pending: 'Pendiente',
    succeeded: 'Exitoso',
    failed: 'Fallido',
  },
  toast: {
    draftCreated: 'Draft creado. El cockpit se actualizará con el nuevo formulario.',
    lifecycleUpdated: 'Lifecycle actualizado.',
    dispatchQueued: 'Dispatch ejecutado.',
    actionFailed: 'No se pudo completar la acción. Revisa permisos o readiness.',
  },
} as const
