/** Browser-safe public copy for the native Efeonce meeting scheduler. */
export const GH_GROWTH_MEETINGS_COPY = {
  regionLabel: 'Agenda una reunión con Efeonce',
  eyebrow: '30 minutos para avanzar',
  title: 'Reunión de descubrimiento',
  compactTitle: 'Agenda una reunión',
  intro: 'Elige un momento real de nuestra agenda. La invitación llegará a tu correo con el enlace de Teams.',
  loading: 'Sincronizando horarios disponibles…',
  timezoneLabel: 'Tu horario local',
  timezoneNote: 'Todas las horas se muestran en la zona horaria detectada en tu dispositivo.',
  scheduleStep: 'Horario',
  detailsStep: 'Tus datos',
  confirmationStep: 'Confirmación',
  chooseDay: 'Elige un día',
  calendarTitle: 'Elige una fecha',
  calendarRegion: 'Calendario de disponibilidad',
  availableDay: 'Disponible',
  previousMonth: 'Mes anterior',
  nextMonth: 'Mes siguiente',
  viewCalendar: 'Volver al calendario',
  chooseTime: 'Horarios disponibles',
  timesFor: 'Horarios para',
  chooseTimeHelp: 'Selecciona una hora para continuar.',
  selectedTime: 'Horario elegido',
  selectSlotPrompt: 'Selecciona un horario',
  continueWithTime: 'Continuar con',
  noSlots: 'No hay horarios en esta ventana.',
  nextWindow: 'Ver próximos días',
  continue: 'Continuar',
  reserve: 'Agendar reunión',
  back: 'Volver a horarios',
  fallback: 'Usar agenda HubSpot',
  fallbackOnly: 'La agenda nativa no está disponible ahora. Puedes reservar en nuestra agenda segura de HubSpot.',
  requiredSummary: 'Revisa los campos indicados antes de continuar.',
  requiredField: 'Este campo es obligatorio.',
  invalidEmail: 'Escribe un correo válido.',
  fieldReady: 'Listo.',
  emailHint: 'Usa tu correo corporativo para verificar tu empresa.',
  verifyingEmail: 'Verificando correo de trabajo…',
  corporateEmail: 'Usa el correo de tu empresa, no uno personal (ej. nombre@tuempresa.com).',
  disposableEmail: 'Los correos temporales o desechables no están permitidos.',
  emailVerified: 'Correo corporativo verificado.',
  consentRequired: 'Necesitamos tu autorización para coordinar la reunión.',
  consentAccepted: 'Autorización registrada.',
  captchaRequired: 'Completa la verificación de seguridad.',
  processing: 'Confirmando tu reunión…',
  confirmedEyebrow: 'Reunión confirmada',
  confirmedRailStatus: 'Reserva registrada',
  confirmedRailTitle: 'Reserva confirmada',
  confirmedRailBody: 'La cita quedó reservada. Conserva la invitación para unirte o hacer cambios.',
  confirmedTitle: 'Tu reunión quedó agendada',
  confirmedBody: 'La invitación con el enlace de Microsoft Teams va camino a tu correo. Puede tardar unos minutos en aparecer.',
  confirmedReceiptLabel: 'Tu cita',
  confirmedNextTitle: 'Qué sigue',
  confirmedNextEmail: 'Busca la invitación en tu correo de trabajo.',
  confirmedNextTeams: 'El enlace para unirte estará dentro de la invitación.',
  confirmedNextChanges: 'Desde ese mismo correo puedes reprogramar o cancelar.',
  confirmedHelp: 'Si no aparece de inmediato, revisa spam o espera unos minutos.',
  conflict: 'Ese horario acaba de ocuparse. Elige otro.',
  refreshAvailability: 'Actualizar horarios',
  genericError: 'La agenda no está respondiendo ahora.',
  ambiguousTitle: 'Estamos verificando tu reserva',
  ambiguousBody: 'El proveedor pudo haber creado la reunión. Revisa tu correo antes de intentar reservar nuevamente.',
  firstName: 'Nombre',
  lastName: 'Apellido',
  email: 'Correo de trabajo',
  company: 'Empresa',
  processingConsent: 'Acepto que Efeonce use estos datos para coordinar esta reunión.',
  meetingSummary: 'Resumen de tu reunión',
  selected: 'Horario seleccionado',
} as const
