export const GH_KNOWLEDGE_COPY = {
  pageTitle: 'Knowledge',
  pageSubtitle: 'Pregúntale a Nexa y revisa de dónde sale cada respuesta antes de actuar.',
  workbenchSubtitle: 'Busca guías publicadas, revisa su vigencia y deja señales para mejorar la memoria de Greenhouse.',
  workbenchSearchStatus: 'Buscando en Knowledge...',
  workbenchSearchIdle: 'Explora guías publicadas o pregunta con lenguaje natural.',
  workbenchSearchEmpty: 'No encontré una guía publicada con esos términos.',
  workbenchSearchEmptyAction: 'Prueba con otra palabra clave o reporta qué falta para que el equipo lo agregue.',
  workbenchErrorTitle: 'Knowledge no respondió',
  workbenchErrorBody: 'No pude cargar las guías publicadas. La ruta sigue disponible; intenta actualizar en unos segundos.',
  workbenchResults: 'resultados',
  workbenchLearningPaths: 'Rutas de aprendizaje',
  workbenchInspectorTitle: 'Detalle de la guía',
  workbenchWhyAppears: 'Por qué aparece',
  workbenchFreshness: 'Vigencia',
  workbenchOwner: 'Owner',
  workbenchSource: 'Fuente',
  workbenchPolicy: 'Política IA',
  workbenchRead: 'Leer guía',
  workbenchOpenNexa: 'Continuar con Nexa',
  workbenchEvidenceBridge: 'Evidencia compartida con Nexa',
  workbenchEvidenceDocumentStep: 'Guía publicada',
  workbenchEvidenceDocumentStepBody: 'Documento visible para humanos desde Knowledge.',
  workbenchEvidenceSectionStep: 'Secciones disponibles',
  workbenchEvidenceSectionStepBody: 'El inspector usa el mismo renderer de evidencia que Nexa.',
  workbenchEvidenceFeedbackStep: 'Lista para mejorar la memoria',
  workbenchEvidenceFeedbackStepBody: 'Tu señal se guarda en el contrato compartido de feedback.',
  workbenchReportMissing: 'Reportar falta',
  workbenchFeedbackSent: 'Señal enviada. Knowledge Ops la revisa en la cola de mejora.',
  workbenchFeedbackError: 'No pude enviar la señal. Intenta de nuevo.',
  workbenchModeHelper: 'Modo humano: solo muestra contenido publicado y fuentes visibles.',
  mcpModeHelper: 'Modo MCP: muestra el paquete gobernado que pueden consumir agentes.',
  workbenchModesSoon: 'Próximamente',
  commandPlaceholder: 'Pregúntale a Nexa',
  humanSearchPlaceholder: 'Buscar guías en Knowledge',
  mcpSearchPlaceholder: 'Buscar paquete para agentes',
  followUpPlaceholder: 'Haz otra pregunta a Nexa',
  selectedQuestion: '¿Cómo reviso mis métricas ICO personales y qué significan?',
  sendQuestion: 'Preguntar',
  sendFeedback: 'Reportar mejora',
  export: 'Exportar',
  responseTitle: 'Respuesta de Nexa',
  assistantName: 'Nexa',
  responseThinkingLabel: 'Nexa está refinando la respuesta',
  sourcesLabel: 'Fuentes',
  proofTitle: 'Fuentes y trazabilidad',
  agentTitle: 'Para agentes',
  mcpLensTitle: 'Paquete para agentes',
  mcpLensSubtitle: 'MCP y agentes consumen el mismo corpus gobernado, sin fragmentos restringidos.',
  mcpLensEmptyTitle: 'Busca o selecciona una guía',
  mcpLensEmptyBody: 'El paquete MCP aparece cuando hay una fuente publicada o una búsqueda con evidencia real.',
  mcpResourceUri: 'Resource URI',
  mcpEvidencePacket: 'Paquete de evidencia',
  mcpContractVersion: 'Contrato',
  mcpNoMock: 'Sin mock: este panel solo muestra evidencia que viene del contrato real.',
  lensSwitcherTitle: 'Lente de Knowledge',
  lensSwitcherBody: 'Cambia entre exploración humana, respuesta de Nexa y paquete para agentes.',
  breadcrumbRoot: 'Greenhouse',
  breadcrumbCurrent: 'Knowledge',
  manualTitle: 'Manual: Cómo usar Mi Desempeño',
  openDocument: 'Abrir documento',
  copyUri: 'Copiar URI',
  viewFullPacket: 'Ver packet completo',
  agentDisclosure: 'Los agentes usan el mismo corpus gobernado que las personas. Los fragmentos restringidos no llegan al modelo.',
  answer:
    'Para revisar tus métricas ICO personales, entra a Mi Desempeño desde el menú principal. Ahí puedes ver tus indicadores por objetivo, colaborar con tu líder y dar seguimiento a tu crecimiento.',
  currentModeHelper: {
    human: 'Respuesta para personas: explicación accionable y fuentes visibles.',
    nexa: 'Respuesta de Nexa: muestra cómo se apoyó en Knowledge.',
    mcp: 'Vista técnica: expone el paquete que consumen agentes y MCP.'
  },
  operationalDataWarning: 'No consulté datos actuales',
  operationalDataWarningBody: 'Esta respuesta usa guías publicadas. Para ver tu estado real, consulta tus datos de desempeño.',
  openManual: 'Abrir manual',
  saveGuide: 'Guardar como guía',
  reportGap: 'Reportar falta',
  consultData: 'Consultar mis datos',
  feedbackQuestion: '¿Te fue útil este contenido?',
  feedbackIntro: 'Marca una señal y agrega contexto si falta una fuente o algo está desactualizado.',
  feedbackUseful: 'Útil',
  feedbackNotUseful: 'No tan útil',
  feedbackIncorrect: 'Incorrecto',
  feedbackPlaceholder: 'Comentario breve (opcional)',
  feedbackCommentLabel: 'Comentario de feedback',
  feedbackSubmit: 'Reportar mejora',
  feedbackRegisteredShort: 'Mejora reportada',
  feedbackRegistered: 'Feedback registrado. Lo usamos para mejorar la guía y las respuestas de Nexa.',
  copiedUri: 'URI copiada',
  aria: {
    completedStep: 'Paso completado',
    alignedSource: 'Fuente alineada',
    documentHealthOk: 'Documento validado',
    modeSelector: 'Modo de respuesta',
    selectedQuestion: 'Pregunta seleccionada',
    activeMode: 'Modo activo',
    proofTabs: 'Prueba y trazabilidad',
    feedbackSelector: 'Feedback de contenido',
    searchKnowledge: 'Buscar en Knowledge',
    openNexaFromKnowledge: 'Abrir Nexa con contexto de Knowledge'
  },
  evidenceTabs: {
    sources: 'Fuentes',
    trace: 'Cómo llegó',
    packet: 'Paquete',
    evals: 'Revisión'
  },
  mode: {
    human: 'Humano',
    nexa: 'Nexa',
    mcp: 'MCP'
  }
} as const
