export const GH_KNOWLEDGE_COPY = {
  pageTitle: 'Knowledge',
  pageSubtitle: 'Pregúntale a Nexa y revisa de dónde sale cada respuesta antes de actuar.',
  commandPlaceholder: 'Pregúntale a Nexa',
  followUpPlaceholder: 'Haz otra pregunta a Nexa',
  selectedQuestion: '¿Cómo reviso mis métricas ICO personales y qué significan?',
  sendQuestion: 'Preguntar',
  sendFeedback: 'Reportar mejora',
  export: 'Exportar',
  responseTitle: 'Respuesta de Nexa',
  assistantName: 'Nexa',
  responseThinkingLabel: 'Nexa está refinando la respuesta',
  sourcesLabel: 'Fuentes',
  proofTitle: 'Fuentes y trazabilidad',
  agentTitle: 'Para agentes',
  breadcrumbRoot: 'Greenhouse',
  breadcrumbCurrent: 'Knowledge',
  manualTitle: 'Manual: Cómo usar Mi Desempeño',
  openDocument: 'Abrir documento',
  copyUri: 'Copiar URI',
  viewFullPacket: 'Ver packet completo',
  agentDisclosure: 'Los agentes usan el mismo corpus gobernado que las personas. Los fragmentos restringidos no llegan al modelo.',
  answer:
    'Para revisar tus métricas ICO personales, entra a Mi Desempeño desde el menú principal. Ahí puedes ver tus indicadores por objetivo, colaborar con tu líder y dar seguimiento a tu crecimiento.',
  currentModeHelper: {
    human: 'Respuesta para personas: explicación accionable y fuentes visibles.',
    nexa: 'Respuesta de Nexa: muestra cómo se apoyó en Knowledge.',
    mcp: 'Vista técnica: expone el paquete que consumen agentes y MCP.'
  },
  operationalDataWarning: 'No consulté datos actuales',
  operationalDataWarningBody: 'Esta respuesta usa guías publicadas. Para ver tu estado real, consulta tus datos de desempeño.',
  openManual: 'Abrir manual',
  saveGuide: 'Guardar como guía',
  reportGap: 'Reportar falta',
  consultData: 'Consultar mis datos',
  feedbackQuestion: '¿Te fue útil este contenido?',
  feedbackIntro: 'Marca una señal y agrega contexto si falta una fuente o algo está desactualizado.',
  feedbackUseful: 'Útil',
  feedbackNotUseful: 'No tan útil',
  feedbackIncorrect: 'Incorrecto',
  feedbackPlaceholder: 'Comentario breve (opcional)',
  feedbackCommentLabel: 'Comentario de feedback',
  feedbackSubmit: 'Reportar mejora',
  feedbackRegisteredShort: 'Mejora reportada',
  feedbackRegistered: 'Feedback registrado. Lo usamos para mejorar la guía y las respuestas de Nexa.',
  copiedUri: 'URI copiada',
  aria: {
    completedStep: 'Paso completado',
    alignedSource: 'Fuente alineada',
    documentHealthOk: 'Documento validado',
    modeSelector: 'Modo de respuesta',
    selectedQuestion: 'Pregunta seleccionada',
    activeMode: 'Modo activo',
    proofTabs: 'Prueba y trazabilidad',
    feedbackSelector: 'Feedback de contenido'
  },
  evidenceTabs: {
    sources: 'Fuentes',
    trace: 'Cómo llegó',
    packet: 'Paquete',
    evals: 'Revisión'
  },
  mode: {
    human: 'Humano',
    nexa: 'Nexa',
    mcp: 'MCP'
  }
} as const
