/**
 * TASK-960 — Contractor Remittance Advice ("Comprobante de Pago") copy.
 *
 * Domain-specific, BILINGUAL copy module (es-CL + en-US). Lives here per the
 * canonical decision tree: domain copy → `src/lib/copy/<domain>.ts` (mirror of
 * `agency.ts` / `payroll.ts`), NOT the shared MicrocopyDictionary namespace union
 * (which is reserved for cross-surface functional microcopy). Bilingual because the
 * document follows the CONTRACTOR's locale (mirror of `src/lib/email/locale-resolver.ts`).
 *
 * The strings are the APPROVED mockup copy (operator 2026-05-31); this module only
 * relocates them from `mockup/remittance-data.ts` so the runtime presenter consumes
 * the same source. Pure data (client + server safe).
 */

export type RemittanceLocale = 'es-CL' | 'en-US'

export type RemittanceRegime =
  | 'honorarios_cl'
  | 'international_withholding'
  | 'provider_managed'
  | 'cross_currency'

/** Provider tax-document kind (the contractor's own document — BHE in CL, invoice abroad). */
export type RemittanceProviderDocKind = 'bhe' | 'invoice'

export interface RemittanceCopy {
  title: string
  numberLabel: string
  issuerSection: string
  beneficiarySection: string
  providerDocSection: string
  breakdownSection: string
  paymentSection: string
  footerNote: string
  issuerTaxIdLabel: string
  beneficiaryTaxIdLabel: string
  countryLabel: string
  paymentDateLabel: string
  methodLabel: string
  methodValue: string
  referenceLabel: string
  grossLabel: string
  withholdingSiiLabel: (ratePct: string) => string
  withholdingGenericLabel: string
  withholdingManagedNote: string
  netLabel: string
  fxLabel: (rate: string, equivalent: string) => string
  disclaimer: string
  unavailableValue: string
  regimeLabels: Record<RemittanceRegime, string>
  providerDocKind: Record<RemittanceProviderDocKind, string>
}

const REMITTANCE_COPY: Record<RemittanceLocale, RemittanceCopy> = {
  'es-CL': {
    title: 'Comprobante de Pago',
    numberLabel: 'N°',
    issuerSection: 'Emisor',
    beneficiarySection: 'Beneficiario',
    providerDocSection: 'Documento del prestador',
    breakdownSection: 'Detalle del pago',
    paymentSection: 'Datos del pago',
    footerNote:
      'Documento generado por Greenhouse. No es un documento tributario; el documento tributario es el emitido por el prestador.',
    issuerTaxIdLabel: 'RUT',
    beneficiaryTaxIdLabel: 'Identificación',
    countryLabel: 'País',
    paymentDateLabel: 'Fecha de pago',
    methodLabel: 'Medio de pago',
    methodValue: 'Transferencia bancaria',
    referenceLabel: 'Referencia',
    grossLabel: 'Monto bruto (servicios)',
    withholdingSiiLabel: ratePct => `Retención SII (${ratePct})`,
    withholdingGenericLabel: 'Retención',
    withholdingManagedNote: 'Retención gestionada por el proveedor / país de residencia',
    netLabel: 'Neto pagado',
    fxLabel: (rate, equivalent) => `Tipo de cambio aplicado: 1 USD = ${rate} CLP · Equivalente: ${equivalent}`,
    disclaimer:
      'Pago por prestación de servicios profesionales. No constituye remuneración ni vínculo de subordinación o dependencia.',
    unavailableValue: '—',
    regimeLabels: {
      honorarios_cl: 'Honorarios Chile',
      international_withholding: 'Internacional',
      provider_managed: 'Vía proveedor',
      cross_currency: 'Internacional (FX)'
    },
    providerDocKind: { bhe: 'Boleta de Honorarios', invoice: 'Invoice' }
  },
  'en-US': {
    title: 'Remittance Advice',
    numberLabel: 'No.',
    issuerSection: 'Issuer',
    beneficiarySection: 'Payee',
    providerDocSection: 'Provider document',
    breakdownSection: 'Payment breakdown',
    paymentSection: 'Payment details',
    footerNote:
      'Document generated by Greenhouse. This is not a tax document; the tax document is the one issued by the provider.',
    issuerTaxIdLabel: 'Tax ID',
    beneficiaryTaxIdLabel: 'Tax ID',
    countryLabel: 'Country',
    paymentDateLabel: 'Payment date',
    methodLabel: 'Payment method',
    methodValue: 'Bank transfer',
    referenceLabel: 'Reference',
    grossLabel: 'Gross amount (services)',
    withholdingSiiLabel: ratePct => `SII withholding (${ratePct})`,
    withholdingGenericLabel: 'Withholding',
    withholdingManagedNote: 'Withholding managed by the provider / country of residence',
    netLabel: 'Net paid',
    fxLabel: (rate, equivalent) => `Exchange rate applied: 1 USD = ${rate} CLP · Equivalent: ${equivalent}`,
    disclaimer:
      'Payment for professional services rendered. This is not remuneration and does not constitute an employment or subordination relationship.',
    unavailableValue: '—',
    regimeLabels: {
      honorarios_cl: 'Chile professional services',
      international_withholding: 'International',
      provider_managed: 'Provider-managed',
      cross_currency: 'International (FX)'
    },
    providerDocKind: { bhe: 'Professional services receipt (BHE)', invoice: 'Invoice' }
  }
}

export const getRemittanceCopy = (locale: RemittanceLocale): RemittanceCopy => REMITTANCE_COPY[locale]
