export const GH_WORKFORCE_CONTRACTING = {
  productName: 'Workforce Contracting',
  studioName: 'Workforce Contracting Studio',
  mockupTitle: 'Workforce Contracting',
  commandCenter: 'Centro operativo',
  guidedBuilder: 'Flujo guiado',
  bilingualReview: 'Revisión bilingüe',
  collaboratorViewer: 'Portal colaborador',
  requiredLanguages: 'ES + EN obligatorios',
  authoritativeSpanish: 'Español legal prevalente',
  aiGuardrail: 'Claude redacta, Greenhouse valida',
  createDocument: 'Nueva carta o contrato',
  approveBilingualDraft: 'Aprobar borrador bilingüe',
  reviewBilingualDraft: 'Revisar borrador bilingüe',
  generateBilingualDraft: 'Generar borrador bilingüe',
  requestChanges: 'Solicitar cambios',
  compare: 'Comparar',
  showSources: 'Mostrar fuentes',
  previousIssue: 'Hallazgo anterior',
  nextIssue: 'Siguiente hallazgo',
  generatePdf: 'Generar PDF',
  readyForSignature: 'Listo para firma',
  pendingSignature: 'Firma pendiente',
  blockedByData: 'Bloqueado por datos',
  parityOk: 'Paridad OK',
  parityWarning: 'Atención',
  parityBlocked: 'Bloqueante',
  aria: {
    prototypeMode: 'Modo del prototipo Workforce Contracting',
    legalReadinessProgress: 'Progreso de validación legal',
    commandQueueTable: 'Tabla de casos de Workforce Contracting',
    bilingualReviewTable: 'Tabla de revisión bilingüe de contrato'
  }
} as const
