// Merch con IA generativa (2026-09-25). Método: el arte plano de la lámina es la composición exacta;
// el modelo sólo pone material y luz. En prendas, el kit real de Efeonce es la referencia de forma y tela.
// node items.mjs [id,id]  → corre pnpm ai:image por ítem (Sunburst xhigh), 3 en paralelo.
import {spawn} from 'node:child_process';import {writeFileSync,existsSync} from 'node:fs';import {dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';
const D=dirname(fileURLToPath(import.meta.url)),K='/Users/jreye/Documents/greenhouse-eo/ai-generations';
const A=f=>join(D,'arte',f+'.png');
const BASE=`Keep every graphic element exactly as drawn in the artwork images: the same words with the same spelling, the small solid sphere placed right after each word (it is a period, not a letter), the thin ring and the arc with a dot at its tip, and the Efeonce logo. Do not redraw, restyle, translate, move or add any text, logo, icon or mark; no extra words anywhere. Colors stay as in the artwork: deep navy #001A33, teal #36C8BF, white. Photorealistic studio product photograph, seamless light grey background (#E6E9EB), soft key light from the upper left, gentle fill, natural contact shadows, crisp focus on the graphics, no people, no hands, no props that are not described.`;
export const ITEMS=[
 {id:'lapiceros',size:'1536x1024',img:[A('mc_lapiceros')],p:`Image 1 is the final artwork of three Efeonce ballpoint pens. Photograph three real pens made of matte soft-touch plastic with a metal clip and a glossy round push button on top: the button is the colored sphere of each pen (teal, teal, orange). The pens lie parallel and slightly diagonal on the surface, top-down three-quarter angle. The printed word and logo on each barrel match the artwork exactly. Omit the caption text under the pens.`},
 {id:'pulseras',size:'1536x1024',img:[A('mc_pulseras')],p:`Image 1 is the final artwork of five silicone wristbands (navy, white, orange, blue, red-orange). Photograph five real debossed-and-printed silicone wristbands lying in a gentle row, slightly overlapping, three-quarter top view. Each band shows its single word followed by a small dot, printed in white or navy as in the artwork. Omit the caption text under the bands.`},
 {id:'mousepad',size:'1536x1024',img:[A('mc_mousepad')],p:`Image 1 is the final artwork of a 90 × 40 cm desk mat. Photograph the real desk mat: stitched edges, soft fabric top, dye-sublimated print, lying on a light oak desk, seen from a low three-quarter angle. The word, the orbit on the right and the small logo in the corner match the artwork. Omit the caption text under the mat.`},
 {id:'polo',size:'1024x1024',img:[A('mc_polo'),`${K}/2026-09-17_polo-efeonce/final/efeonce-polo-navy-01-frente-1600x1600-v01-fondo-estudio.png`],p:`Image 1 is the final artwork of an Efeonce navy polo shirt edition. Image 2 is the REAL Efeonce navy polo: copy its cut, piqué fabric, collar, placket and proportions exactly. Apply the edition from image 1: the top placket button is a teal round button (the sphere) and "Hacer." is embroidered in white satin stitch on the left chest (wearer's left), small. Remove any other chest emblem so only "Hacer." appears on the chest. Front view, laid on an invisible mannequin.`},
 {id:'polera',size:'1024x1024',img:[A('mc_poleraNavy'),`${K}/2026-09-17_polo-efeonce/final/efeonce-polo-navy-01-frente-1600x1600-v01-fondo-estudio.png`],p:`Image 1 is the final artwork of a navy cotton T-shirt. Image 2 is a real Efeonce garment, use it only for the navy color, fabric quality and studio look (it is a polo; the product here is a crew-neck T-shirt without collar or buttons). Screen-print on the chest exactly as in image 1: a thin ring with a teal arc and dot, and "Hacer." in white inside it. Front view on an invisible mannequin.`},
 {id:'gorra',size:'1024x1024',img:[A('mc_gorra'),`${K}/2026-09-17_gorra-efeonce/final/efeonce-gorra-v3-navy-isotipo-1600x1600-v01-fondo-estudio.png`],p:`Image 1 is the final artwork of an Efeonce cap. Image 2 is the REAL Efeonce navy cap: copy its six-panel shape, curved brim, fabric and stitching exactly. Apply the edition from image 1: "Hacer." embroidered in white satin stitch on the front panels (replacing the emblem of image 2), and the button on top of the crown is teal (the sphere). Three-quarter front view.`},
 {id:'carnet',size:'1024x1536',img:[A('mc_carnet'),`${K}/2026-09-17_lanyard-efeonce/final/efeonce-lanyard-10-portacarnet-vacio-1200x1600-v01-fondo-estudio.png`],p:`Image 1 is the final printed face of an Efeonce employee ID card. Image 2 is the REAL Efeonce card holder and lanyard hardware: copy it exactly. Close-up product shot: the card from image 1 inside that holder fills about 70% of the frame height, only the top clip and the first centimeters of the lanyard strap are visible, straight-on and slightly tilted; the portrait photo, name "Julio Reyes.", title "Managing & GTM Director", slogan and logo exactly as printed in image 1.`},
 {id:'credencial-staff',size:'1024x1536',img:[A('mc_evento-Staff')],p:`Image 1 is the final printed face of an event badge (staff). Photograph it as a real printed badge on thick matte card inside a clear soft PVC sleeve, hanging from a plain navy lanyard clip at the top, straight-on view. All text and placeholders in brackets stay exactly as in image 1.`},
 {id:'tarjetas',size:'1536x1024',img:[A('mc_tarjeta'),A('mc_tarjetaRev')],p:`Image 1 is the front and image 2 the back of an Efeonce business card (85 × 55 mm, 600 g uncoated card). Photograph two real cards on the surface: one showing the front (image 1) lying flat, the other showing the back (image 2) resting at an angle on top of it, subtle paper texture and crisp edges, three-quarter top view. Name, title, phone, email, slogan and logos exactly as in the artwork.`},
 {id:'pin',size:'1024x1024',img:[A('mc_pin')],p:`Image 1 is the final artwork of a round enamel pin. Photograph a real hard-enamel pin, 25 mm, polished silver metal lines, navy enamel field, the ring in silver and the arc and dot in teal enamel, butterfly clutch not visible, lying on the surface at a slight angle, macro product shot.`},
 {id:'caja-tapa',size:'1536x1024',img:[A('bv_tapa')],p:`Image 1 is the final artwork of the lid of an Efeonce welcome box. Photograph the real closed rigid gift box: matte navy soft-touch paper wrap, lid printed exactly like image 1, the small logo on the front edge of the lid, three-quarter view from above.`},
 {id:'caja-abierta',size:'1536x1024',img:[A('bv_abierta')],p:`Image 1 is the final artwork of an Efeonce welcome box, opened, seen from above: the inside of the lid on top and the tray with six compartments below. Photograph the real open box top-down: rigid box, navy lid interior printed exactly as image 1 with "Esto es tuyo." and "[Nombre].", white foam tray holding real objects matching each compartment: a navy steel sports bottle lying down, a white ID card, a keyring with a teal bead and navy tag, a folded navy polo shirt, a navy pen with teal top button, a white welcome card. Omit the small caption labels of the compartments.`},
 {id:'envio',size:'1536x1024',img:[A('bv_envioDentro'),A('bv_envioFuera')],p:`Image 1 is the inside and image 2 the outside of an Efeonce mailer box for sending merch to clients. Photograph the real corrugated mailer box open, three-quarter view: the inside of the lid is navy printed with "Gracias." and the orbit exactly as image 1; inside, light grey tissue paper folded and closed with a round teal sticker (the sphere). The outside of the box is off-white with the small logo and the thin ring as in image 2. Omit the caption text in image 1.`},
 {id:'papeleria',size:'1536x1024',img:[A('pp_carta'),A('pp_sobre'),A('pp_sobreDorso')],p:`Image 1 is an A4 letterhead page, image 2 the front and image 3 the back of a DL envelope, all Efeonce. Photograph a real stationery flat lay on the surface: the letterhead sheet printed exactly as image 1, the envelope showing its front (image 2) and a second envelope showing its back with the flap closed by a round teal sticker (image 3). Uncoated premium white paper, top-down view, soft shadows. Omit the caption text in image 3. The web address in the letterhead footer is the small grey outlined speech-bubble pill with "efeoncepro.com" from image 1, copied exactly, never as plain text. The slogan "Empower your Growth" in the footer has NO period and no dot after it; the teal dot belongs only to the end of the thin divider line above it.`},
 {id:'llavero',size:'1024x1024',img:[A('pp_llavero'),A('pp_llaveroRev')],p:`Image 1 is the front and image 2 the back of an Efeonce keychain. Photograph two real keychains: brushed steel split ring with a glossy teal bead on the ring (the sphere), and a navy enamel-coated metal tag with a punched hole; one shows the front "Adelante." (image 1), the other the back with the logo (image 2). Lying on the surface, macro product shot.`},
 {id:'stand',size:'1536x1024',img:[A('ev_telon'),A('ev_pendon'),A('ev_meson')],p:`Image 1 is the 3 × 2.4 m fabric backdrop, image 2 the 85 × 200 cm roll-up banner and image 3 the front of the 100 × 90 cm counter of an Efeonce trade-fair stand. Photograph the real assembled stand at an expo, front view: the backdrop printed exactly as image 1 on tension fabric, the roll-up banner standing on the left printed as image 2, the counter on the right with a white top printed as image 3 (it must not cover the word "Aquí."). Grey carpet, neutral expo hall lighting, empty aisle, no people. Omit the small caption text in image 2. The web address appears only as the outlined speech-bubble pill with "efeoncepro.com" from the artwork, copied exactly with its soft luminosity tone (it takes the hue of the fabric behind it), never as plain text.`},
 {id:'paraguas',size:'1024x1024',img:[A('ev_paraguas')],p:`Image 1 is the artwork of an Efeonce event umbrella seen from above (8 panels). Photograph the real open golf umbrella from a high angle, navy canopy fabric with the orbit and "Siempre." printed exactly as image 1, silver tip at the center, standing on light grey studio floor.`},
];
const only=process.argv[2]?.split(',');const todo=ITEMS.filter(i=>!only||only.includes(i.id));
let active=0,idx=0;const run=it=>new Promise(res=>{const pf=join(D,'prompts',it.id+'.txt');writeFileSync(pf,it.p+'\n\n'+BASE);
 const args=['ai:image','--prompt-file',pf,...it.img.flatMap(i=>['--image',i]),'--model','gpt-image-2.5-sunburst','--quality','xhigh','--size',it.size,'--out',join(D,'out',it.id+'.png')];
 const c=spawn('pnpm',args,{cwd:'/Users/jreye/Documents/greenhouse-eo',stdio:['ignore','pipe','pipe']});let o='';c.stdout.on('data',d=>o+=d);c.stderr.on('data',d=>o+=d);c.on('close',code=>{console.log(`[${it.id}] exit ${code}\n`+o.split('\n').filter(l=>/USD|error|Error|saved|→|wrote/i.test(l)).slice(-4).join('\n'));res();});});
const next=async()=>{while(idx<todo.length){const it=todo[idx++];await run(it);}};await Promise.all([next(),next(),next()]);
