import 'server-only'

/**
 * PdfTokens — sistema de tokens visuales para el PDF de cotizaciones.
 *
 * Equivale paralelamente a `docs/architecture/GREENHOUSE_DESIGN_TOKENS_V1.md`,
 * pero traducido al modelo de `@react-pdf/renderer` (StyleSheet) que NO soporta
 * CSS variables, oklch(), container queries ni unidades modernas.
 *
 * Source visual: `docs/research/mockups/quote-pdf-full-mockup.html` (TASK-629).
 *
 * Cualquier cambio aquí debe reflejarse 1:1 en el mockup HTML para mantener
 * la coherencia entre artefacto de iteracion y produccion.
 */

export const PdfColors = {
  primary: '#023c70',          // Efeonce navy — backbone
  accent: '#0375db',           // Efeonce blue — accent + links
  text: '#2F2B3D',             // Body text
  textMuted: '#6E6B7B',        // Metadata, helpers
  textSubtle: '#A5A3AE',       // Tertiary
  surface: '#F8F7FA',          // Card backgrounds
  divider: '#E4E5EB',          // Borders
  paper: '#FFFFFF',            // Page background
  paperOnPrimary: 'rgba(255,255,255,0.7)',
  success: '#6ec207',
  warning: '#ff6500',

  // Sub-brand accents — siempre se acompañan del isotipo, nunca standalone
  subBrand: {
    globe: '#bb1954',
    wave: '#00BAD1',
    reach: '#ff6500',
    efeonce: '#023c70'
  }
} as const

export type SubBrandCode = 'globe' | 'wave' | 'reach' | 'efeonce'

/**
 * Font family names — cada peso registrado como familia independiente en
 * `register-fonts.ts`. Componentes referencian por nombre directo según
 * la intención visual (no necesitan pasar fontWeight).
 *
 * Fallback implícito: si una familia no carga (archivo faltante, I/O error),
 * React-PDF cae a Helvetica automáticamente sin romper el render.
 */
export const PdfFonts = {
  heading: 'Poppins',              // 600 SemiBold — section titles, KPIs
  headingBold: 'Poppins Bold',     // 700 — hero, big numbers
  headingMedium: 'Poppins Medium', // 500 — card titles
  body: 'DM Sans',                 // 400 — body copy
  bodyMedium: 'DM Sans Medium',    // 500 — overlines, eyebrows, labels
  bodyBold: 'DM Sans Bold'         // 700 — bold runs inline
} as const

export const PdfSpacing = {
  // Escala 4n pt — equivalente a la del portal traducida a pt
  s1: 4,
  s2: 8,
  s3: 12,
  s4: 16,
  s5: 20,
  s6: 24,
  s8: 32,
  s10: 40,
  s12: 48
} as const

export const PdfRadii = {
  sm: 4,
  md: 6,
  lg: 8
} as const

export const PdfTypography = {
  eyebrow: { fontFamily: PdfFonts.bodyMedium, fontSize: 7, letterSpacing: 1.2 },
  eyebrowAccent: { fontFamily: PdfFonts.bodyMedium, fontSize: 8, letterSpacing: 2 },
  hero: { fontFamily: PdfFonts.heading, fontSize: 36, letterSpacing: -0.5 },
  sectionTitle: { fontFamily: PdfFonts.heading, fontSize: 22, letterSpacing: -0.3 },
  cardTitle: { fontFamily: PdfFonts.heading, fontSize: 14 },
  bundleTitle: { fontFamily: PdfFonts.heading, fontSize: 12 },
  bodyLarge: { fontFamily: PdfFonts.body, fontSize: 11 },
  body: { fontFamily: PdfFonts.body, fontSize: 10 },
  bodySmall: { fontFamily: PdfFonts.body, fontSize: 9 },
  bodyDense: { fontFamily: PdfFonts.body, fontSize: 8.5 },
  caption: { fontFamily: PdfFonts.body, fontSize: 8 },
  metadata: { fontFamily: PdfFonts.body, fontSize: 7 },
  metricLarge: { fontFamily: PdfFonts.heading, fontSize: 22 },
  metricMid: { fontFamily: PdfFonts.heading, fontSize: 16 },
  metricSmall: { fontFamily: PdfFonts.heading, fontSize: 14 }
} as const

export const PdfPage = {
  width: 595,                // A4 width
  height: 842,               // A4 height
  paddingX: 48,
  paddingY: 56,
  paddingBottom: 72          // espacio para footer fijo
} as const

/**
 * Mapping sub-brand code → asset path (relative to public/) + display label.
 * Path se consume desde `process.cwd() + '/public/' + path`.
 */
/**
 * Sub-brand asset paths point to the PNG variants generated by
 * `scripts/build-pdf-brand-assets.ts`. React-PDF's <Image> only supports
 * PNG/JPG, so SVGs are rasterized at build time into `public/branding/pdf/`.
 *
 * Re-run the script when the canonical SVG sub-brand logos change.
 */
export const SUB_BRAND_ASSETS: Record<SubBrandCode, {
  isotipoPath: string
  fullLogoPath: string
  label: string
  color: string
}> = {
  efeonce: {
    isotipoPath: 'branding/pdf/isotipo-efeonce.png',
    fullLogoPath: 'branding/logo-full.png',
    label: 'Efeonce',
    color: PdfColors.subBrand.efeonce
  },
  globe: {
    isotipoPath: 'branding/pdf/isotipo-globe.png',
    fullLogoPath: 'branding/pdf/globe-full.png',
    label: 'Globe',
    color: PdfColors.subBrand.globe
  },
  wave: {
    isotipoPath: 'branding/pdf/isotipo-wave.png',
    fullLogoPath: 'branding/pdf/wave-full.png',
    label: 'Wave',
    color: PdfColors.subBrand.wave
  },
  reach: {
    isotipoPath: 'branding/pdf/isotipo-reach.png',
    fullLogoPath: 'branding/pdf/reach-full.png',
    label: 'Reach',
    color: PdfColors.subBrand.reach
  }
}

/**
 * Default emisor legal — sirve como fallback cuando la query a
 * greenhouse_core.organizations falla o aun no esta poblada.
 * Decision 7 (RESEARCH-005 v1.3): se prefiere lectura dinamica, este es safety net.
 */
export const DEFAULT_LEGAL_ENTITY = {
  legalName: 'Efeonce Group SpA',
  taxId: '77.357.182-1',
  address: 'Dr. Manuel Barros Borgoño 71 of. 05, Providencia, Santiago, Chile',
  website: 'efeoncepro.com'
} as const
