import json
from pathlib import Path
r=Path(__file__).parent
runs=[];captures=[]
for p in sorted(r.glob('*.json')):
 if p.name.endswith('-request.json') or p.name in ['demand-inputs.json','serp-observations.json','source-ledger.json']:continue
 d=json.loads(p.read_text())
 if 'response' not in d:continue
 runs.append({'id':p.stem,'file':p.name,'captured_at':d['queriedAt'],'cost_usd':d['response']['costUsd'],'outcome':d['outcome'],'endpoint':d['request']['endpoint']['path'],'consumer':d['request'].get('consumer'),'attribution':'Efeonce acquisition' if d['request'].get('organizationId') else 'public prospect SERP; no client organization','status_codes':d['response']['taskCodes']})
 if not p.name.startswith('serp-'):continue
 for t in d['response']['tasks']:
  for v in t.get('result') or []:
   organic=[x for x in v.get('items') or [] if x.get('type')=='organic']
   full=t['status_code']==20000 and not (t.get('data') or {}).get('target')
   captures.append({'id':f'SERP-{len(captures)+1:02}','source_file':p.name,'task_id':t['id'],'query':v['keyword'],'captured_at':v.get('datetime') or d['queriedAt'],'market':'PE','location_code':2604,'language':'es','device':d['request']['tasks'][0].get('device'),'depth_requested':20,'status_code':t['status_code'],'target_filter':(t.get('data') or {}).get('target'),'capture_state':'available_full_serp' if full else 'provider_no_results_no_usable_rank_data','pibank_best_organic_rank':min([x['rank_group'] for x in organic if x.get('domain','').removeprefix('www.')=='pibank.pe'],default=None),'pibank_rank_state':'observed' if any(x.get('domain','').removeprefix('www.')=='pibank.pe' for x in organic) else ('not_observed_in_requested_depth' if full else 'unknown_provider_no_results'),'organic_rows':[{'rank_group':x['rank_group'],'rank_absolute':x.get('rank_absolute'),'domain':x.get('domain'),'url':x.get('url'),'title':x.get('title')} for x in organic]})
sources=[
{'id':'WEB-PIBANK-PRODUCT','url':'https://pibank.pe/cuenta-soles-pibank/','type':'official_product','as_of':'2026-10-06','facts':['Cuenta Soles:5%TREA published, first sol, no minimum/maintenance','Savings-only, no debit/payment methods; digital web opening with registro.pibank.pe','Calculator and FAQ already present; legal documents linked'],'limitation':'Product conditions must revalidate at delivery; not channel baseline or financial advice'},
{'id':'WEB-PIBANK-ENTITY','url':'https://pibank.pe/quienes-somos/','type':'official_entity','as_of':'2026-10-06','facts':['Pibank belongs to Banco Pichincha Peru','Model born Spain2018, presence Colombia/US'],'limitation':'International model is not Peru conversion/traffic benchmark'},
{'id':'WEB-INTERBANK','url':'https://interbank.pe/cuentas/cuentas-ahorro/cuenta-super-tasa','type':'official_product','as_of':'2026-10-06','facts':['Soles opening from S/10000; tiered rates up to4.5%','Published table S/10000-29999.99 rate0.5%; maximum from S/200000','Maintenance waiver tied to average balance; online opening'],'limitation':'Page table/conditions, not a current financial recommendation; check tariff before comparative client copy'},
{'id':'WEB-SCOTIA','url':'https://www.scotiabank.com.pe/Personas/ahorros/default?cliente=false','type':'official_product_list','as_of':'2026-10-06','facts':['Lists accounts and advertises up to4.60%TREA soles for Cuenta Power'],'limitation':'Maximum headline; no claim equivalent ticket or eligibility without tariff'},
{'id':'WEB-BCP','url':'https://www.viabcp.com/abrir-cuenta','type':'official_product_comparison','as_of':'2026-10-06','facts':['Multiple accounts by use; Premio lists rate soles0.25%-1.00%','Some transactional accounts state no interest'],'limitation':'Do not generalize one account conditions to BCP entire portfolio'},
{'id':'WEB-FALABELLA','url':'https://www.bancofalabella.pe/cuentas','type':'official_product_list','as_of':'2026-10-06','facts':['Savings and transactional products with different conditions'],'limitation':'Promotional headlines/time windows need specific current tariff; excluded expired August promotion from rate comparison'},
{'id':'WEB-EFECTIBANK','url':'https://www.efectibank.pe/ahorros/cuenta-de-ahorros/','type':'official_product','as_of':'2026-10-06','facts':['Digital savings account lists4.5%TREA soles, no minimum/maintenance','App opening and debit/payment functionality'],'limitation':'Efectiva brand terms in keywords retained; current official identity Efectibank; no historic transfer of conversion'}]
(r/'serp-observations.json').write_text(json.dumps({'schema_version':1,'as_of':'2026-10-06','captures':captures,'limitations':['Full SERP only status20000 with no target filtering','No Results40102 retained as no usable rank data, not evidence of rank0 or no index','No share-of-market, unique users or conversion metrics']},ensure_ascii=False,indent=2)+'\n')
(r/'source-ledger.json').write_text(json.dumps({'schema_version':1,'as_of':'2026-10-06','dataforseo_cost_usd':round(sum(x['cost_usd'] or 0 for x in runs),5),'runs':runs,'public_primary_sources':sources,'entitlement_evidence':'All Labs paid requests passed canonical enforceSeoRunEntitlement before provider; acquisition org EO-ORG-0007 from canonical source. No provision/change. Extra MCP entitlement read UNAUTHORIZED reauthentication; no bypass and CLI succeeded via configured operator lane.'},ensure_ascii=False,indent=2)+'\n')
print('cost',round(sum(x['cost_usd'] or 0 for x in runs),5),'runs',len(runs),'captures',len(captures),'full',sum(x['capture_state']=='available_full_serp' for x in captures))
