-- Up Migration

-- TASK-611 — Capabilities Registry seed for existing 95 catalog entries (non-organization).
-- Idempotente (ON CONFLICT DO NOTHING). Pareja con migration
-- 20260508104217939_task-611-capabilities-registry.sql que crea la tabla + seedea las 11
-- organization.* introducidas por TASK-611. Esta migration alcanza paridad TS↔DB para todas
-- las capabilities ya declaradas en src/config/entitlements-catalog.ts.
--
-- Disciplina: cuando emerja una capability nueva en TS, la migration que la introduzca DEBE
-- agregar la fila correspondiente en capabilities_registry. El parity test runtime
-- (src/lib/capabilities-registry/parity.test.ts) detecta drift en CI.

INSERT INTO greenhouse_core.capabilities_registry (capability_key, module, allowed_actions, allowed_scopes, description) VALUES
  ('home.view','home',ARRAY['read'],ARRAY['own','all'],'runtime catalog entry — home.home.view'),
  ('home.nexa','home',ARRAY['read'],ARRAY['own','all'],'runtime catalog entry — home.home.nexa'),
  ('home.shortcuts','home',ARRAY['read'],ARRAY['own','all'],'runtime catalog entry — home.home.shortcuts'),
  ('agency.workspace','agency',ARRAY['read','launch'],ARRAY['tenant','all'],'runtime catalog entry — agency.agency.workspace'),
  ('people.directory','people',ARRAY['read','launch'],ARRAY['tenant','all'],'runtime catalog entry — people.people.directory'),
  ('hr.workspace','hr',ARRAY['read','launch'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.workspace'),
  ('hr.leave','hr',ARRAY['read','approve'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.leave'),
  ('hr.leave_balance','hr',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.leave_balance'),
  ('hr.leave_backfill','hr',ARRAY['create'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.leave_backfill'),
  ('hr.leave_adjustment','hr',ARRAY['create','update'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.leave_adjustment'),
  ('hr.org_chart','hr',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.org_chart'),
  ('hr.offboarding_case','hr',ARRAY['read','create','update','approve','manage'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.offboarding_case'),
  ('hr.final_settlement','hr',ARRAY['read','create','update','approve','manage'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.final_settlement'),
  ('hr.final_settlement_document','hr',ARRAY['read','create','update','approve','manage'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.final_settlement_document'),
  ('hr.onboarding_template','hr',ARRAY['read','create','update','manage'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.onboarding_template'),
  ('hr.onboarding_instance','hr',ARRAY['read','create','update','manage'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.onboarding_instance'),
  ('my.onboarding','my_workspace',ARRAY['read','update'],ARRAY['own','all'],'runtime catalog entry — my_workspace.my.onboarding'),
  ('hr.payroll_adjustments','hr',ARRAY['create','update'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.payroll_adjustments'),
  ('hr.payroll_adjustments_approval','hr',ARRAY['approve'],ARRAY['tenant','all'],'runtime catalog entry — hr.hr.payroll_adjustments_approval'),
  ('finance.workspace','finance',ARRAY['read','launch'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.workspace'),
  ('finance.status','finance',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.status'),
  ('finance.payment_instruments.read','finance',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_instruments.read'),
  ('finance.payment_instruments.update','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_instruments.update'),
  ('finance.payment_instruments.deactivate','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_instruments.deactivate'),
  ('finance.payment_instruments.manage_defaults','finance',ARRAY['manage'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_instruments.manage_defaults'),
  ('finance.payment_instruments.reveal_sensitive','finance',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_instruments.reveal_sensitive'),
  ('finance.payment_profiles.read','finance',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_profiles.read'),
  ('finance.payment_profiles.create','finance',ARRAY['create','update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_profiles.create'),
  ('finance.payment_profiles.approve','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_profiles.approve'),
  ('finance.payment_profiles.reveal_sensitive','finance',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_profiles.reveal_sensitive'),
  ('finance.payslip.resend','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payslip.resend'),
  ('finance.payroll.rematerialize','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payroll.rematerialize'),
  ('finance.payment_orders.recover','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payment_orders.recover'),
  ('finance.payments.repair_clp','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.payments.repair_clp'),
  ('finance.expenses.reclassify_economic_category','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.expenses.reclassify_economic_category'),
  ('finance.income.reclassify_economic_category','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.income.reclassify_economic_category'),
  ('finance.cash.adopt-external-signal','finance',ARRAY['create','update'],ARRAY['space','all'],'runtime catalog entry — finance.finance.cash.adopt-external-signal'),
  ('finance.cash.dismiss-external-signal','finance',ARRAY['update'],ARRAY['space','all'],'runtime catalog entry — finance.finance.cash.dismiss-external-signal'),
  ('finance.reconciliation.read','finance',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.reconciliation.read'),
  ('finance.reconciliation.match','finance',ARRAY['create','update'],ARRAY['space','all'],'runtime catalog entry — finance.finance.reconciliation.match'),
  ('finance.reconciliation.import','finance',ARRAY['create'],ARRAY['space','all'],'runtime catalog entry — finance.finance.reconciliation.import'),
  ('finance.reconciliation.declare_snapshot','finance',ARRAY['create','update'],ARRAY['space','all'],'runtime catalog entry — finance.finance.reconciliation.declare_snapshot'),
  ('finance.reconciliation.close','finance',ARRAY['close'],ARRAY['space','all'],'runtime catalog entry — finance.finance.reconciliation.close'),
  ('finance.reconciliation.ai_suggestions.read','finance',ARRAY['read'],ARRAY['space','all'],'runtime catalog entry — finance.finance.reconciliation.ai_suggestions.read'),
  ('finance.reconciliation.ai_suggestions.generate','finance',ARRAY['create'],ARRAY['space','all'],'runtime catalog entry — finance.finance.reconciliation.ai_suggestions.generate'),
  ('finance.reconciliation.ai_suggestions.review','finance',ARRAY['update'],ARRAY['space','all'],'runtime catalog entry — finance.finance.reconciliation.ai_suggestions.review'),
  ('finance.expense_distribution.ai_suggestions.read','finance',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.expense_distribution.ai_suggestions.read'),
  ('finance.expense_distribution.ai_suggestions.generate','finance',ARRAY['create'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.expense_distribution.ai_suggestions.generate'),
  ('finance.expense_distribution.ai_suggestions.review','finance',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — finance.finance.expense_distribution.ai_suggestions.review'),
  ('admin.workspace','admin',ARRAY['read','manage','launch'],ARRAY['all'],'runtime catalog entry — admin.admin.workspace'),
  ('client_portal.workspace','client_portal',ARRAY['read','launch'],ARRAY['space','all'],'runtime catalog entry — client_portal.client_portal.workspace'),
  ('my_workspace.workspace','my_workspace',ARRAY['read','launch'],ARRAY['own','all'],'runtime catalog entry — my_workspace.my_workspace.workspace'),
  ('ai_tooling.workspace','ai_tooling',ARRAY['read','launch'],ARRAY['tenant','all'],'runtime catalog entry — ai_tooling.ai_tooling.workspace'),
  ('commercial.workspace','commercial',ARRAY['read','launch'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.workspace'),
  ('commercial.party.create','commercial',ARRAY['create'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.party.create'),
  ('commercial.party.promote_to_client','commercial',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.party.promote_to_client'),
  ('commercial.party.churn','commercial',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.party.churn'),
  ('commercial.party.override_lifecycle','commercial',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.party.override_lifecycle'),
  ('commercial.deal.create','commercial',ARRAY['create'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.deal.create'),
  ('commercial.quote_to_cash.execute','commercial',ARRAY['approve'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.quote_to_cash.execute'),
  ('commercial.product_catalog.resolve_conflict','commercial',ARRAY['update'],ARRAY['all'],'runtime catalog entry — commercial.commercial.product_catalog.resolve_conflict'),
  ('commercial.pipeline','commercial',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.pipeline'),
  ('commercial.quotation','commercial',ARRAY['read','create','update','approve','export'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.quotation'),
  ('commercial.contract','commercial',ARRAY['read','create','update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.contract'),
  ('commercial.sow','commercial',ARRAY['read','create','update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.sow'),
  ('commercial.master_agreement','commercial',ARRAY['read','create','update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.master_agreement'),
  ('commercial.product_catalog','commercial',ARRAY['read','create','update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.product_catalog'),
  ('commercial.engagement.read','commercial',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.engagement.read'),
  ('commercial.engagement.declare','commercial',ARRAY['create'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.engagement.declare'),
  ('commercial.engagement.record_progress','commercial',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.engagement.record_progress'),
  ('commercial.engagement.record_outcome','commercial',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.engagement.record_outcome'),
  ('commercial.engagement.approve','commercial',ARRAY['approve'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.engagement.approve'),
  ('commercial.service_engagement.sync','commercial',ARRAY['sync'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.service_engagement.sync'),
  ('commercial.service_engagement.resolve_orphan','commercial',ARRAY['approve'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.service_engagement.resolve_orphan'),
  ('commercial.service_engagement.archive_legacy','commercial',ARRAY['delete'],ARRAY['tenant','all'],'runtime catalog entry — commercial.commercial.service_engagement.archive_legacy'),
  ('platform.health.read','admin',ARRAY['read'],ARRAY['all'],'runtime catalog entry — admin.platform.health.read'),
  ('platform.health.detail','admin',ARRAY['read'],ARRAY['all'],'runtime catalog entry — admin.platform.health.detail'),
  ('home.runway','finance',ARRAY['read'],ARRAY['organization','all'],'runtime catalog entry — finance.home.runway'),
  ('home.briefing.daily','home',ARRAY['read'],ARRAY['own','all'],'runtime catalog entry — home.home.briefing.daily'),
  ('home.atrisk.spaces','agency',ARRAY['read'],ARRAY['organization','all'],'runtime catalog entry — agency.home.atrisk.spaces'),
  ('home.atrisk.invoices','finance',ARRAY['read'],ARRAY['organization','all'],'runtime catalog entry — finance.home.atrisk.invoices'),
  ('home.atrisk.members','hr',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — hr.home.atrisk.members'),
  ('home.atrisk.projects','agency',ARRAY['read'],ARRAY['team','all'],'runtime catalog entry — agency.home.atrisk.projects'),
  ('person.legal_profile.read_masked','people',ARRAY['read'],ARRAY['own','all'],'runtime catalog entry — people.person.legal_profile.read_masked'),
  ('person.legal_profile.self_update','my_workspace',ARRAY['create','update'],ARRAY['own','all'],'runtime catalog entry — my_workspace.person.legal_profile.self_update'),
  ('personal_workspace.payslip.resend_self','my_workspace',ARRAY['update'],ARRAY['own','all'],'runtime catalog entry — my_workspace.personal_workspace.payslip.resend_self'),
  ('personal_workspace.payment_profile.read_self','my_workspace',ARRAY['read'],ARRAY['own','all'],'runtime catalog entry — my_workspace.personal_workspace.payment_profile.read_self'),
  ('personal_workspace.payment_profile.request_change_self','my_workspace',ARRAY['create'],ARRAY['own','all'],'runtime catalog entry — my_workspace.personal_workspace.payment_profile.request_change_self'),
  ('person.legal_profile.hr_update','hr',ARRAY['create','update'],ARRAY['tenant','all'],'runtime catalog entry — hr.person.legal_profile.hr_update'),
  ('person.legal_profile.verify','hr',ARRAY['approve'],ARRAY['tenant','all'],'runtime catalog entry — hr.person.legal_profile.verify'),
  ('person.legal_profile.reveal_sensitive','hr',ARRAY['read'],ARRAY['tenant','all'],'runtime catalog entry — hr.person.legal_profile.reveal_sensitive'),
  ('person.legal_profile.export_snapshot','hr',ARRAY['export'],ARRAY['tenant','all'],'runtime catalog entry — hr.person.legal_profile.export_snapshot'),
  ('workforce.role_title.update','hr',ARRAY['update'],ARRAY['tenant','all'],'runtime catalog entry — hr.workforce.role_title.update'),
  ('workforce.role_title.review_drift','hr',ARRAY['read','approve'],ARRAY['tenant','all'],'runtime catalog entry — hr.workforce.role_title.review_drift'),
  ('workforce.assignment_role_override','hr',ARRAY['create','update'],ARRAY['tenant','all'],'runtime catalog entry — hr.workforce.assignment_role_override')
ON CONFLICT (capability_key) DO NOTHING;

-- Down Migration

DELETE FROM greenhouse_core.capabilities_registry
  WHERE capability_key NOT LIKE 'organization.%';
