import{dir,svg,rect,text,label,im,N,B,W,pattern,link}from'./arte.mjs';import sharp from'sharp';import{readFile,writeFile,mkdir,copyFile}from'node:fs/promises';import{join}from'node:path';
const entries=[];async function crop(file,id,object,view,box){await sharp(join(dir,'final',file)).extract(box).flatten({background:W}).png().toFile(join(dir,'individuales',id+'.png'));entries.push({id,object,view,file:'individuales/'+id+'.png',source:'final/'+file,status:'propuesta-para-aprobacion'});}
for(const[file,names]of [['02-mugs-magenta-naranja.png',['magenta','naranja']],['03-mugs-blanco-azul.png',['blanco','azul']]])for(let r=0;r<2;r++)for(let c=0;c<4;c++){const ob='mug-'+names[r],v=['frente','tres-cuartos','reverso','cenital'][c];await crop(file,ob+'-'+v,ob,v,{left:c*384,top:r*512,width:384,height:512});}
const boxes=[{left:185,top:0,width:425,height:480},{left:775,top:0,width:730,height:485},{left:175,top:485,width:445,height:480},{left:688,top:480,width:817,height:530}];for(let i=0;i<4;i++){const v=['frente','tres-cuartos','reverso','abierta'][i];await crop('04-agenda.png','agenda-'+v,'agenda',v,boxes[i]);}
for(let i=0;i<4;i++){const v=['tapa-cenital','cerrado-tres-cuartos','abierto-reverso','abierto-frente'][i];await crop('05-mac.png','mac-'+v,'mac',v,{left:i%2*768,top:i<2?0:480,width:768,height:i<2?470:544});}
for(let i=0;i<4;i++){const v=['frente','tres-cuartos','perfil','reverso'][i];await crop('06-pizarra.png','pizarra-'+v,'pizarra',v,{left:i%2*768,top:i<2?0:460,width:768,height:i<2?460:564});}
await writeFile(join(dir,'manifest.json'),JSON.stringify({title:'Enlace',version:3,date:'2026-09-25',status:'recurso-grafico-candidato-no-validado',masterbrand:'Efeonce',views:entries,feedbackPreserved:['Logo pequeño en zona baja','Reverso limpio de agenda','Objetos aislados sobre blanco y multivista'],changes:['Marca incorporada a mugs magenta y naranja','Mismo módulo de superficie entre objetos','F11 descartado tras encontrar uso en otras agencias'],fixed:{module:'art/modulo-enlace.svg',geometry:'dos codos opuestos, radio exterior 160, interior 80, terminales diagonales de 80, celda 470',rowOffset:'0.5 celda en filas alternadas'},flexible:['escala uniforme','tinta','contraste tonal','recorte de patrón por superficie'],provenance:{baseRenders:'../apertura-v1/renders',notebookBase:'../ideas-con-direccion-v2/bases/agenda.png',officeBase:'../ideas-con-direccion-v2/bases/oficina.png',graphics:'SVG locales dibujados; logotipos oficiales intactos; tipografía de archivos de fuente reales',method:'composición vectorial con perspectiva sobre bases generadas previamente'},validation:{visualReview:'realizada',brandRecall:'no-medido',brandLift:'no-medido',plan:'VALIDACION.md'}},null,2));
const pic=async(f,x,y,w,h)=>`<image href="data:image/png;base64,${(await readFile(join(dir,f))).toString('base64')}" x="${x}" y="${y}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet"/>`;
let mugs=rect(0,0,1800,1320,W)+im('logo',60,43,225,60)+label('EXPLORACIÓN 03 / CUATRO COLORES, MISMA FAMILIA',1090,81,13,N,600)+text('Firma discreta. Trama común.',55,213,90,N,{maxWidth:1680})+label('Una cara con identificación baja; la otra con el patrón en tono sobre tono.',60,263,21,N);
for(let c=0;c<4;c++){const color=['blanco','azul','magenta','naranja'][c];mugs+=await pic('individuales/mug-'+color+'-frente.png',45+c*430,300,408,456);mugs+=await pic('individuales/mug-'+color+'-reverso.png',45+c*430,770,408,456);mugs+=label(color.toUpperCase(),75+c*430,764,13,N,600);}
mugs+=label('Todas las variantes conservan Efeonce como marca principal. Los colores Globe funcionan como acento.',60,1280,17,N);await sharp(Buffer.from(svg(1800,1320,mugs))).png().toFile(join(dir,'00-tazas-familia.png'));
const editorial=svg(600,800,`${rect(0,0,600,800,W)}${text('Ideas con',42,113,67,N,{weight:420,maxWidth:505})}${text('dirección.',40,194,86,N,{maxWidth:515})}<svg x="0" y="280" width="600" height="390" viewBox="0 0 600 390">${pattern(600,390,N,.95,208)}</svg>${im('logo',44,713,174,47)}`);await writeFile(join(dir,'art/pieza-editorial.svg'),editorial);await sharp(Buffer.from(editorial)).png().toFile(join(dir,'art/pieza-editorial.png'));
const noLogo=svg(1600,900,`${rect(0,0,1600,900,'#F5F4EF')}${label('MATERIAL DE PRUEBA / SIN RESULTADOS DE PÚBLICO',55,62,13,N,600)}${text('La forma permanece.',51,170,85,N)}${label('Mismo recurso a una tinta, en negativo y en trama; sin nombre, logo ni mensaje.',55,220,20,N)}
${rect(55,290,455,475,W)}${link(92,347,365,N)}${rect(571,290,455,475,N)}${link(608,347,365,W)}<svg x="1087" y="290" width="455" height="475" viewBox="0 0 455 475">${rect(0,0,455,475,W)}${pattern(455,475,N,1,160)}</svg>
${label('Preparado para evaluar atribución y confusión. La continuidad visual no demuestra recordación.',55,843,17,N)}`);await sharp(Buffer.from(noLogo)).png().toFile(join(dir,'08-lectura-sin-firma.png'));
const sections=[['01-recurso.png','01 / RECURSO','Enlace: geometría estable','Un módulo de dos codos opuestos y cortes diagonales. Se conserva el dibujo al pasar de papel a cerámica, metal o muro.'],['00-tazas-familia.png','02 / TAZAS','Firma discreta. Trama común.','Cuatro colores; logo oficial pequeño y bajo en una cara, trama tonal en la otra.'],['final/02-mugs-magenta-naranja.png','03 / MAGENTA Y NARANJA','Ahora tienen marca','Frente, tres cuartos, reverso y cenital por color. Efeonce sigue siendo la marca principal.'],['final/03-mugs-blanco-azul.png','04 / BLANCO Y AZUL','La misma regla de presencia','Identificación baja y reverso con el mismo patrón. Se mantiene la opción de superficies de descanso en el resto del set.'],['final/04-agenda.png','05 / AGENDA','Reverso conservado','El frente explora la trama. La firma pequeña al reverso mantiene su ubicación y escala. Cuatro vistas.'],['final/05-mac.png','06 / MAC','Ship y trama','El ship oficial lidera; una pequeña pieza de vinilo ensaya el recurso secundario. Cuatro vistas.'],['final/06-pizarra.png','07 / ACRÍLICO','Firma baja y área libre','La trama ocupa una zona acotada. El espacio de trabajo permanece claro. Cuatro vistas.'],['final/07-estudio.png','08 / ESTUDIO','La misma forma en otra escala','Prueba de mural y objetos. Es una aplicación espacial conceptual, pendiente de revisión.'],['08-lectura-sin-firma.png','09 / VALIDACIÓN','Preparado para probar','Se muestran forma y repetición sin logo. Hace falta una prueba con público para saber si genera atribución a Efeonce.']];
await writeFile(join(dir,'sections.json'),JSON.stringify(sections,null,2));
const prev=await readFile(join(dir,'../ideas-con-direccion-v2/index.html'),'utf8');const css=prev.match(/<style>([\s\S]*?)<\/style>/)[1];await mkdir(join(dir,'fonts'),{recursive:true});for(const f of ['bricolage.ttf','poppins.ttf'])await copyFile(join(dir,'../ideas-con-direccion-v2/fonts',f),join(dir,'fonts',f));await copyFile(join(dir,'../../../public/branding/logo-full.svg'),join(dir,'art/efeonce.svg'));
const html=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Efeonce · Enlace · Propuesta 03</title><style>${css}</style><header><img src="art/efeonce.svg" alt="Efeonce"><p>PROPUESTA 03 · ENLACE<br>25 SEPTIEMBRE 2026</p></header><main><section class="intro"><div class="eyebrow">En revisión</div><h1>Una forma común.<br>Una firma discreta.</h1><p>La corrección se concentra en dos decisiones: dar presencia de marca a todos los colores de taza y repetir un recurso concreto entre distintos soportes. Se conserva la ubicación baja del logo que te gustó.</p><div class="actions"><a href="revision-efeonce-v3.pdf" download>Descargar revisión PDF</a><a href="referencias-efeonce-v3.zip" download>Descargar 28 vistas + artes</a></div><nav><a href="#s1">Tazas</a><a href="#s0">Recurso</a><a href="#s4">Agenda</a><a href="#s7">Estudio</a><a href="#validacion">Validación</a></nav></section>${sections.map(([file,k,t,d],i)=>`<section id="s${i}"><div class="eyebrow">${k}</div><h2>${t}</h2><p>${d}</p><figure><a href="${file}"><img src="${file}" alt="${t}" loading="lazy"></a><figcaption>Propuesta para aprobación. Abre la imagen para ver el detalle.</figcaption></figure></section>`).join('')}<section id="validacion"><h2>Qué falta comprobar.</h2><p>Enlace es una candidata. La prueba pendiente debe medir cuántas personas la atribuyen a Efeonce y cuántas la confunden con otras marcas. El brand lift requiere además comparar grupos expuestos y no expuestos. No hay resultados de público todavía.</p><p><a href="VALIDACION.md">Plan de validación</a> · <a href="README.md">Ficha de dirección y procedencia</a></p><details><summary>28 vistas individuales</summary><div class="files">${entries.map(e=>`<a href="${e.file}" download>${e.id.replaceAll('-',' ')}</a>`).join('')}</div></details><details><summary>Artes vectoriales</summary><div class="files">${['modulo-enlace','trama-enlace','agenda-tinta','agenda-portada','agenda-reverso','mural-tinta','pieza-editorial'].map(n=>`<a href="art/${n}.svg" download>${n.replaceAll('-',' ')}</a>`).join('')}</div></details><p style="font-size:13px">La ruta f11 ensayada durante esta ronda se descartó como eje al encontrar usos en agencias y estudios. Enlace se conserva como patrón candidato; Efeonce y su ship mantienen la identidad principal.</p></section></main><footer>Referencias conceptuales · Renders de base reutilizados + composición vectorial · Aprobación de dirección pendiente</footer></html>`;
await writeFile(join(dir,'index.html'),html);console.log(entries.length+' vistas y galería preparados.');
