/** Build a browser-only controller; never serialize functions transformed by the server runtime. */
import { writeFile, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

import { build } from 'esbuild'

export async function generateLoginController(check = false) {
  const root = process.cwd()

  const result = await build({
    stdin: {
      contents: `import {installLoginController} from './src/lib/auth-server/persons/login-controller';
      import {AUTH_LOGIN_COPY} from './src/lib/copy/auth-server-login';
      installLoginController(document.querySelector('[data-capture="id-passkey"]'), AUTH_LOGIN_COPY,
        {fetch:window.fetch.bind(window),credentials:navigator.credentials,
        supported:typeof window.PublicKeyCredential==='function'&&typeof navigator.credentials?.get==='function',
        navigate:url=>window.location.assign(url)});`,
      resolveDir: root,
      loader: 'ts'
    },
    bundle: true,
    platform: 'browser',
    format: 'iife',
    target: 'es2022',
    write: false,
    keepNames: false,
    minify: false,
    tsconfig: resolve(root, 'tsconfig.json')
  })

  const script = result.outputFiles[0]!.text.replaceAll('</script', '<\\/script')

  const output =
    '/** Generated by scripts/auth-server/generate-login-controller.ts. Do not edit. */\nexport const LOGIN_CONTROLLER_SCRIPT = ' +
    JSON.stringify(script) +
    '\n'

  const path = resolve(root, 'src/lib/auth-server/persons/login-controller.generated.ts')

  if (check) {
    if ((await readFile(path, 'utf8')) !== output) throw new Error('login_controller_drift')
  } else await writeFile(path, output)
}
