/** Build a browser-only controller; never serialize functions transformed by the server runtime. */
import { writeFile, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

import { build } from 'esbuild'

export async function generateStepUpController(check = false) {
  const root = process.cwd()

  const result = await build({
    stdin: {
      contents: `import {installStepUpController} from './src/lib/auth-server/persons/step-up-controller';
      import {AUTH_STEP_UP_COPY} from './src/lib/copy/auth-server-step-up';
      import QRCode from 'qrcode';
      installStepUpController(document.querySelector('[data-capture="auth-step-up"]'), AUTH_STEP_UP_COPY,
        {fetch:window.fetch.bind(window),credentials:navigator.credentials,navigate:url=>window.location.assign(url),
        renderQr:async value=>'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(await QRCode.toString(value,{type:'svg',width:256,margin:2}))});`,
      resolveDir: root,
      loader: 'ts'
    },
    bundle: true,
    platform: 'browser',
    format: 'iife',
    target: 'es2022',
    write: false,
    keepNames: false,
    minify: false,
    tsconfig: resolve(root, 'tsconfig.json')
  })

  const script = result.outputFiles[0]!.text.replaceAll('</script', '<\\/script')

  const output =
    '/** Generated by scripts/auth-server/generate-step-up-controller.ts. Do not edit. */\nexport const STEP_UP_CONTROLLER_SCRIPT = ' +
    JSON.stringify(script) +
    '\n'

  const path = resolve(root, 'src/lib/auth-server/persons/step-up-controller.generated.ts')

  if (check) {
    if ((await readFile(path, 'utf8')) !== output) throw new Error('step_up_controller_drift')
  } else await writeFile(path, output)
}
