import fs from 'node:fs';import {construirPrompt} from '../../scripts/foto/build-prompt.mjs';
const root='ai-generations/2026-09-22_aeo-final-safe-v05';
for(const base of ['01-fuera','02-reconoces','03-referencia','04-elegida']) {
const f=JSON.parse(fs.readFileSync(`ai-generations/2026-09-22_aeo-cta-v04/brief/${base}-45.json`));f.id=base+'-916';f.formato='9:16';f.lecho.objeto='A very near real foreground object that ALREADY OCCUPIES THE ENTIRE LOWER 44 PERCENT, starting at 56 percent down the frame, not merely at the bottom: '+f.lecho.objeto;f.lecho.tono+='; IMPORTANT extend this same foreground upward to 56 percent of frame height so the whole lower 44 percent is empty and softly blurred';
f.escena=`REFRAME THIS 4:5 REFERENCE INTO A NEW NATIVE 9:16 PHOTOGRAPH. Change the scene framing substantially: make the important scene smaller and higher than the reference. This is a new camera framing of the exact same scene. Preserve exact identity, navy corporate clothing, anatomy and the digital story. Native vertical 9:16 photograph. Re-stage camera distance and object placement for an Instagram full-screen ad. CRITICAL SPATIAL BRIEF: top 0–34% is the real graphite studio wall, dark evenly shadowed and empty, no window or projected light. The entire important scene — head, both hands, tablet, screen source cards and mascot — is inside x=10–86%, y=35–56%. Use a compact, strong close scene horizontally arranged in that central band; all important details recognizable. A real near foreground object crosses the frame from y=58% all the way to the bottom, softly out of focus, with a gradual transition. At y=61–64% the center of that real foreground is completely calm and ${base==='03-referencia'?'very pale near-white':'deep charcoal almost black'}. This physical foreground must be high enough to hold a later logo ABOVE platform UI. It is NOT a graphic panel or gradient overlay. Bottom 35% contains only continued defocused foreground, no meaningful content. TOP 14% also contains no meaningful content. Do not put any headline, CTA, watermark, letters, logos, or signature into this photograph. ` + ({
'01-fuera':'Preserve the blue cloud-shaped Codex character and physical monitor with two blue filled source cards and a conspicuous empty third source slot. The blue monitor stand stays physical. The foreground is the softly curved dark upholstered back of the viewer chair very close to lens. Remove irrelevant desk clutter. Horizontal arrangement: Codex left, monitor right. Screen entirely inside the central action band.',
'02-reconoces':'Nexa in side/rear profile holds her tablet naturally in both hands, at her waist. Tablet screen faces inward/up toward HER; no pointing hand. Her tablet shows a modern tower, the real wall monitor shows an old warehouse. Keep face, hands, both images visible together inside the central action band. The near dark corridor windowsill very close to lens creates the foreground.',
'03-referencia':'Nexa side/rear profile in navy polo observes a physical projection on real concrete with one bold blue source card. She holds the matching tablet naturally, its screen toward her, not toward camera. All projection, head, hands and tablet are inside the central action band. Low projector on real blue equipment support. Foreground is the real near review table, pale almost white with soft optical defocus, starting by58% and continuing to the bottom. No stray dark tabletop seams at y61–64%.',
'04-elegida':'Keep the real inclined touchscreen with blue physical frame and a large naturally formed index finger hovering just BEFORE tapping the highlighted source card. Finger and reflection agree physically. Blue Codex farther behind is still recognizable. Finger, chosen card and Codex are entirely inside the central action band. Real dark foreground equipment housing very close to lens obscures the bottom35% naturally.'}[base]);
fs.writeFileSync(`${root}/brief/${f.id}.json`,JSON.stringify(f,null,2)+'\n');const p=construirPrompt(f);fs.writeFileSync(`${root}/brief/${f.id}.prompt.txt`,p.prompt);
}
