/**
 * Display identifier resolver — canonical helper (TASK-701 follow-up).
 *
 * Different instrument categories carry their identifier in different
 * fields. Hardcoding the lookup in adapters / readiness / chips means every
 * new category requires editing 3+ places and forgetting one is what made
 * credit cards show "Sin identificador visible" even when `card_last_four`
 * was populated.
 *
 * This helper is the single source of truth for "what visible identifier
 * does this instrument have?". Categories declare their identifier source
 * via `IDENTIFIER_SOURCES`. Consumers call `resolveDisplayIdentifier(row)`
 * and never branch on category.
 *
 * ⚠️ FOR AGENTS / FUTURE DEVS:
 * - DO NOT inline `row.cardLastFour ?? row.accountNumber ?? ...` in a new
 *   adapter. Use this helper.
 * - When a new category ships with a new identifier source, add an entry
 *   to `IDENTIFIER_SOURCES`. The form / list / readiness adapt without
 *   further changes.
 */

import type { InstrumentCategory } from '@/config/payment-instruments'

export interface IdentifierFields {
  /** The masked account number (e.g. '•••• 4661' for bank, '•••• 0001' for CCA). */
  accountNumberMasked?: string | null
  /** Raw account number — only present when caller has reveal access. */
  accountNumber?: string | null
  /** Card last 4 digits (credit/debit cards). */
  cardLastFour?: string | null
  /** Provider-issued identifier (e.g. fintech account, deel contractor id). */
  providerIdentifierMasked?: string | null
  providerIdentifier?: string | null
}

type IdentifierFieldKey =
  | 'accountNumberMasked'
  | 'accountNumber'
  | 'cardLastFour'
  | 'providerIdentifierMasked'
  | 'providerIdentifier'

interface IdentifierSource {
  /** Ordered list of fields to try, first non-empty wins. */
  fields: readonly IdentifierFieldKey[]
  /** Optional formatter — applied to the resolved raw value. */
  format?: (value: string) => string
}

const cardFormatter = (value: string) => {
  const trimmed = value.trim()

  if (!trimmed) return trimmed

  // If the value already has bullets/masking, leave it alone.
  if (trimmed.startsWith('••••') || trimmed.startsWith('•••')) return trimmed

  // For pure 4-digit card_last_four we render the canonical bank-style masking.
  return `•••• ${trimmed}`
}

/**
 * Per-category identifier resolution. Each category declares the ordered
 * fallback chain of fields its display identifier comes from.
 *
 * `accountNumberMasked` is preferred over `accountNumber` because the API
 * already masks values it sends to clients — the raw `accountNumber` is
 * only present after a reveal flow with audit.
 */
const IDENTIFIER_SOURCES: Record<InstrumentCategory, IdentifierSource> = {
  bank_account: {
    fields: ['accountNumberMasked', 'accountNumber', 'providerIdentifierMasked', 'providerIdentifier']
  },
  credit_card: {
    // Cards never store full PAN; only the last 4 digits are persisted and visible.
    fields: ['cardLastFour', 'accountNumberMasked', 'providerIdentifierMasked'],
    format: cardFormatter
  },
  fintech: {
    fields: ['accountNumberMasked', 'accountNumber', 'providerIdentifierMasked', 'providerIdentifier']
  },
  payment_platform: {
    fields: ['providerIdentifierMasked', 'providerIdentifier', 'accountNumberMasked', 'accountNumber']
  },
  payroll_processor: {
    fields: ['providerIdentifierMasked', 'providerIdentifier', 'accountNumberMasked', 'accountNumber']
  },
  cash: {
    fields: []
  },
  shareholder_account: {
    // Internal account number generated by the canonical allocator (TASK-700).
    fields: ['accountNumberMasked', 'accountNumber']
  }
}

const pickFirst = (
  source: IdentifierFields,
  fields: readonly IdentifierFieldKey[]
): string | null => {
  for (const key of fields) {
    const value = source[key]

    if (typeof value === 'string') {
      const trimmed = value.trim()

      if (trimmed.length > 0) return trimmed
    }
  }

  return null
}

/**
 * Resolve the display identifier for a payment instrument row.
 * Returns `null` when no identifier is available for the category — the
 * UI then shows a placeholder ("Sin identificador visible") that is
 * semantically correct (the row truly has no display identifier yet),
 * not a missing-data bug.
 */
export const resolveDisplayIdentifier = (
  row: IdentifierFields,
  category: InstrumentCategory | string | null | undefined
): string | null => {
  if (!category) return null

  const source = IDENTIFIER_SOURCES[category as InstrumentCategory]

  if (!source) return null

  const raw = pickFirst(row, source.fields)

  if (!raw) return null

  return source.format ? source.format(raw) : raw
}
