from pathlib import Path
import csv,json,hashlib,re,collections
p=Path(__file__).resolve().parent;r=p.parent/'research'/'pibank-expanded-2026-10-06';d=json.loads((r/'keyword-dataset.json').read_text());rows=d['keywords'];idx={x['normalized_keyword']:x for x in rows}
# Manual decision families, representative chosen for intent/localisation, never maximum.
S=[
('A01','Cuenta de ahorro líquido en soles','direct','cuenta de ahorros','market_proxy_sensitivity','Alta','Producto; FAQ definición/uso','Base categoría existente; no sumar singular/plural ni digital genérico','category'),
('A02','Rendimiento de cuenta de ahorro','direct','interes de cuenta de ahorro','market_proxy_sensitivity','Alta','Producto/calculadora/FAQ tasa y cálculo','Interés/con intereses/tasa son formulaciones superpuestas','yield'),
('A03','Ahorro sin mantenimiento','direct','cuenta de ahorros sin mantenimiento','market_proxy_sensitivity','Alta','Producto/FAQ costos','No sumar cero/gratis/sin mantenimiento; ITF y excepciones requieren revisión','cost'),
('A04','Comparar cuentas de ahorro Perú','direct','mejores cuentas de ahorro peru','market_proxy_sensitivity','Alta','Producto; comparación nueva o ampliación','Comparar condiciones equivalentes; variantes de años/mejor banco solapan','compare_accounts'),
('A05','Banco que paga intereses por ahorro','conditional','que banco paga mas intereses en peru','market_proxy_pending_serp','Media','Comparación de ahorro vs plazo y fuentes','Representante localizado40; generic480 no se suma y SERP mayor interés mezcla plazo fijo','compare_banks'),
('A06','Dónde colocar dinero y ganar intereses','conditional','donde puedo ahorrar mi dinero y ganar intereses en peru','market_proxy_pending_serp','Media','Guía decisión + producto','Intención recuperada del ruido; otra consulta390 no se añade automáticamente','place_savings'),
('A07','Abrir cuenta de ahorros','direct','abrir cuenta de ahorros','market_proxy_sensitivity','Alta','FAQ apertura + registro','Apertura/crear/online forman recorrido; no sumar sinónimos','opening'),
('A08','Requisitos/elegibilidad y monto de apertura','direct','requisitos para abrir una cuenta de ahorros','market_proxy_pending_serp','Media','FAQ requisitos/documentos/mínimo','Compatible con adulto peruano residente y DNI; puede solapar apertura','requirements'),
('C01','Ahorro de alto rendimiento en Perú','conditional','cuentas de alto rendimiento peru','conditional_not_default','Media','Producto + comparación','Geografía/producto mixtos; generic1600 excluido del default; no suma año2026','high_yield'),
('C02','Cuenta digital y ahorro digital','conditional','cuenta digital','conditional_not_default','Media','Producto/FAQ sin medios de pago','Búsqueda espera pagos/débito a menudo; ahorro digital210 tampoco se añade sin SERP','digital'),
('C03','Ahorro frente a cuenta corriente/plazo fijo','conditional','diferencia entre cuenta corriente y cuenta de ahorros','assisted_only','Media','Guía para decidir si ahorro líquido encaja','Comparación legítima; productos alternativos no son adquisición propia automática','substitute_comparison'),
('C05','Evaluación de ahorro de otra entidad / cross-shopping','conditional','cuenta super tasa interbank','competitor_consideration_requires_serp','Media','Comparaciones por producto/condiciones; posible traslado de ahorro','No descartar ahorro rival por marca; distinguir evaluación vs login/soporte, conservar volumen1900sin adjudicar aPibank','competitor_consideration'),
('C04','Categoría bancaria/interés general','conditional','cuenta bancaria','no_default_mixed_intent','Baja','Contexto de producto','4.400 no son demanda ahorro; tasa interés3.600/intereses2.900 mezclan crédito/otros','broad_banking'),
('E01','Qué es una cuenta de ahorro y beneficios','assisted','que es una cuenta de ahorros','assisted_only','Alta','FAQ qué es/para qué sirve','Educación próxima al producto; variantes definición no sumadas','definition'),
('E02','Comprender TREA y cálculo','assisted','trea','assisted_only','Alta','Calculadora/FAQ con fuentes bancarias','TREA2.900 y qué es880 no son poblaciones nuevas ni margen del banco','trea'),
('E03','Simular rendimiento de ahorro','assisted','simulador cuenta de ahorros','assisted_only','Alta','Calculadora existente','Simulador40 medido; calculadora/intereses sin dato no rellenar con0 ni plazo fijo','calculator'),
('E04','FSD y respaldo institucional','assisted','fondo de seguro de depositos','assisted_only','Alta','FAQ garantía + identidad + FSD','FSD1.600 es confianza no demanda directa; verificar entidad y periodo','insurance'),
('E05','Seguridad de un banco para ahorrar','assisted','bancos seguros en peru','assisted_only','Media','Confianza/identidad','10 estimado; no atribuir urgencias, fraude ni confianza a cuentas sin datos','safety'),
('E06','CCI: significado y consulta','service','que es cci','assisted_or_service_only','Alta','FAQ transferencias + guía de fondeo','CCI9.900/definición4.400/consulta2.400 solapan y sirven clientes de muchos bancos','cci'),
('E07','Transferencia bancaria/local','service','transferencia bancaria','assisted_or_service_only','Alta','FAQ operaciones/tipos','Banco propio soporta transferencias locales; internacional fuera de oferta','transfer'),
('E08','Tiempo/horarios de transferencia','service','cuanto demora una transferencia interbancaria','assisted_or_service_only','Alta','FAQ horarios/límites','2.400 estimadas; de clientes existentes o fondos entrantes; no añadir aperturas','transfer_time'),
('E09','Primer fondeo de Cuenta Soles','activation',None,'bank_baseline_required','Alta','FAQ transferencias/monto; secuencia de activación','No medir «cuentas de fondeo»260: probablemente trading; seed depositar sin datos','first_funding'),
('E10','Educación para ahorrar','assisted','como ahorrar dinero','assisted_only','Media','Guía si mejora decisión de ahorro líquido','590 no atribuye captación; excluye agua/energía/tareas escolares y formatos vacíos','saving_habits'),
('B01','Pibank Perú: identidad y producto','brand',None,'own_brand_baseline_required','Alta','Home/producto/identidad/FAQ','Pibank140 es histórico global/marca previa; no baseline lanzamiento Perú','own_brand'),
('B02','Marca: evaluación hacia apertura','conversion',None,'eligible_sessions_required','Alta','Producto/registro y CTA','Mejora sobre tráfico de todos los canales; no medir lift desde volumen keywords','conversion'),
('B03','Acceso/app/OTP y administración','service',None,'service_baseline_required','Alta','FAQ app/acceso/administración','Trabajo verificable de experiencia; sin denominador tickets/autoservicio no ahorro monetario','app_service'),
('B04','Saldo mantenido y permanencia','retention',None,'bank_cohort_baseline_required','Alta','Comunicación condiciones/uso + coordinación banco','Más fondeo/saldo no probado por FAQ; cohortes/origen externo y ventanas requeridos','retention'),
('I01','AEO: representación y citabilidad','aeo',None,'surface_panel_required','Media','Producto/entidad/FAQ/fuentes externas','PAA no son LLM prompts medidos;16bloques AI Overview sin benchmark de respuestas','aeo'),
('X01','Marca rival navegacional/soporte u otra entidad','benchmark',None,'not_acquisition_default','Variable','Benchmark de páginas oficiales','Volumen marca no adquirible automáticamente; incluye bancos extranjeros','competitor'),
('X02','Oferta futura dólares','future','cuenta en dolares','product_launch_required','No actual','Backlog futuro','No oferta actual acreditada; FX/conversión suelta no cuenta USD','usd'),
('X03','Producto/segmento/país incompatible','excluded',None,'excluded','No actual','Ningún nuevo destino','Tarjeta/pagos/internacional/empresas/menores/noDNI/otrospaíses fuera del alcance','incompatible'),
('X04','Otra intención/ruido o sin revisión suficiente','excluded',None,'excluded_or_manual_review','No validada','Sin producción automática','No convertir clasificación por regex en TAM ni intención comprobada','noise'),
]
fs=[]
for num,label,lane,rep,mode,fit,asset,why,slug in S:
 x=idx.get(rep) if rep else None
 fs.append({'family_id':num,'family':label,'lane':lane,'representative_keyword':x['keyword'] if x else None,'representative_keyword_id':x['id'] if x else None,'estimated_searches_per_month':x['search_volume'] if x else None,'volume_state':x['volume_state'] if x else 'not_measured','source':x['source'] if x else None,'keyword_updated_at':x['keyword_updated_at'] if x else None,'history_months':len(x['monthly_searches']) if x else 0,'history_latest':str(x['monthly_searches'][0]) if x and x['monthly_searches'] else None,'period':'row_update_and_history; not2027' if x else 'not_measured','market':'PE2604/es','modelability':mode,'product_fit':fit,'existing_asset':asset,'overlap_and_reason':why,'slug':slug,'own_baseline':None,'conversion':None,'incremental_value':None})
fby={x['slug']:x for x in fs}
# Explicitly curated mapping prevents previously missed fit and automatic positives.
manual={}
groups={
'category':['cuenta de ahorros','cuenta ahorro','cuenta de ahorros peru','cuentas de ahorro peru','cuenta de ahorros en soles','cuenta de ahorro soles','cuenta de ahorros mn','cuenta de ahorros a la vista'],
'yield':['interes de cuenta de ahorro','cuenta de ahorro con intereses','cuenta de ahorros con intereses','cuentas de ahorros con intereses','intereses cuenta de ahorros','intereses en cuenta de ahorros','cuenta de ahorros tasa de interes','cuenta de ahorros interes','cuenta de ahorros intereses','cuenta de ahorros que genera intereses','cuenta de ahorros con rendimientos','cuenta de ahorros con rentabilidad','cuenta de ahorros con mejor tasa','cuenta de ahorros con mayor tasa de interes','cuenta de ahorros que paga mas intereses','cuenta de ahorros con mayor rentabilidad','cuenta de ahorros mejor tasa','cuenta de ahorros con intereses altos','cuenta de ahorros con mas intereses','cuenta de ahorros con mayor tasa de interes peru','cuenta de ahorros con mejor rendimiento','cuenta de ahorros ganan intereses','cual es la rentabilidad de una cuenta de ahorros'],
'cost':['cuenta de ahorros sin mantenimiento','cuenta de ahorros cero mantenimiento','cuenta de ahorros gratis','cuenta de ahorros gratuita','cuenta ahorros sin cuota de manejo','cuenta de ahorros 0 cuota de manejo','cuenta de ahorros cero','abrir cuenta de ahorros gratis','abrir cuenta de ahorros sin cuota de manejo'],
'compare_accounts':['mejores cuentas de ahorro peru','mejor cuenta de ahorros','mejores cuentas de ahorro','mejores cuentas de ahorro peru 2026','cual es la mejor cuenta de ahorros en peru','comparar cuentas de ahorro','que cuenta de ahorros es mejor','cual es la mejor cuenta de ahorros','la mejor cuenta de ahorros en peru'],
'compare_banks':['que banco paga mas intereses en peru','que banco paga mas intereses','banco que paga mas intereses','que banco paga mas intereses en peru 2026','mejor banco para ahorrar','cual banco es mejor para ahorrar','cual es el mejor banco para ahorrar','que banco es mejor para ahorrar','mejor banco para abrir cuenta de ahorros','mejor banco para ahorrar en peru','mejor banco para ahorrar peru','cual es el banco que paga mas intereses en peru','cual es el mejor banco del peru para ahorrar','el mejor banco para ahorrar en peru','banco que paga mas intereses peru','cual es el banco que paga mas intereses','cual es el mejor banco para ahorrar en peru','que banco es mejor para ahorrar en peru','que banco paga mas intereses en cuenta de ahorro','que bancos pagan mas intereses por ahorros en peru','cual es el mejor banco en peru para ahorrar','cual es el mejor banco para ahorrar dinero'],
'place_savings':['en que banco puedo ahorrar mi dinero y ganar intereses','donde puedo ahorrar mi dinero y ganar intereses en peru','donde puedo ahorrar mi dinero y ganar intereses'],
'opening':['abrir cuenta de ahorros','apertura cuenta de ahorros','apertura de cuenta de ahorros','crear cuenta de ahorros','como abrir una cuenta de ahorros','como crear cuenta de ahorros','como crear una cuenta de ahorros','como sacar cuenta de ahorros','como sacar una cuenta de ahorros','abrir cuenta de ahorros online','abrir una cuenta de ahorros','abre tu cuenta de ahorros','donde abrir cuenta de ahorros','donde abrir una cuenta de ahorros','abrir cuenta de ahorros en linea','abrir cuenta de ahorros por internet','abrir cuenta de ahorros virtual','abrir una cuenta de ahorros online','bancos para abrir cuenta de ahorros','como abrir una cuenta de ahorros online','como abrir una cuenta de ahorros por internet','como crear una cuenta de ahorros online','como hago para abrir una cuenta de ahorros','como tener una cuenta de ahorros','crear una cuenta de ahorros','cuenta de ahorros abrir','cuenta de ahorros online','cuenta de ahorros en linea'],
'requirements':['requisitos para abrir una cuenta de ahorros','con cuanto dinero puedo abrir una cuenta de ahorros','con cuanto puedo abrir una cuenta de ahorros','con cuanto se abre una cuenta de ahorros','contrato de cuenta de ahorros','cuanto dinero puedo tener en una cuenta de ahorros'],
'broad_banking':['cuenta bancaria','tasa de interes','intereses','tasa de interes bancos','tasa de interes de un banco','tasa de intereses de bancos','tasas de interes de bancos','intereses de los bancos','tasas de interes bancos ahorros'],
'definition':['que es una cuenta de ahorros','que es cuenta de ahorros','que es una cuenta de ahorro','cuenta de ahorros que es','que son cuenta de ahorro','que son cuentas de ahorro','que son cuentas de ahorros','cuenta de ahorros concepto','cuenta de ahorros tipos','para que sirve una cuenta de ahorros','que significa cuenta de ahorros','beneficios de una cuenta de ahorros','cuenta de ahorros beneficios','como funciona una cuenta de ahorros'],
'cci':['cci','que es cci','que es codigo interbancario','consulta cci','cci que significa','que es el cci','cci que es','como saber el cci de una cuenta','codigo de cuenta interbancario','cuenta interbancaria','que es cuenta interbancaria','que es una cuenta interbancaria'],
'saving_habits':['como ahorrar dinero','como ahorrar el dinero','ahorrar dinero como','ahorrar dinero','como ahorrar','como ahorrar dinero si gano poco','como puedo ahorrar mi dinero','como ahorrar dinero en casa','como ahorrar dinero en la casa','como ahorrar el dinero en casa','como ahorrar en casa dinero','plan de ahorro en soles','plan de ahorro','planes de ahorro'],
'app_service':['como cancelar una cuenta de ahorros','como saber el numero de mi cuenta de ahorros','como saber si mi cuenta de ahorros esta activa','consulta de cuenta de ahorros','numero de cuenta bancaria','cual es el numero de cuenta bancaria','estado de cuenta bancaria','estado de cuentas bancarias','extracto bancario'],
}
for k,vals in groups.items():
 for n in vals:
  if n in idx:manual[n]=k
missing_manual=[n for vals in groups.values() for n in vals if n not in idx]
otherbrands=['apap','atlantida','azteca','cuscatlan','cibao','uob','gnb','mi banco','bolivariano','av villas','pacifico','citibank','citiban','san jose','agrario','banco general','banco union','chase','colpatria','diners','finandina','global bank','ing','jfk','libreton','punto bb','banco de comercio','afp prima','al fin banco','almighty','american express']
foreign=['euros','euro','en uf','sucurs','extranjero','en el extranjero','sin dni','sin ine','pasaporte','colombia','ecuador','mexico','argentina','chile','espana','venezuela','bolivia','dominicana','costa rica','panama','uruguay','paraguay','brasil','usa','estados unidos','salvador','guatemala','honduras','nicaragua','guayaquil','bogota','medellin','buenos aires','cuit','cuil','cbu','clabe','rfc','rut','pesos']
bad=['detraccion','ruc','sunat','cts','afp','gratificacion','aguinaldo','tarjeta','pago de servicios','pagar servicios','internacional','credito','prestamo','empresa','empresarial','persona juridica','mancomun','compartida','infantil','juvenil','joven','nino','menor','beca','apuesta','casino','bet365','paypal','wise','payoneer','agua','luz','energia','broma','cuentas de fondeo','dinero falso','menaje','en ingles','abreviatura','contabilidad','asiento','libro','cuenta plus','cuenta ahorro plus','preferente','carta apertura','almighty']
audit=[]
for x in rows:
 n=x['normalized_keyword'];slug='noise';reason='No finalista manual; clasificar exclusión/revisión, no generar página por defecto'
 if 'pibank' in n:slug='own_brand';reason='Marca propia histórica, geografía actual no certificada por volumen'
 elif (x['lane']=='brand_competitor' and any(t in n for t in ['bcp','bbva','interbank','scotiabank','pichincha','banbif','falabella','ripley','mibanco','agora','ahorramas','efecti','bancom','caja ','caja.','comparabien','sbs'])) and not any(t in n for t in foreign+bad+['plazo fijo','deposito a plazo','login','iniciar sesion','telefono','sucursal','reclamo','consulta saldo','clave','contrasena']) and (('cuenta' in n and any(t in n for t in ['ahorr','super tasa','power'])) or ('ahorr' in n and any(t in n for t in ['interes','tasa','trea','comision','rendimiento'])) or ('sbs' in n and any(t in n for t in ['tasas de interes de bancos','compara tasas','tasas pasivas']))):slug='competitor_consideration';reason='Evaluación de alternativa ahorro peruana; cross-shopping condicional, no navegación ni captación acreditada'
 elif n in ['que banco o caja paga mas intereses','que banco o financiera paga mas intereses']:slug='compare_banks';reason='Compara tipos de institución; no marca individual, mezcla producto pendiente SERP'
 elif x['lane']=='brand_competitor' or any(t in n for t in otherbrands):slug='competitor';reason='Marca ajena sin evaluación compatible acreditada; benchmark/soporte, no demanda genérica'
 elif any(t in n for t in foreign) or any(t in n for t in bad):slug='incompatible';reason='Geografía, función, producto o segmento incompatible/ruido'
 elif n in manual:slug=manual[n];reason='Finalista manual por intención y oferta actual'
 elif x['lane']=='future_usd' or ('dolar' in n and ('ahorr' in n or 'cuenta' in n)):slug='usd';reason='Producto USD futuro, no disponible actualmente'
 elif 'alto rendimiento' in n or 'alta rentabilidad' in n:slug='high_yield';reason='Condicional por geografía/producto; no sumar variantes'
 elif 'digital' in n and ('cuenta' in n or 'banco' in n):slug='digital';reason='Puede exigir medios de pago; ahorro digital no equivale a adopción elegible'
 elif 'seguro de deposito' in n or 'seguro de los deposito' in n or 'seguro de depositos' in n:slug='insurance';reason='Asistencia confianza; no adquisiciones adicionales'
 elif 'trea' in n or ('tea' in n and ('interes' in n or 'tasa' in n)):slug='trea';reason='Comprensión de rendimiento; revisar precisión de fórmulas'
 elif ('simulador' in n or 'calcul' in n) and ('ahorr' in n or ('interes' in n and 'cuenta' in n)):slug='calculator';reason='Evaluación asistida; calculadora ya existe'
 elif 'banco seguro' in n or 'bancos seguros' in n or 'seguridad bancaria' in n:slug='safety';reason='Confianza asistida'
 elif 'transfer' in n:
  slug='transfer_time' if any(t in n for t in ['demora','tiempo','tarda','horario','inmediata','diferida']) else 'transfer';reason='Operación local/activación, frecuentemente usuario existente'
 elif 'cci' in n or 'interbancario' in n:slug='cci';reason='Operación/consulta; no adjudicar a adquisición'
 elif ('corriente' in n or 'plazo fijo' in n) and ('ahorro' in n and any(t in n for t in ['diferencia',' vs ',' o ',' y '])):slug='substitute_comparison';reason='Comparación educativa de sustitutos; no vender producto alternativo'
 elif 'como ahorrar' in n or 'ahorrar dinero' in n or 'plan de ahorro' in n:slug='saving_habits';reason='Educación amplia; revisión de utilidad antes de producir'
 elif any(t in n for t in ['que es','que son','beneficios','para que sirve','como funciona','concepto','significa']) and 'ahorr' in n and 'cuenta' in n:slug='definition';reason='Educación próxima al producto'
 f=fby[slug];audit.append({'keyword_id':x['id'],'keyword':x['keyword'],'previous_lane':x['lane'],'family_id':f['family_id'],'family':f['family'],'lane':f['lane'],'modelability':f['modelability'],'assignment_reason':reason,'volume':x['search_volume'],'volume_state':x['volume_state'],'core_keyword':x['core_keyword'],'source':x['source'],'updated_at':x['keyword_updated_at'],'all_sources':';'.join(x['sources'])})
for f in fs:
 a=[x for x in audit if x['family_id']==f['family_id']];f['member_keywords']=len(a);f['positive_volume_keywords']=sum(x['volume_state']=='value' for x in a);f['null_or_missing_keywords']=sum(x['volume_state'] in ['null','missing'] for x in a);f['aggregation_allowed']=False
 f['evidence_usable']='provider_market_estimate' if f['representative_keyword_id'] else 'product_corpus_and_serp_not_demand';f['serp_exact_measured']=f['representative_keyword'] in [c['query'] for c in json.loads((r/'serp-evidence.json').read_text())['captures']]
# All provider families get a verdict, including mixed families that require human split.
cores=collections.defaultdict(list)
for x in audit:cores[x['core_keyword'] or x['keyword']].append(x)
family_out=[]
for core,rs in sorted(cores.items()):
 modes=sorted(set(x['modelability'] for x in rs));ids=sorted(set(x['family_id'] for x in rs));family_out.append({'core_or_exact':core,'keyword_count':len(rs),'curated_family_ids':';'.join(ids),'modelability':'mixed_requires_split' if len(modes)>1 else modes[0],'modelability_details':';'.join(modes),'aggregation_allowed':False,'reason':'Text core is not an independent audience; use manual intent verdict, no MAX/sum universe','keyword_ids':';'.join(x['keyword_id'] for x in rs)})
def write_csv(name,a):
 with (p/name).open('w') as out:
  w=csv.DictWriter(out,fieldnames=list(a[0]));w.writeheader();w.writerows(a)
write_csv('oportunidades-curadas.csv',fs);write_csv('auditoria-keywords.csv',audit);write_csv('familias-proveedor.csv',family_out)
# Content corpus evidence is durable as URLs/title/hash/verdict, not full copied answers.
faq=json.loads(Path('/tmp/pibank-faq-census-20261006/inventory.json').read_text());fout=[]
for x in faq:
 n=x['n'];fid='B03'
 if n in [1,11]:fid='A01'
 elif n in [4,10,17,38]:fid='A07'
 elif n in [12,13,14,16,19,20,21,25]:fid='A02'
 elif n in [23,26,31,34,39,43,44,46]:fid='E09'
 elif n in [40,47,51]:fid='B01'
 fout.append({'n':n,'url':x['url'],'h1':x['h1'],'status':x['status'],'read_date':x['readDate'],'body_sha256':x['sha256'],'family':fid,'existing':True,'default_action':'review/improve existing; new URL only if distinct gap','conversion_measured':False})
write_csv('cobertura-corpus-publico.csv',fout)
counts=dict(collections.Counter(x['lane'] for x in audit));assert len(audit)==4855 and len({x['keyword_id'] for x in audit})==4855
v={'as_of':'2026-10-06','status':'PASS reaudited bounded corpus; decision support only','source_dataset_sha256':hashlib.sha256((r/'keyword-dataset.json').read_bytes()).hexdigest(),'source_monthly_panel_sha256':hashlib.sha256((r/'monthly-demand-inputs.json').read_bytes()).hexdigest(),'keyword_count':len(audit),'all_keywords_have_verdict':True,'curated_opportunity_families':len(fs),'provider_core_or_exact_families':len(family_out),'lane_keyword_counts_not_demand':counts,'faq_read':len(faq),'faq_source':'same-day previously obtained public census; no new crawl','manual_keys_not_found':missing_manual,'aggregation_policy':'No sum of representative volumes or cores as market; no claim unique users; no blanket MAX; opportunities can overlap','new_paid_calls':0,'additional_provider_cost_usd':0,'own_brand_baseline':None,'aeo_baseline':None,'eligible_sessions':None,'onboarding_conversion':None,'funding_and_balance_baseline':None,'full_program_return':None,'history_policy':'Original research/model unchanged; representative history available source rows, not2027 forecast','checks':{'unique_ids':True,'all_rows_classified':True,'all_sources_local':all((p.parent/'research'/x['source']).exists() for x in audit if x['source']),'no_acquisition_forecast':True,'no_current_brand_volume_inferred':True}}
(p/'validacion-demanda.json').write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'families':len(fs),'corefamilies':len(family_out),'counts':counts,'manual_missing':missing_manual},ensure_ascii=False))
