// ============================================================
// Greenhouse PostgreSQL — Kysely Database Types
// ============================================================
// AUTO-GENERATED by kysely-codegen. Do not edit manually.
// Regenerate with: pnpm db:generate-types
//
// This is a placeholder until the first codegen run against
// the live database. Once generated, this file will contain
// typed interfaces for all 9 schemas:
//   greenhouse_core, greenhouse_serving, greenhouse_sync,
//   greenhouse_hr, greenhouse_payroll, greenhouse_finance,
//   greenhouse_delivery, greenhouse_crm, greenhouse_ai
// ============================================================

/**
 * Placeholder DB interface. After running `pnpm db:generate-types`,
 * this file is replaced with full table/column types from the live schema.
 */
export interface DB {
  [key: string]: Record<string, unknown>
}
