import {dir,svg,rect,text,label,im,N,B,W} from './build.mjs';import sharp from 'sharp';import {readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';import {join} from 'node:path';import {createHash} from 'node:crypto';
const entries=[];async function crop(file,id,object,view,box){const out=join(dir,'individuales',id+'.png');await sharp(join(dir,'final',file)).extract(box).flatten({background:W}).png().toFile(out);entries.push({id,object,view,file:'individuales/'+id+'.png',source:'final/'+file,status:'concepto-para-aprobacion'});}
for(const [file,prefix]of [['03-mugs.png','mug'],['07-globe-colores.png','mug-globe']])for(let r=0;r<2;r++)for(let c=0;c<4;c++){const ob=prefix==='mug'?(r?'mug-azul':'mug-blanco-hacer'):(r?'mug-globe-naranja':'mug-globe-magenta'),v=['frente','tres-cuartos','reverso','cenital'][c];await crop(file,ob+'-'+v,ob,v,{left:c*384,top:r*512,width:384,height:512});}
const agendaBoxes=[{left:185,top:0,width:425,height:480},{left:775,top:0,width:730,height:485},{left:175,top:485,width:445,height:480},{left:688,top:480,width:817,height:530}];for(let i=0;i<4;i++)await crop('02-agenda.png','agenda-'+['frente','tres-cuartos','reverso','abierta'][i],'agenda',['frente','tres-cuartos','reverso','abierta'][i],agendaBoxes[i]);
for(let i=0;i<4;i++)await crop('04-mac.png','mac-'+['tapa-cenital','cerrado-tres-cuartos','abierto-reverso','abierto-frente'][i],'mac',['tapa-cenital','cerrado-tres-cuartos','abierto-reverso','abierto-frente'][i],{left:i%2*768,top:i<2?0:480,width:768,height:i<2?470:544});
for(let i=0;i<4;i++){const v=['frente','tres-cuartos','perfil','reverso'][i],r=Math.floor(i/2);await crop('05-pizarra.png','pizarra-'+v,'pizarra',v,{left:i%2*768,top:r?460:0,width:768,height:r?564:460});}
for(let r=0;r<3;r++)for(let c=0;c<3;c++){const ob=['lapicero','bandeja','sujetalibros'][r],v=['frente','tres-cuartos',r===2?'elevada':'superior'][c];const top=[0,327,640][r],bottom=[325,638,1024][r];await crop('06-escritorio.png',ob+'-'+v,ob,v,{left:c*512+2,top,width:508,height:bottom-top});}
for(let i=0;i<4;i++){const v=['frente','tres-cuartos','posterior','cenital'][i];await crop('08-ship.png','ship-'+v,'ship',v,{left:i%2*700,top:Math.floor(i/2)*700,width:700,height:700});entries.at(-1).status='forma-aprobada-2026-09-17-aplicacion-pendiente';}
const brandFiles=['logo-full.svg','logo-negative.svg','SVG/isotipo-full-efeonce.svg','SVG/isotipo-goble-full.svg','SVG/isotipo-wave.svg','SVG/isotipo-reach-full.svg'];const sources=[];for(const f of brandFiles)sources.push({path:'public/branding/'+f,sha256:createHash('sha256').update(await readFile(join(dir,'../../../public/branding',f))).digest('hex')});
await writeFile(join(dir,'manifest.json'),JSON.stringify({title:'Ideas con dirección',version:2,status:'propuesta-para-aprobacion',date:'2026-09-25',masterbrand:'Efeonce',subbrands:['Globe','Wave','Reach'],sources,views:entries,production:'Renders conceptuales multivista; no planos acotados ni especificaciones de fabricación.',typography:{source:'axisAdvertising (trial)',advisor:'Brochure / 1–3 palabras / Impactar',main:'Bricolage Grotesque',structure:'Poppins',render:'Contornos derivados de archivos de fuente reales'},provenance:{baseRenders:'../apertura-v1/prompts.json',officePrompt:'../apertura-v1/office-batch.json',officeFicha:'../apertura-v1/office-ficha.json',notebookEdit:'bases/agenda.png - generación editada a tela azul lisa; composición tipográfica posterior',branding:'SVG oficiales compuestos después de generar'}} ,null,2));
const pic=async(path,x,y,w,h)=>`<image href="data:image/png;base64,${(await readFile(join(dir,path))).toString('base64')}" x="${x}" y="${y}" width="${w}" height="${h}" preserveAspectRatio="xMidYMid meet"/>`;
const board=svg(1800,1260,`${rect(0,0,1800,1260,W)}${im('logo',60,45,220,60)}${label('COLECCIÓN DE ESTUDIO / PROPUESTA 02',1190,83,13,N,600)}
${text('La idea toma forma.',54,214,104,N,{maxWidth:1680})}
${label('Una familia con distintas intensidades: expresión, firma y material.',60,259,20,N)}
${await pic('individuales/agenda-tres-cuartos.png',20,299,780,506)}
${await pic('individuales/mug-blanco-hacer-frente.png',800,282,344,480)}
${await pic('individuales/mac-cerrado-tres-cuartos.png',1112,329,652,435)}
${label('AGENDA / LA VOZ GRÁFICA',61,814,13,N,600)}${label('MUG / UNA PALABRA',845,814,13,N,600)}${label('MAC / IDENTIDAD PERSONAL',1209,814,13,N,600)}
${await pic('individuales/bandeja-tres-cuartos.png',40,863,487,281)}
${await pic('individuales/lapicero-tres-cuartos.png',598,863,478,281)}
${await pic('individuales/sujetalibros-tres-cuartos.png',1200,839,436,310)}
${label('OBJETOS DE APOYO / COLOR, MATERIAL Y FUNCIÓN',60,1210,14,N,600)}
`);await writeFile(join(dir,'00-coleccion.svg'),board);await sharp(Buffer.from(board)).png().toFile(join(dir,'00-coleccion.png'));
await mkdir(join(dir,'fonts'),{recursive:true});await copyFile(join(dir,'../../../src/assets/fonts/BricolageGrotesque-Variable.ttf'),join(dir,'fonts/bricolage.ttf'));await copyFile('/Users/jreye/Library/Fonts/Poppins-Regular.ttf',join(dir,'fonts/poppins.ttf'));await copyFile(join(dir,'../../../public/branding/logo-full.svg'),join(dir,'art/efeonce.svg'));
const sections=[
['linea','01-linea-grafica.png','01 / La línea gráfica','Dirección, encuadre y enfoque','Tres comportamientos de un mismo lenguaje. La curva abierta aporta continuidad; los corchetes ordenan; el círculo selecciona dentro de un campo de posibilidades. La tipografía lleva la idea.',''],
['coleccion','00-coleccion.png','02 / La colección','Expresión, firma y material','La agenda concentra la gráfica. El mug blanco tiene una voz breve. Mac y pizarra identifican. Lapicero, bandeja y sujetalibros participan por color y forma.',''],
['estudio','final/09-estudio.png','03 / Aplicación espacial','Un estudio que piensa y hace','Mural tipográfico, mesa de trabajo, materiales cálidos y herramientas a la vista. Boceto de ambiente para puesta en escena; aún no es un proyecto arquitectónico medido.',''],
['agenda','final/02-agenda.png','04 / Agenda','Ideas con dirección','Tela azul, impresión blanca, páginas punteadas y firma discreta al reverso. Frente, tres cuartos, reverso y apertura.','agenda'],
['mugs','final/03-mugs.png','05 / Cerámica','Una palabra. O solo color.','Blanco con interior azul y “Hacer.”; azul con interior blanco, sin gráfica. Cuatro vistas por variante.','mug-blanco-hacer,mug-azul'],
['mac','final/04-mac.png','06 / Mac','Dos gestos con intención','Ship oficial y sticker tipográfico. Cuatro vistas para mantener posiciones. El render sirve para explorar la aplicación; el modelo y las medidas del equipo se fijarán en producción.','mac'],
['pizarra','final/05-pizarra.png','07 / Acrílico','La gráfica ayuda a trabajar','Firma Efeonce, encuadre abierto y tres campos: Enfoque, Ideas y Acción. Frente, tres cuartos, perfil y reverso.','pizarra'],
['escritorio','final/06-escritorio.png','08 / Apoyos de estudio','Presencia sin logotipo','Lapicero, bandeja y sujetalibros. Navy, azul activo y materiales táctiles; tres vistas por objeto.','lapicero,bandeja,sujetalibros'],
['globe','final/07-globe-colores.png','09 / Acento de submarca','El magenta de Globe','El isotipo oficial del globo es principalmente #BB1954, con acento #FF6500. Se comparan magenta y naranja; naranja es también el primario del tema de producto. Efeonce conserva sus azules como base.','mug-globe-magenta,mug-globe-naranja'],
['ship','final/08-ship.png','10 / Símbolo','Un objeto de identidad','Se reutiliza el ship 3D de la biblioteca aprobada. Su presencia en esta colección está pendiente de revisión. Uso puntual como escultura de escritorio o utilería.','ship']
];
const links=ob=>entries.filter(e=>ob.split(',').includes(e.object)).map(e=>`<a href="${e.file}" download>${e.object.replaceAll('-',' ')} · ${e.view.replaceAll('-',' ')}</a>`).join('');
const html=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Efeonce — Ideas con dirección</title><style>
@font-face{font-family:Bricolage;src:url(fonts/bricolage.ttf)}@font-face{font-family:Poppins;src:url(fonts/poppins.ttf)}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f5f4ef;color:#023c70;font-family:Poppins,Arial,sans-serif}a{color:inherit;text-underline-offset:5px}header{padding:28px 5%;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #cbd4d9;gap:28px}header img{width:190px}header p{font-size:12px;letter-spacing:.06em;text-align:right}main{max-width:1600px;margin:auto}section{padding:68px 5% 20px;scroll-margin-top:20px}.intro{padding-top:65px}h1,h2{font-family:Bricolage,Arial,sans-serif;font-variation-settings:'wght' 740,'wdth' 96,'opsz' 76;letter-spacing:-.03em;line-height:.98}h1{font-size:clamp(55px,7vw,105px);max-width:1000px;margin:20px 0 30px}h2{font-size:clamp(32px,4vw,60px);margin:12px 0 20px}p{max-width:960px;line-height:1.7;font-size:17px}.eyebrow{font-size:12px;letter-spacing:.06em;text-transform:uppercase}.actions,nav{display:flex;flex-wrap:wrap;gap:14px 25px;margin:26px 0}.actions a{padding:13px 22px;background:#023c70;color:white;text-decoration:none;border-radius:2px;font-size:14px}nav a{font-size:13px}figure{margin:32px 0 0}figure img{width:100%;display:block;background:#fff}figcaption{font-size:12px;margin-top:12px;color:#526573}.principles{display:grid;grid-template-columns:repeat(3,1fr);gap:30px;padding:30px 0}.principles p{font-size:14px}.principles strong{font-size:19px}details{padding:20px 0;border-bottom:1px solid #cbd4d9}summary{cursor:pointer}.files{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:20px 0;font-size:12px}.note{background:white;padding:28px;margin-top:24px}.note p{font-size:14px}footer{padding:60px 5%;font-size:13px}@media(max-width:650px){header img{width:140px}header p{font-size:10px}section{padding:40px 5% 10px}.principles{grid-template-columns:1fr;gap:5px}.files{grid-template-columns:1fr}p{font-size:15px}.actions a{width:100%;text-align:center}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}}@media print{header,nav,.actions,details{display:none}section{break-before:page;padding:10px}figure{margin-top:15px}p{font-size:12px}h2{font-size:30px}}
</style><header><img src="art/efeonce.svg" alt="Efeonce"><p>EXPLORACIÓN DE IDENTIDAD Y OBJETOS<br>25 SEPTIEMBRE 2026 · VERSIÓN 02</p></header><main>
<section class="intro"><div class="eyebrow">Propuesta para aprobación</div><h1>Ideas con dirección.</h1><p>Una agencia premium, creativa, estratégica y digital. Una línea con tipografía expresiva, decisiones claras de composición y objetos que se sienten parte de un estudio real.</p><div class="actions"><a href="revision-efeonce-v2.pdf" download>Descargar revisión PDF</a><a href="referencias-efeonce-v2.zip" download>Descargar las 41 vistas + artes</a></div><nav><a href="#linea">La línea</a><a href="#coleccion">Colección</a><a href="#estudio">Estudio</a><a href="#agenda">Objetos y vistas</a><a href="#criterio">Criterio de marca</a></nav></section>
${sections.map(([id,file,kicker,title,desc,objects])=>`<section id="${id}"><div class="eyebrow">${kicker}</div><h2>${title}</h2><p>${desc}</p><figure><a href="${file}" target="_blank"><img src="${file}" alt="${title}. ${desc}" loading="lazy"></a><figcaption>Abre la imagen para verla a resolución completa. Propuesta pendiente de aprobación.</figcaption></figure>${objects?`<details><summary>Descargar vistas individuales sobre blanco</summary><div class="files">${links(objects)}</div></details>`:''}</section>`).join('')}
<section id="criterio"><div class="eyebrow">Criterio de marca</div><h2>Efeonce al frente.</h2><div class="principles"><div><strong>Premium</strong><p>Escala editorial, espacio, material y acabados. La composición mantiene una voz dominante por superficie.</p></div><div><strong>Creativa y estratégica</strong><p>La idea se expresa con carácter. El encuadre y el foco hacen visible una elección; los recorridos relacionan sus partes.</p></div><div><strong>Digital</strong><p>Repetición controlada, variación y transformación. Los mismos recursos pueden crecer a pantalla y movimiento.</p></div></div><div class="note"><p><strong>Universo de marca.</strong> El ship conserva su función de símbolo principal. Del círculo y el globo exploramos apertura y enfoque; de Wave, encuadre y ritmo; de Reach, dirección. Son hipótesis de diseño, no nuevos significados oficiales de los isotipos. Las submarcas aparecen cuando el contexto las requiere.</p><p><strong>Uso selectivo.</strong> Agenda: lenguaje protagonista. Muro: idea y firma. Mac: símbolo y tipografía. Pizarra: firma y estructura útil. Cerámica y apoyos: material, color o una expresión breve.</p><p><strong>Estado.</strong> “Ideas con dirección” es un concepto y copy de exploración. Los renders muestran referencias visuales; medidas, materiales finales, tintas, tolerancias y consistencia geométrica deberán fijarse al preparar producción. Reconocimiento sin logo aún no evaluado.</p></div><details><summary>Artes vectoriales de la propuesta</summary><div class="files"><a href="art/agenda-portada.svg" download>Portada de agenda</a><a href="art/agenda-tinta.svg" download>Tinta de portada</a><a href="art/agenda-reverso.svg" download>Firma del reverso</a><a href="art/poster-enfoque.svg" download>Póster de encuadre</a><a href="art/poster-campo.svg" download>Póster de enfoque</a><a href="art/mural-tinta.svg" download>Mural</a><a href="art/sticker-hacer.svg" download>Sticker Hacer</a><a href="art/mug-hacer.svg" download>Tipografía del mug</a></div></details></section>
</main><footer>Propuesta 02 · Efeonce · Bricolage Grotesque + Poppins · SVG oficiales conservados.<br>Imágenes generadas y composición gráfica posterior. Para revisión de dirección creativa.</footer></html>`;
await writeFile(join(dir,'index.html'),html);await writeFile(join(dir,'sections.json'),JSON.stringify(sections,null,2));console.log(entries.length+' vistas, galería y colección.');
