<?php
/** Guarded atomic Elementor cutover of the operator-approved Content Ops design. */
if(!defined('ABSPATH')||!class_exists('WP_CLI'))exit;
$id=242603;$expected='4c38754c2e086bd4e60469df0ad75ae52a07c62d9feeb3aedf2272f6afb94938';
if(!current_user_can('edit_post',$id)||get_post_status($id)!=='publish'||get_post_field('post_name',$id)!=='servicio-marketing-de-contenidos'||!hash_equals($expected,hash('sha256',get_post_meta($id,'_elementor_data',true))))WP_CLI::error('Identity or content drift. Inspect before retry.');
$home=(int)get_option('page_on_front');$protected=[];foreach([$home,244079,251279,251300,251627] as $p)$protected[$p]=hash('sha256',get_post_meta($p,'_elementor_data',true));
$shell=[];foreach(['page_on_front','sidebars_widgets','widget_block','theme_mods_ohio-child','ohio_options'] as $k)$shell[$k]=get_option($k);
$doc=\Elementor\Plugin::$instance->documents->get($id);$widgets=\Elementor\Plugin::$instance->widgets_manager->get_widget_types();$elements=[];
$modules=['hero','proof','problem','system','atomization','hub','review','editorial','modes','ecosystem','business','faq','conversion'];
foreach($modules as $i=>$module){$name='greenhouse_content_'.$module;if(!isset($widgets[$name]))WP_CLI::error('Widget absent: '.$name);$d=$widgets[$name]->content_schema();$controls=$widgets[$name]->get_controls();$v=$d['defaults'];foreach($d['fields'] as $f){if(!isset($controls[$f['key']]))WP_CLI::error('Control absent: '.$f['key']);if($f['type']==='media')$v[$f['key']]['url']=EO_Content_Marketing_Base::asset_url($v[$f['key']]['url']);}
$v['motion']='yes';$v['_title']=$d['title'];if($module==='conversion'){$v['form_key']='18b228e9-106a-402e-a6f2-a8c5469e73d7';$v['form_surface']='fhsf-efeonce-content-marketing';}
$zero=['unit'=>'px','top'=>'0','right'=>'0','bottom'=>'0','left'=>'0','isLinked'=>true];$v['_margin']=$zero;$v['_padding']=$zero;
$elements[]=['id'=>substr(md5('cm-section-'.$module),0,7),'elType'=>'container','isInner'=>false,'settings'=>['_title'=>sprintf('%02d · %s',$i+1,$d['title']),'content_width'=>'full','flex_direction'=>'column','flex_gap'=>['column'=>'0','row'=>'0','unit'=>'px','isLinked'=>true],'padding'=>$zero,'margin'=>$zero,'css_classes'=>'gh-content-section gh-content-section--'.$module.' clb__'.$d['scheme'].'_section'],'elements'=>[['id'=>substr(md5('cm-'.$module),0,7),'elType'=>'widget','widgetType'=>$name,'settings'=>$v,'elements'=>[]]]];}
$snapshot='_gh_content_marketing_before_'.gmdate('Ymd_His');
if(!add_option($snapshot,['post'=>get_post($id,ARRAY_A),'meta'=>get_post_meta($id),'elements'=>$doc->get_elements_data(),'settings'=>$doc->get_settings(),'protected'=>$protected,'shell'=>$shell],'',false))WP_CLI::error('Backup failed.');
$cover=WP_PLUGIN_DIR.'/eo-elementor-widgets/assets/img/content-marketing/social-cover.jpg';if(!is_readable($cover))WP_CLI::error('Social image missing.');
require_once ABSPATH.'wp-admin/includes/file.php';require_once ABSPATH.'wp-admin/includes/media.php';require_once ABSPATH.'wp-admin/includes/image.php';
$temp=wp_tempnam('content-marketing-social.jpg');copy($cover,$temp);$attachment=media_handle_sideload(['name'=>'efeonce-content-marketing-content-ops.jpg','tmp_name'=>$temp],$id,'Content Marketing y Content Ops — Efeonce');
if(is_wp_error($attachment))WP_CLI::error('Media import failed. Snapshot: '.$snapshot);
update_post_meta($attachment,'_wp_attachment_image_alt','Content Marketing y Content Ops de Efeonce: una idea, muchas expresiones, un solo sistema.');
$settings=$doc->get_settings();$settings['post_featured_image']=['id'=>$attachment,'url'=>wp_get_attachment_url($attachment)];$settings['hide_title']='yes';$settings['page_layout']='default';
$settings['custom_css']='body.page-id-242603 .elementor.elementor-242603,body.page-id-242603 .gh-content-section,body.page-id-242603 .gh-content-section>.e-con-inner,body.page-id-242603 .gh-content-section>.elementor-widget,body.page-id-242603 .gh-content-section .elementor-widget-container{width:100%!important;max-width:100%!important;margin:0!important;padding:0!important;gap:0!important}body.page-id-242603 .page-container.-full-w,body.page-id-242603 .page-container.-full-w>.page-content,body.page-id-242603 .entry-content{width:100%!important;max-width:100%!important;margin:0!important;padding:0!important}body.page-id-242603 .gh-content-section{left:0!important;right:0!important;inset-inline-start:0!important;inset-inline-end:0!important}body.page-id-242603 .site-content,body.page-id-242603 .page-container,body.page-id-242603 .page-content,body.page-id-242603 .entry-content,body.page-id-242603 .gh-content-section--system{overflow:visible}body.page-id-242603{overflow-x:clip}';
if(false===$doc->save(['elements'=>$elements,'settings'=>$settings]))WP_CLI::error('Elementor save failed. Snapshot: '.$snapshot);
foreach(['page_add_wrapper'=>'0','page_add_top_padding'=>'0','page_full_width_margins_size'=>'0px','page_breadcrumbs_visibility'=>'0','page_header_title_visibility'=>'0'] as $k=>$v)update_post_meta($id,$k,$v);
$title='Agencia de Content Marketing y Content Ops | Efeonce';
$description='Estrategia, producción y operación de contenidos con Efeonce. Del research a la publicación en tu CMS, con revisión visible y adaptación para cada canal.';
$meta=['_eo_content_marketing_enabled'=>'1','_gh_content_marketing_schema'=>'contentMarketingModule.v1','_yoast_wpseo_title'=>$title,'_yoast_wpseo_metadesc'=>$description,'_yoast_wpseo_opengraph-title'=>$title,'_yoast_wpseo_opengraph-description'=>$description,'_yoast_wpseo_twitter-title'=>$title,'_yoast_wpseo_twitter-description'=>$description,'_yoast_wpseo_canonical'=>'https://efeoncepro.com/servicio-marketing-de-contenidos/','_yoast_wpseo_meta-robots-noindex'=>'2','_yoast_wpseo_meta-robots-nofollow'=>'','_yoast_wpseo_bctitle'=>'Content Marketing','_yoast_wpseo_focuskw'=>'agencia de marketing de contenidos','_yoast_wpseo_opengraph-image'=>wp_get_attachment_url($attachment),'_yoast_wpseo_opengraph-image-id'=>(string)$attachment,'_yoast_wpseo_twitter-image'=>wp_get_attachment_url($attachment),'_yoast_wpseo_twitter-image-id'=>(string)$attachment,'_thumbnail_id'=>(string)$attachment];
foreach($meta as $k=>$v)update_post_meta($id,$k,$v);
wp_update_post(['ID'=>$id,'post_status'=>'publish']);
YoastSEO()->classes->get('Yoast\\WP\\SEO\\Builders\\Indexable_Builder')->build_for_id_and_type($id,'post');
$actual=json_decode(get_post_meta($id,'_elementor_data',true),true);if(count($actual)!==13)WP_CLI::error('Unexpected saved document; inspect snapshot.');
foreach($actual as $i=>$container){$w=$container['elements'][0];if($w['widgetType']!==$elements[$i]['elements'][0]['widgetType'])WP_CLI::error('Widget readback failed.');foreach($elements[$i]['elements'][0]['settings'] as $k=>$v)if(($w['settings'][$k]??null)!==$v)WP_CLI::error('Settings readback failed: '.$modules[$i].'/'.$k);}
foreach($meta as $k=>$v)if((string)get_post_meta($id,$k,true)!==(string)$v)WP_CLI::error('Metadata readback failed: '.$k);
foreach($protected as $p=>$hash)if(!hash_equals($hash,hash('sha256',get_post_meta($p,'_elementor_data',true))))WP_CLI::error('Unrelated page changed; inspect concurrently.');
foreach($shell as $k=>$v)if(get_option($k)!==$v)WP_CLI::error('Site chrome changed; inspect concurrently.');
\Elementor\Plugin::$instance->files_manager->clear_cache();clean_post_cache($id);WP_CLI::runcommand('cache flush',['return'=>true]);WP_CLI::runcommand('kinsta cache purge --all',['return'=>true]);
echo wp_json_encode(['status'=>'published_verified','postId'=>$id,'url'=>get_permalink($id),'snapshot'=>$snapshot,'attachmentId'=>$attachment,'hash'=>hash('sha256',get_post_meta($id,'_elementor_data',true)),'widgets'=>count($actual),'protectedUnchanged'=>true,'title'=>$title,'description'=>$description],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
